// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * Governance policy settings.
 * 
 */
public final class TenantGovernancePolicySettingsArgs extends com.pulumi.resources.ResourceArgs {

    public static final TenantGovernancePolicySettingsArgs Empty = new TenantGovernancePolicySettingsArgs();

    /**
     * Enable desktop flow data policy management.
     * 
     */
    @Import(name="enableDesktopFlowDataPolicyManagement")
    private @Nullable Output<Boolean> enableDesktopFlowDataPolicyManagement;

    /**
     * @return Enable desktop flow data policy management.
     * 
     */
    public Optional<Output<Boolean>> enableDesktopFlowDataPolicyManagement() {
        return Optional.ofNullable(this.enableDesktopFlowDataPolicyManagement);
    }

    private TenantGovernancePolicySettingsArgs() {}

    private TenantGovernancePolicySettingsArgs(TenantGovernancePolicySettingsArgs $) {
        this.enableDesktopFlowDataPolicyManagement = $.enableDesktopFlowDataPolicyManagement;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TenantGovernancePolicySettingsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TenantGovernancePolicySettingsArgs $;

        public Builder() {
            $ = new TenantGovernancePolicySettingsArgs();
        }

        public Builder(TenantGovernancePolicySettingsArgs defaults) {
            $ = new TenantGovernancePolicySettingsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enableDesktopFlowDataPolicyManagement Enable desktop flow data policy management.
         * 
         * @return builder
         * 
         */
        public Builder enableDesktopFlowDataPolicyManagement(@Nullable Output<Boolean> enableDesktopFlowDataPolicyManagement) {
            $.enableDesktopFlowDataPolicyManagement = enableDesktopFlowDataPolicyManagement;
            return this;
        }

        /**
         * @param enableDesktopFlowDataPolicyManagement Enable desktop flow data policy management.
         * 
         * @return builder
         * 
         */
        public Builder enableDesktopFlowDataPolicyManagement(Boolean enableDesktopFlowDataPolicyManagement) {
            return enableDesktopFlowDataPolicyManagement(Output.of(enableDesktopFlowDataPolicyManagement));
        }

        public TenantGovernancePolicySettingsArgs build() {
            return $;
        }
    }

}
