// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Phase 0 / Phase 2 POC component — validates the bidirectional construct bridge.
 *
 *     Accepts a ``label`` input and echoes it as ``labelOut``.
 *     Also exposes a placeholder ``resourceId`` output following AVM conventions.
 */
export class PocComponent extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'powerplatform:components:PocComponent';

    /**
     * Returns true if the given object is an instance of PocComponent.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PocComponent {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PocComponent.__pulumiType;
    }

    declare public /*out*/ readonly labelOut: pulumi.Output<string>;
    declare public /*out*/ readonly resourceId: pulumi.Output<string>;

    /**
     * Create a PocComponent resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PocComponentArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["enableTelemetry"] = args?.enableTelemetry;
            resourceInputs["label"] = args?.label;
            resourceInputs["labelOut"] = undefined /*out*/;
            resourceInputs["resourceId"] = undefined /*out*/;
        } else {
            resourceInputs["labelOut"] = undefined /*out*/;
            resourceInputs["resourceId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PocComponent.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a PocComponent resource.
 */
export interface PocComponentArgs {
    enableTelemetry?: boolean;
    label?: string;
}
