// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * AVM-aligned component that manages a Power Platform deployment pipeline lifecycle.
 */
export class ResDeploymentPipeline extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'powerplatform:components:ResDeploymentPipeline';

    /**
     * Returns true if the given object is an instance of ResDeploymentPipeline.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ResDeploymentPipeline {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ResDeploymentPipeline.__pulumiType;
    }

    declare public /*out*/ readonly deploymentEnvironmentIds: pulumi.Output<{[key: string]: string}>;
    declare public /*out*/ readonly deploymentStageIds: pulumi.Output<{[key: string]: string}>;
    declare public /*out*/ readonly pipelineId: pulumi.Output<string>;
    declare public readonly pipelineName: pulumi.Output<string>;
    declare public /*out*/ readonly pipelineTeamId: pulumi.Output<string>;
    declare public /*out*/ readonly resourceId: pulumi.Output<string>;

    /**
     * Create a ResDeploymentPipeline resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ResDeploymentPipelineArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.devEnvironmentKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'devEnvironmentKey'");
            }
            if (args?.environments === undefined && !opts.urn) {
                throw new Error("Missing required property 'environments'");
            }
            if (args?.hostEnvironmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'hostEnvironmentId'");
            }
            if (args?.pipelineName === undefined && !opts.urn) {
                throw new Error("Missing required property 'pipelineName'");
            }
            if (args?.pipelineStages === undefined && !opts.urn) {
                throw new Error("Missing required property 'pipelineStages'");
            }
            resourceInputs["deploymentPipelineUserRoleId"] = args?.deploymentPipelineUserRoleId;
            resourceInputs["devEnvironmentKey"] = args?.devEnvironmentKey;
            resourceInputs["enableAiDeploymentNotes"] = args?.enableAiDeploymentNotes;
            resourceInputs["enableRedeployment"] = args?.enableRedeployment;
            resourceInputs["enableTelemetry"] = args?.enableTelemetry;
            resourceInputs["environments"] = args?.environments;
            resourceInputs["hostEnvironmentId"] = args?.hostEnvironmentId;
            resourceInputs["lifecycleState"] = args?.lifecycleState;
            resourceInputs["pipelineDescription"] = args?.pipelineDescription;
            resourceInputs["pipelineName"] = args?.pipelineName;
            resourceInputs["pipelineStages"] = args?.pipelineStages;
            resourceInputs["rootBusinessUnitId"] = args?.rootBusinessUnitId;
            resourceInputs["securityGroupId"] = args?.securityGroupId;
            resourceInputs["deploymentEnvironmentIds"] = undefined /*out*/;
            resourceInputs["deploymentStageIds"] = undefined /*out*/;
            resourceInputs["pipelineId"] = undefined /*out*/;
            resourceInputs["pipelineTeamId"] = undefined /*out*/;
            resourceInputs["resourceId"] = undefined /*out*/;
        } else {
            resourceInputs["deploymentEnvironmentIds"] = undefined /*out*/;
            resourceInputs["deploymentStageIds"] = undefined /*out*/;
            resourceInputs["pipelineId"] = undefined /*out*/;
            resourceInputs["pipelineName"] = undefined /*out*/;
            resourceInputs["pipelineTeamId"] = undefined /*out*/;
            resourceInputs["resourceId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ResDeploymentPipeline.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a ResDeploymentPipeline resource.
 */
export interface ResDeploymentPipelineArgs {
    deploymentPipelineUserRoleId?: string;
    devEnvironmentKey: string;
    enableAiDeploymentNotes?: boolean;
    enableRedeployment?: boolean;
    enableTelemetry?: boolean;
    environments: {[key: string]: inputs.components.PipelineEnvironmentEntryArgs};
    hostEnvironmentId: string;
    lifecycleState?: string;
    pipelineDescription?: string;
    pipelineName: string;
    pipelineStages: inputs.components.PipelineStageConfigArgs[];
    rootBusinessUnitId?: string;
    securityGroupId?: string;
}
