// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Components.Inputs
{

    /// <summary>
    /// Dataverse provisioning configuration.
    /// 
    ///     Mirrors the ``var.dataverse`` object in the AVM ``res-environment`` module.
    ///     Passing a :class:`DataverseConfig` instance triggers Dataverse provisioning
    ///     on the underlying ``Environment`` resource.
    /// 
    ///     Field names follow the AVM variable names (snake_case).  The component maps
    ///     them to the camelCase wire names expected by the Pulumi provider.
    ///     
    /// </summary>
    public sealed class DataverseConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("administrationModeEnabled")]
        public bool? AdministrationModeEnabled { get; set; }

        [Input("backgroundOperationEnabled")]
        public bool? BackgroundOperationEnabled { get; set; }

        [Input("currencyCode")]
        public string? CurrencyCode { get; set; }

        [Input("domain")]
        public string? Domain { get; set; }

        [Input("languageCode")]
        public int? LanguageCode { get; set; }

        [Input("securityGroupId")]
        public string? SecurityGroupId { get; set; }

        [Input("templateMetadata")]
        public string? TemplateMetadata { get; set; }

        [Input("templates")]
        private List<string>? _templates;
        public List<string> Templates
        {
            get => _templates ?? (_templates = new List<string>());
            set => _templates = value;
        }

        public DataverseConfigArgs()
        {
        }
        public static new DataverseConfigArgs Empty => new DataverseConfigArgs();
    }
}
