// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * OData $expand parameter for a navigation property in getDataRecords.
 * 
 */
public final class DataRecordsExpandParamArgs extends com.pulumi.resources.ResourceArgs {

    public static final DataRecordsExpandParamArgs Empty = new DataRecordsExpandParamArgs();

    /**
     * OData filter expression for the expanded entity.
     * 
     */
    @Import(name="filter")
    private @Nullable Output<String> filter;

    /**
     * @return OData filter expression for the expanded entity.
     * 
     */
    public Optional<Output<String>> filter() {
        return Optional.ofNullable(this.filter);
    }

    /**
     * The navigation property name to expand.
     * 
     */
    @Import(name="navigationProperty", required=true)
    private Output<String> navigationProperty;

    /**
     * @return The navigation property name to expand.
     * 
     */
    public Output<String> navigationProperty() {
        return this.navigationProperty;
    }

    /**
     * Comma-separated list of columns to include for the expanded entity.
     * 
     */
    @Import(name="select")
    private @Nullable Output<String> select;

    /**
     * @return Comma-separated list of columns to include for the expanded entity.
     * 
     */
    public Optional<Output<String>> select() {
        return Optional.ofNullable(this.select);
    }

    private DataRecordsExpandParamArgs() {}

    private DataRecordsExpandParamArgs(DataRecordsExpandParamArgs $) {
        this.filter = $.filter;
        this.navigationProperty = $.navigationProperty;
        this.select = $.select;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DataRecordsExpandParamArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DataRecordsExpandParamArgs $;

        public Builder() {
            $ = new DataRecordsExpandParamArgs();
        }

        public Builder(DataRecordsExpandParamArgs defaults) {
            $ = new DataRecordsExpandParamArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param filter OData filter expression for the expanded entity.
         * 
         * @return builder
         * 
         */
        public Builder filter(@Nullable Output<String> filter) {
            $.filter = filter;
            return this;
        }

        /**
         * @param filter OData filter expression for the expanded entity.
         * 
         * @return builder
         * 
         */
        public Builder filter(String filter) {
            return filter(Output.of(filter));
        }

        /**
         * @param navigationProperty The navigation property name to expand.
         * 
         * @return builder
         * 
         */
        public Builder navigationProperty(Output<String> navigationProperty) {
            $.navigationProperty = navigationProperty;
            return this;
        }

        /**
         * @param navigationProperty The navigation property name to expand.
         * 
         * @return builder
         * 
         */
        public Builder navigationProperty(String navigationProperty) {
            return navigationProperty(Output.of(navigationProperty));
        }

        /**
         * @param select Comma-separated list of columns to include for the expanded entity.
         * 
         * @return builder
         * 
         */
        public Builder select(@Nullable Output<String> select) {
            $.select = select;
            return this;
        }

        /**
         * @param select Comma-separated list of columns to include for the expanded entity.
         * 
         * @return builder
         * 
         */
        public Builder select(String select) {
            return select(Output.of(select));
        }

        public DataRecordsExpandParamArgs build() {
            if ($.navigationProperty == null) {
                throw new MissingRequiredPropertyException("DataRecordsExpandParamArgs", "navigationProperty");
            }
            return $;
        }
    }

}
