// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.inputs;




public final class GetDlpPoliciesPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDlpPoliciesPlainArgs Empty = new GetDlpPoliciesPlainArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private GetDlpPoliciesPlainArgs $;

        public Builder() {
            $ = new GetDlpPoliciesPlainArgs();
        }
        public GetDlpPoliciesPlainArgs build() {
            return $;
        }
    }

}
