// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.rpothin.powerplatform.inputs.DataRecordsExpandParamArgs;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetDataRecordsArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDataRecordsArgs Empty = new GetDataRecordsArgs();

    /**
     * The GUID of the Power Platform environment containing the Dataverse instance.
     * 
     */
    @Import(name="environmentId", required=true)
    private Output<String> environmentId;

    /**
     * @return The GUID of the Power Platform environment containing the Dataverse instance.
     * 
     */
    public Output<String> environmentId() {
        return this.environmentId;
    }

    /**
     * List of navigation properties to expand in the response.
     * 
     */
    @Import(name="expand")
    private @Nullable Output<List<DataRecordsExpandParamArgs>> expand;

    /**
     * @return List of navigation properties to expand in the response.
     * 
     */
    public Optional<Output<List<DataRecordsExpandParamArgs>>> expand() {
        return Optional.ofNullable(this.expand);
    }

    /**
     * OData $filter expression (e.g. &#34;name eq &#39;My Pipeline&#39;&#34;).
     * 
     */
    @Import(name="filter")
    private @Nullable Output<String> filter;

    /**
     * @return OData $filter expression (e.g. &#34;name eq &#39;My Pipeline&#39;&#34;).
     * 
     */
    public Optional<Output<String>> filter() {
        return Optional.ofNullable(this.filter);
    }

    /**
     * OData $orderby expression (e.g. &#34;createdon desc&#34;).
     * 
     */
    @Import(name="orderby")
    private @Nullable Output<String> orderby;

    /**
     * @return OData $orderby expression (e.g. &#34;createdon desc&#34;).
     * 
     */
    public Optional<Output<String>> orderby() {
        return Optional.ofNullable(this.orderby);
    }

    /**
     * List of column logical names to include in the response.
     * 
     */
    @Import(name="select")
    private @Nullable Output<List<String>> select;

    /**
     * @return List of column logical names to include in the response.
     * 
     */
    public Optional<Output<List<String>>> select() {
        return Optional.ofNullable(this.select);
    }

    /**
     * The logical name of the Dataverse table to query (e.g. account, deploymentpipeline).
     * 
     */
    @Import(name="tableLogicalName", required=true)
    private Output<String> tableLogicalName;

    /**
     * @return The logical name of the Dataverse table to query (e.g. account, deploymentpipeline).
     * 
     */
    public Output<String> tableLogicalName() {
        return this.tableLogicalName;
    }

    /**
     * Maximum number of records to return ($top). Use to limit large result sets.
     * 
     */
    @Import(name="top")
    private @Nullable Output<Integer> top;

    /**
     * @return Maximum number of records to return ($top). Use to limit large result sets.
     * 
     */
    public Optional<Output<Integer>> top() {
        return Optional.ofNullable(this.top);
    }

    private GetDataRecordsArgs() {}

    private GetDataRecordsArgs(GetDataRecordsArgs $) {
        this.environmentId = $.environmentId;
        this.expand = $.expand;
        this.filter = $.filter;
        this.orderby = $.orderby;
        this.select = $.select;
        this.tableLogicalName = $.tableLogicalName;
        this.top = $.top;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDataRecordsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDataRecordsArgs $;

        public Builder() {
            $ = new GetDataRecordsArgs();
        }

        public Builder(GetDataRecordsArgs defaults) {
            $ = new GetDataRecordsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param environmentId The GUID of the Power Platform environment containing the Dataverse instance.
         * 
         * @return builder
         * 
         */
        public Builder environmentId(Output<String> environmentId) {
            $.environmentId = environmentId;
            return this;
        }

        /**
         * @param environmentId The GUID of the Power Platform environment containing the Dataverse instance.
         * 
         * @return builder
         * 
         */
        public Builder environmentId(String environmentId) {
            return environmentId(Output.of(environmentId));
        }

        /**
         * @param expand List of navigation properties to expand in the response.
         * 
         * @return builder
         * 
         */
        public Builder expand(@Nullable Output<List<DataRecordsExpandParamArgs>> expand) {
            $.expand = expand;
            return this;
        }

        /**
         * @param expand List of navigation properties to expand in the response.
         * 
         * @return builder
         * 
         */
        public Builder expand(List<DataRecordsExpandParamArgs> expand) {
            return expand(Output.of(expand));
        }

        /**
         * @param expand List of navigation properties to expand in the response.
         * 
         * @return builder
         * 
         */
        public Builder expand(DataRecordsExpandParamArgs... expand) {
            return expand(List.of(expand));
        }

        /**
         * @param filter OData $filter expression (e.g. &#34;name eq &#39;My Pipeline&#39;&#34;).
         * 
         * @return builder
         * 
         */
        public Builder filter(@Nullable Output<String> filter) {
            $.filter = filter;
            return this;
        }

        /**
         * @param filter OData $filter expression (e.g. &#34;name eq &#39;My Pipeline&#39;&#34;).
         * 
         * @return builder
         * 
         */
        public Builder filter(String filter) {
            return filter(Output.of(filter));
        }

        /**
         * @param orderby OData $orderby expression (e.g. &#34;createdon desc&#34;).
         * 
         * @return builder
         * 
         */
        public Builder orderby(@Nullable Output<String> orderby) {
            $.orderby = orderby;
            return this;
        }

        /**
         * @param orderby OData $orderby expression (e.g. &#34;createdon desc&#34;).
         * 
         * @return builder
         * 
         */
        public Builder orderby(String orderby) {
            return orderby(Output.of(orderby));
        }

        /**
         * @param select List of column logical names to include in the response.
         * 
         * @return builder
         * 
         */
        public Builder select(@Nullable Output<List<String>> select) {
            $.select = select;
            return this;
        }

        /**
         * @param select List of column logical names to include in the response.
         * 
         * @return builder
         * 
         */
        public Builder select(List<String> select) {
            return select(Output.of(select));
        }

        /**
         * @param select List of column logical names to include in the response.
         * 
         * @return builder
         * 
         */
        public Builder select(String... select) {
            return select(List.of(select));
        }

        /**
         * @param tableLogicalName The logical name of the Dataverse table to query (e.g. account, deploymentpipeline).
         * 
         * @return builder
         * 
         */
        public Builder tableLogicalName(Output<String> tableLogicalName) {
            $.tableLogicalName = tableLogicalName;
            return this;
        }

        /**
         * @param tableLogicalName The logical name of the Dataverse table to query (e.g. account, deploymentpipeline).
         * 
         * @return builder
         * 
         */
        public Builder tableLogicalName(String tableLogicalName) {
            return tableLogicalName(Output.of(tableLogicalName));
        }

        /**
         * @param top Maximum number of records to return ($top). Use to limit large result sets.
         * 
         * @return builder
         * 
         */
        public Builder top(@Nullable Output<Integer> top) {
            $.top = top;
            return this;
        }

        /**
         * @param top Maximum number of records to return ($top). Use to limit large result sets.
         * 
         * @return builder
         * 
         */
        public Builder top(Integer top) {
            return top(Output.of(top));
        }

        public GetDataRecordsArgs build() {
            if ($.environmentId == null) {
                throw new MissingRequiredPropertyException("GetDataRecordsArgs", "environmentId");
            }
            if ($.tableLogicalName == null) {
                throw new MissingRequiredPropertyException("GetDataRecordsArgs", "tableLogicalName");
            }
            return $;
        }
    }

}
