// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetDlpPolicyMigrationConfigArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDlpPolicyMigrationConfigArgs Empty = new GetDlpPolicyMigrationConfigArgs();

    /**
     * The ID of the source DLP policy to read migration configuration from.
     * 
     */
    @Import(name="sourcePolicyId", required=true)
    private Output<String> sourcePolicyId;

    /**
     * @return The ID of the source DLP policy to read migration configuration from.
     * 
     */
    public Output<String> sourcePolicyId() {
        return this.sourcePolicyId;
    }

    private GetDlpPolicyMigrationConfigArgs() {}

    private GetDlpPolicyMigrationConfigArgs(GetDlpPolicyMigrationConfigArgs $) {
        this.sourcePolicyId = $.sourcePolicyId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDlpPolicyMigrationConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDlpPolicyMigrationConfigArgs $;

        public Builder() {
            $ = new GetDlpPolicyMigrationConfigArgs();
        }

        public Builder(GetDlpPolicyMigrationConfigArgs defaults) {
            $ = new GetDlpPolicyMigrationConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param sourcePolicyId The ID of the source DLP policy to read migration configuration from.
         * 
         * @return builder
         * 
         */
        public Builder sourcePolicyId(Output<String> sourcePolicyId) {
            $.sourcePolicyId = sourcePolicyId;
            return this;
        }

        /**
         * @param sourcePolicyId The ID of the source DLP policy to read migration configuration from.
         * 
         * @return builder
         * 
         */
        public Builder sourcePolicyId(String sourcePolicyId) {
            return sourcePolicyId(Output.of(sourcePolicyId));
        }

        public GetDlpPolicyMigrationConfigArgs build() {
            if ($.sourcePolicyId == null) {
                throw new MissingRequiredPropertyException("GetDlpPolicyMigrationConfigArgs", "sourcePolicyId");
            }
            return $;
        }
    }

}
