// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * Power Apps settings.
 * 
 */
public final class TenantPowerAppsSettingsArgs extends com.pulumi.resources.ResourceArgs {

    public static final TenantPowerAppsSettingsArgs Empty = new TenantPowerAppsSettingsArgs();

    /**
     * Disable connection sharing with everyone.
     * 
     */
    @Import(name="disableConnectionSharingWithEveryone")
    private @Nullable Output<Boolean> disableConnectionSharingWithEveryone;

    /**
     * @return Disable connection sharing with everyone.
     * 
     */
    public Optional<Output<Boolean>> disableConnectionSharingWithEveryone() {
        return Optional.ofNullable(this.disableConnectionSharingWithEveryone);
    }

    /**
     * Disable create from Figma.
     * 
     */
    @Import(name="disableCreateFromFigma")
    private @Nullable Output<Boolean> disableCreateFromFigma;

    /**
     * @return Disable create from Figma.
     * 
     */
    public Optional<Output<Boolean>> disableCreateFromFigma() {
        return Optional.ofNullable(this.disableCreateFromFigma);
    }

    /**
     * Disable create from image.
     * 
     */
    @Import(name="disableCreateFromImage")
    private @Nullable Output<Boolean> disableCreateFromImage;

    /**
     * @return Disable create from image.
     * 
     */
    public Optional<Output<Boolean>> disableCreateFromImage() {
        return Optional.ofNullable(this.disableCreateFromImage);
    }

    /**
     * Disable maker match.
     * 
     */
    @Import(name="disableMakerMatch")
    private @Nullable Output<Boolean> disableMakerMatch;

    /**
     * @return Disable maker match.
     * 
     */
    public Optional<Output<Boolean>> disableMakerMatch() {
        return Optional.ofNullable(this.disableMakerMatch);
    }

    /**
     * Disable share with everyone.
     * 
     */
    @Import(name="disableShareWithEveryone")
    private @Nullable Output<Boolean> disableShareWithEveryone;

    /**
     * @return Disable share with everyone.
     * 
     */
    public Optional<Output<Boolean>> disableShareWithEveryone() {
        return Optional.ofNullable(this.disableShareWithEveryone);
    }

    /**
     * Disable unused license assignment.
     * 
     */
    @Import(name="disableUnusedLicenseAssignment")
    private @Nullable Output<Boolean> disableUnusedLicenseAssignment;

    /**
     * @return Disable unused license assignment.
     * 
     */
    public Optional<Output<Boolean>> disableUnusedLicenseAssignment() {
        return Optional.ofNullable(this.disableUnusedLicenseAssignment);
    }

    /**
     * Enable guests to make apps.
     * 
     */
    @Import(name="enableGuestsToMake")
    private @Nullable Output<Boolean> enableGuestsToMake;

    /**
     * @return Enable guests to make apps.
     * 
     */
    public Optional<Output<Boolean>> enableGuestsToMake() {
        return Optional.ofNullable(this.enableGuestsToMake);
    }

    private TenantPowerAppsSettingsArgs() {}

    private TenantPowerAppsSettingsArgs(TenantPowerAppsSettingsArgs $) {
        this.disableConnectionSharingWithEveryone = $.disableConnectionSharingWithEveryone;
        this.disableCreateFromFigma = $.disableCreateFromFigma;
        this.disableCreateFromImage = $.disableCreateFromImage;
        this.disableMakerMatch = $.disableMakerMatch;
        this.disableShareWithEveryone = $.disableShareWithEveryone;
        this.disableUnusedLicenseAssignment = $.disableUnusedLicenseAssignment;
        this.enableGuestsToMake = $.enableGuestsToMake;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TenantPowerAppsSettingsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TenantPowerAppsSettingsArgs $;

        public Builder() {
            $ = new TenantPowerAppsSettingsArgs();
        }

        public Builder(TenantPowerAppsSettingsArgs defaults) {
            $ = new TenantPowerAppsSettingsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param disableConnectionSharingWithEveryone Disable connection sharing with everyone.
         * 
         * @return builder
         * 
         */
        public Builder disableConnectionSharingWithEveryone(@Nullable Output<Boolean> disableConnectionSharingWithEveryone) {
            $.disableConnectionSharingWithEveryone = disableConnectionSharingWithEveryone;
            return this;
        }

        /**
         * @param disableConnectionSharingWithEveryone Disable connection sharing with everyone.
         * 
         * @return builder
         * 
         */
        public Builder disableConnectionSharingWithEveryone(Boolean disableConnectionSharingWithEveryone) {
            return disableConnectionSharingWithEveryone(Output.of(disableConnectionSharingWithEveryone));
        }

        /**
         * @param disableCreateFromFigma Disable create from Figma.
         * 
         * @return builder
         * 
         */
        public Builder disableCreateFromFigma(@Nullable Output<Boolean> disableCreateFromFigma) {
            $.disableCreateFromFigma = disableCreateFromFigma;
            return this;
        }

        /**
         * @param disableCreateFromFigma Disable create from Figma.
         * 
         * @return builder
         * 
         */
        public Builder disableCreateFromFigma(Boolean disableCreateFromFigma) {
            return disableCreateFromFigma(Output.of(disableCreateFromFigma));
        }

        /**
         * @param disableCreateFromImage Disable create from image.
         * 
         * @return builder
         * 
         */
        public Builder disableCreateFromImage(@Nullable Output<Boolean> disableCreateFromImage) {
            $.disableCreateFromImage = disableCreateFromImage;
            return this;
        }

        /**
         * @param disableCreateFromImage Disable create from image.
         * 
         * @return builder
         * 
         */
        public Builder disableCreateFromImage(Boolean disableCreateFromImage) {
            return disableCreateFromImage(Output.of(disableCreateFromImage));
        }

        /**
         * @param disableMakerMatch Disable maker match.
         * 
         * @return builder
         * 
         */
        public Builder disableMakerMatch(@Nullable Output<Boolean> disableMakerMatch) {
            $.disableMakerMatch = disableMakerMatch;
            return this;
        }

        /**
         * @param disableMakerMatch Disable maker match.
         * 
         * @return builder
         * 
         */
        public Builder disableMakerMatch(Boolean disableMakerMatch) {
            return disableMakerMatch(Output.of(disableMakerMatch));
        }

        /**
         * @param disableShareWithEveryone Disable share with everyone.
         * 
         * @return builder
         * 
         */
        public Builder disableShareWithEveryone(@Nullable Output<Boolean> disableShareWithEveryone) {
            $.disableShareWithEveryone = disableShareWithEveryone;
            return this;
        }

        /**
         * @param disableShareWithEveryone Disable share with everyone.
         * 
         * @return builder
         * 
         */
        public Builder disableShareWithEveryone(Boolean disableShareWithEveryone) {
            return disableShareWithEveryone(Output.of(disableShareWithEveryone));
        }

        /**
         * @param disableUnusedLicenseAssignment Disable unused license assignment.
         * 
         * @return builder
         * 
         */
        public Builder disableUnusedLicenseAssignment(@Nullable Output<Boolean> disableUnusedLicenseAssignment) {
            $.disableUnusedLicenseAssignment = disableUnusedLicenseAssignment;
            return this;
        }

        /**
         * @param disableUnusedLicenseAssignment Disable unused license assignment.
         * 
         * @return builder
         * 
         */
        public Builder disableUnusedLicenseAssignment(Boolean disableUnusedLicenseAssignment) {
            return disableUnusedLicenseAssignment(Output.of(disableUnusedLicenseAssignment));
        }

        /**
         * @param enableGuestsToMake Enable guests to make apps.
         * 
         * @return builder
         * 
         */
        public Builder enableGuestsToMake(@Nullable Output<Boolean> enableGuestsToMake) {
            $.enableGuestsToMake = enableGuestsToMake;
            return this;
        }

        /**
         * @param enableGuestsToMake Enable guests to make apps.
         * 
         * @return builder
         * 
         */
        public Builder enableGuestsToMake(Boolean enableGuestsToMake) {
            return enableGuestsToMake(Output.of(enableGuestsToMake));
        }

        public TenantPowerAppsSettingsArgs build() {
            return $;
        }
    }

}
