// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform
{
    /// <summary>
    /// Manages settings on a Power Platform environment. Settings are applied via PATCH to the BAP admin API. Deletion removes the resource from Pulumi state only (settings cannot be unset).
    /// </summary>
    [PowerplatformResourceType("powerplatform:index:EnvironmentSettings")]
    public partial class EnvironmentSettings : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The ID of the environment.
        /// </summary>
        [Output("environmentId")]
        public Output<string> EnvironmentId { get; private set; } = null!;

        /// <summary>
        /// Whether activity logging is enabled.
        /// </summary>
        [Output("isActivityLoggingEnabled")]
        public Output<string?> IsActivityLoggingEnabled { get; private set; } = null!;

        /// <summary>
        /// Whether auditing is enabled.
        /// </summary>
        [Output("isAuditEnabled")]
        public Output<string?> IsAuditEnabled { get; private set; } = null!;

        /// <summary>
        /// Whether user access auditing is enabled.
        /// </summary>
        [Output("isUserAccessAuditEnabled")]
        public Output<string?> IsUserAccessAuditEnabled { get; private set; } = null!;

        /// <summary>
        /// Maximum file upload size in bytes.
        /// </summary>
        [Output("maxUploadFileSize")]
        public Output<string?> MaxUploadFileSize { get; private set; } = null!;

        /// <summary>
        /// Plugin trace log setting.
        /// </summary>
        [Output("pluginTraceLogSetting")]
        public Output<string?> PluginTraceLogSetting { get; private set; } = null!;


        /// <summary>
        /// Create a EnvironmentSettings resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EnvironmentSettings(string name, EnvironmentSettingsArgs args, CustomResourceOptions? options = null)
            : base("powerplatform:index:EnvironmentSettings", name, args ?? new EnvironmentSettingsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private EnvironmentSettings(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("powerplatform:index:EnvironmentSettings", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing EnvironmentSettings resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static EnvironmentSettings Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new EnvironmentSettings(name, id, options);
        }
    }

    public sealed class EnvironmentSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the environment to manage settings for. Immutable after creation.
        /// </summary>
        [Input("environmentId", required: true)]
        public Input<string> EnvironmentId { get; set; } = null!;

        /// <summary>
        /// Whether activity logging is enabled (true or false).
        /// </summary>
        [Input("isActivityLoggingEnabled")]
        public Input<string>? IsActivityLoggingEnabled { get; set; }

        /// <summary>
        /// Whether auditing is enabled (true or false).
        /// </summary>
        [Input("isAuditEnabled")]
        public Input<string>? IsAuditEnabled { get; set; }

        /// <summary>
        /// Whether user access auditing is enabled (true or false).
        /// </summary>
        [Input("isUserAccessAuditEnabled")]
        public Input<string>? IsUserAccessAuditEnabled { get; set; }

        /// <summary>
        /// Maximum file upload size in bytes.
        /// </summary>
        [Input("maxUploadFileSize")]
        public Input<string>? MaxUploadFileSize { get; set; }

        /// <summary>
        /// Plugin trace log setting (Off, Exception, All).
        /// </summary>
        [Input("pluginTraceLogSetting")]
        public Input<string>? PluginTraceLogSetting { get; set; }

        public EnvironmentSettingsArgs()
        {
        }
        public static new EnvironmentSettingsArgs Empty => new EnvironmentSettingsArgs();
    }
}
