// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform
{
    /// <summary>
    /// Adds a service principal as System Administrator in a Dataverse-enabled Power Platform environment. Creates a systemuser record via the Dataverse Web API. Both environmentId and applicationId are immutable — any change triggers resource replacement.
    /// </summary>
    [PowerplatformResourceType("powerplatform:index:EnvironmentApplicationAdmin")]
    public partial class EnvironmentApplicationAdmin : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The GUID of the registered service principal.
        /// </summary>
        [Output("applicationId")]
        public Output<string> ApplicationId { get; private set; } = null!;

        /// <summary>
        /// The GUID of the Power Platform environment.
        /// </summary>
        [Output("environmentId")]
        public Output<string> EnvironmentId { get; private set; } = null!;

        /// <summary>
        /// The Dataverse systemuser record GUID for the registered application user.
        /// </summary>
        [Output("systemUserId")]
        public Output<string> SystemUserId { get; private set; } = null!;


        /// <summary>
        /// Create a EnvironmentApplicationAdmin resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EnvironmentApplicationAdmin(string name, EnvironmentApplicationAdminArgs args, CustomResourceOptions? options = null)
            : base("powerplatform:index:EnvironmentApplicationAdmin", name, args ?? new EnvironmentApplicationAdminArgs(), MakeResourceOptions(options, ""))
        {
        }

        private EnvironmentApplicationAdmin(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("powerplatform:index:EnvironmentApplicationAdmin", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/rpothin",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing EnvironmentApplicationAdmin resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static EnvironmentApplicationAdmin Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new EnvironmentApplicationAdmin(name, id, options);
        }
    }

    public sealed class EnvironmentApplicationAdminArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The GUID of the service principal (application) to add as System Administrator. Immutable after creation.
        /// </summary>
        [Input("applicationId", required: true)]
        public Input<string> ApplicationId { get; set; } = null!;

        /// <summary>
        /// The GUID of the Power Platform environment. Must have a Dataverse instance. Immutable after creation.
        /// </summary>
        [Input("environmentId", required: true)]
        public Input<string> EnvironmentId { get; set; } = null!;

        public EnvironmentApplicationAdminArgs()
        {
        }
        public static new EnvironmentApplicationAdminArgs Empty => new EnvironmentApplicationAdminArgs();
    }
}
