// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform
{
    /// <summary>
    /// Manages a Power Platform environment group. Environment groups allow you to organize environments and apply policies at a group level.
    /// </summary>
    [PowerplatformResourceType("powerplatform:index:EnvironmentGroup")]
    public partial class EnvironmentGroup : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The timestamp when the group was created.
        /// </summary>
        [Output("createdTime")]
        public Output<string?> CreatedTime { get; private set; } = null!;

        /// <summary>
        /// The description of the environment group.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The display name of the environment group.
        /// </summary>
        [Output("displayName")]
        public Output<string> DisplayName { get; private set; } = null!;

        /// <summary>
        /// The timestamp when the group was last modified.
        /// </summary>
        [Output("lastModifiedTime")]
        public Output<string?> LastModifiedTime { get; private set; } = null!;

        /// <summary>
        /// The ID of the parent environment group.
        /// </summary>
        [Output("parentGroupId")]
        public Output<string?> ParentGroupId { get; private set; } = null!;


        /// <summary>
        /// Create a EnvironmentGroup resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EnvironmentGroup(string name, EnvironmentGroupArgs args, CustomResourceOptions? options = null)
            : base("powerplatform:index:EnvironmentGroup", name, args ?? new EnvironmentGroupArgs(), MakeResourceOptions(options, ""))
        {
        }

        private EnvironmentGroup(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("powerplatform:index:EnvironmentGroup", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/rpothin",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing EnvironmentGroup resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static EnvironmentGroup Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new EnvironmentGroup(name, id, options);
        }
    }

    public sealed class EnvironmentGroupArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A description of the environment group.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The display name for the environment group.
        /// </summary>
        [Input("displayName", required: true)]
        public Input<string> DisplayName { get; set; } = null!;

        /// <summary>
        /// The ID of the parent environment group, if this is a nested group.
        /// </summary>
        [Input("parentGroupId")]
        public Input<string>? ParentGroupId { get; set; }

        public EnvironmentGroupArgs()
        {
        }
        public static new EnvironmentGroupArgs Empty => new EnvironmentGroupArgs();
    }
}
