// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform
{
    /// <summary>
    /// Creates a manual backup of a Power Platform environment. Backups are immutable — any change to inputs triggers replacement.
    /// </summary>
    [PowerplatformResourceType("powerplatform:index:EnvironmentBackup")]
    public partial class EnvironmentBackup : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The date and time when the backup expires.
        /// </summary>
        [Output("backupExpiryDateTime")]
        public Output<string?> BackupExpiryDateTime { get; private set; } = null!;

        /// <summary>
        /// The date and time when the backup was created.
        /// </summary>
        [Output("backupPointDateTime")]
        public Output<string?> BackupPointDateTime { get; private set; } = null!;

        /// <summary>
        /// The ID of the backed-up environment.
        /// </summary>
        [Output("environmentId")]
        public Output<string> EnvironmentId { get; private set; } = null!;

        /// <summary>
        /// The label for the backup.
        /// </summary>
        [Output("label")]
        public Output<string> Label { get; private set; } = null!;


        /// <summary>
        /// Create a EnvironmentBackup resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EnvironmentBackup(string name, EnvironmentBackupArgs args, CustomResourceOptions? options = null)
            : base("powerplatform:index:EnvironmentBackup", name, args ?? new EnvironmentBackupArgs(), MakeResourceOptions(options, ""))
        {
        }

        private EnvironmentBackup(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("powerplatform:index:EnvironmentBackup", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/rpothin",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing EnvironmentBackup resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static EnvironmentBackup Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new EnvironmentBackup(name, id, options);
        }
    }

    public sealed class EnvironmentBackupArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the environment to back up.
        /// </summary>
        [Input("environmentId", required: true)]
        public Input<string> EnvironmentId { get; set; } = null!;

        /// <summary>
        /// A descriptive label for the backup.
        /// </summary>
        [Input("label", required: true)]
        public Input<string> Label { get; set; } = null!;

        public EnvironmentBackupArgs()
        {
        }
        public static new EnvironmentBackupArgs Empty => new EnvironmentBackupArgs();
    }
}
