// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform
{
    public static class GetDataRecords
    {
        /// <summary>
        /// Queries Dataverse records from a table using OData filter, select, orderby, top, and expand parameters. Returns the first page of matching records. Use the 'top' parameter to control result count for large tables.
        /// </summary>
        public static Task<GetDataRecordsResult> InvokeAsync(GetDataRecordsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDataRecordsResult>("powerplatform:index:getDataRecords", args ?? new GetDataRecordsArgs(), options.WithDefaults());

        /// <summary>
        /// Queries Dataverse records from a table using OData filter, select, orderby, top, and expand parameters. Returns the first page of matching records. Use the 'top' parameter to control result count for large tables.
        /// </summary>
        public static Output<GetDataRecordsResult> Invoke(GetDataRecordsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDataRecordsResult>("powerplatform:index:getDataRecords", args ?? new GetDataRecordsInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Queries Dataverse records from a table using OData filter, select, orderby, top, and expand parameters. Returns the first page of matching records. Use the 'top' parameter to control result count for large tables.
        /// </summary>
        public static Output<GetDataRecordsResult> Invoke(GetDataRecordsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDataRecordsResult>("powerplatform:index:getDataRecords", args ?? new GetDataRecordsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDataRecordsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The GUID of the Power Platform environment containing the Dataverse instance.
        /// </summary>
        [Input("environmentId", required: true)]
        public string EnvironmentId { get; set; } = null!;

        [Input("expand")]
        private List<Inputs.DataRecordsExpandParam>? _expand;

        /// <summary>
        /// List of navigation properties to expand in the response.
        /// </summary>
        public List<Inputs.DataRecordsExpandParam> Expand
        {
            get => _expand ?? (_expand = new List<Inputs.DataRecordsExpandParam>());
            set => _expand = value;
        }

        /// <summary>
        /// OData $filter expression (e.g. "name eq 'My Pipeline'").
        /// </summary>
        [Input("filter")]
        public string? Filter { get; set; }

        /// <summary>
        /// OData $orderby expression (e.g. "createdon desc").
        /// </summary>
        [Input("orderby")]
        public string? Orderby { get; set; }

        [Input("select")]
        private List<string>? _select;

        /// <summary>
        /// List of column logical names to include in the response.
        /// </summary>
        public List<string> Select
        {
            get => _select ?? (_select = new List<string>());
            set => _select = value;
        }

        /// <summary>
        /// The logical name of the Dataverse table to query (e.g. account, deploymentpipeline).
        /// </summary>
        [Input("tableLogicalName", required: true)]
        public string TableLogicalName { get; set; } = null!;

        /// <summary>
        /// Maximum number of records to return ($top). Use to limit large result sets.
        /// </summary>
        [Input("top")]
        public int? Top { get; set; }

        public GetDataRecordsArgs()
        {
        }
        public static new GetDataRecordsArgs Empty => new GetDataRecordsArgs();
    }

    public sealed class GetDataRecordsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The GUID of the Power Platform environment containing the Dataverse instance.
        /// </summary>
        [Input("environmentId", required: true)]
        public Input<string> EnvironmentId { get; set; } = null!;

        [Input("expand")]
        private InputList<Inputs.DataRecordsExpandParamArgs>? _expand;

        /// <summary>
        /// List of navigation properties to expand in the response.
        /// </summary>
        public InputList<Inputs.DataRecordsExpandParamArgs> Expand
        {
            get => _expand ?? (_expand = new InputList<Inputs.DataRecordsExpandParamArgs>());
            set => _expand = value;
        }

        /// <summary>
        /// OData $filter expression (e.g. "name eq 'My Pipeline'").
        /// </summary>
        [Input("filter")]
        public Input<string>? Filter { get; set; }

        /// <summary>
        /// OData $orderby expression (e.g. "createdon desc").
        /// </summary>
        [Input("orderby")]
        public Input<string>? Orderby { get; set; }

        [Input("select")]
        private InputList<string>? _select;

        /// <summary>
        /// List of column logical names to include in the response.
        /// </summary>
        public InputList<string> Select
        {
            get => _select ?? (_select = new InputList<string>());
            set => _select = value;
        }

        /// <summary>
        /// The logical name of the Dataverse table to query (e.g. account, deploymentpipeline).
        /// </summary>
        [Input("tableLogicalName", required: true)]
        public Input<string> TableLogicalName { get; set; } = null!;

        /// <summary>
        /// Maximum number of records to return ($top). Use to limit large result sets.
        /// </summary>
        [Input("top")]
        public Input<int>? Top { get; set; }

        public GetDataRecordsInvokeArgs()
        {
        }
        public static new GetDataRecordsInvokeArgs Empty => new GetDataRecordsInvokeArgs();
    }


    [OutputType]
    public sealed class GetDataRecordsResult
    {
        /// <summary>
        /// The list of matching Dataverse records. Each record is a map of column name to value.
        /// </summary>
        public readonly ImmutableArray<object> Records;

        [OutputConstructor]
        private GetDataRecordsResult(ImmutableArray<object> records)
        {
            Records = records;
        }
    }
}
