// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform
{
    public static class GetDlpPolicies
    {
        /// <summary>
        /// Lists all rule-based DLP (Data Loss Prevention) policies in the tenant.
        /// </summary>
        public static Task<GetDlpPoliciesResult> InvokeAsync(GetDlpPoliciesArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDlpPoliciesResult>("powerplatform:index:getDlpPolicies", args ?? new GetDlpPoliciesArgs(), options.WithDefaults());

        /// <summary>
        /// Lists all rule-based DLP (Data Loss Prevention) policies in the tenant.
        /// </summary>
        public static Output<GetDlpPoliciesResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDlpPoliciesResult>("powerplatform:index:getDlpPolicies", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Lists all rule-based DLP (Data Loss Prevention) policies in the tenant.
        /// </summary>
        public static Output<GetDlpPoliciesResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDlpPoliciesResult>("powerplatform:index:getDlpPolicies", InvokeArgs.Empty, options.WithDefaults());
    }


    public sealed class GetDlpPoliciesArgs : global::Pulumi.InvokeArgs
    {
        public GetDlpPoliciesArgs()
        {
        }
        public static new GetDlpPoliciesArgs Empty => new GetDlpPoliciesArgs();
    }


    [OutputType]
    public sealed class GetDlpPoliciesResult
    {
        /// <summary>
        /// The list of DLP policies.
        /// </summary>
        public readonly ImmutableArray<Outputs.DlpPolicySummary> Policies;

        [OutputConstructor]
        private GetDlpPoliciesResult(ImmutableArray<Outputs.DlpPolicySummary> policies)
        {
            Policies = policies;
        }
    }
}
