# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['EnvironmentSettingsArgs', 'EnvironmentSettings']

@pulumi.input_type
class EnvironmentSettingsArgs:
    def __init__(__self__, *,
                 environment_id: pulumi.Input[_builtins.str],
                 allow_application_user_access: pulumi.Input[Optional[_builtins.bool]] = None,
                 allow_microsoft_trusted_service_tags: pulumi.Input[Optional[_builtins.bool]] = None,
                 audit_retention_period_in_days: pulumi.Input[Optional[_builtins.int]] = None,
                 is_activity_logging_enabled: pulumi.Input[Optional[_builtins.str]] = None,
                 is_audit_enabled: pulumi.Input[Optional[_builtins.str]] = None,
                 is_read_audit_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 is_user_access_audit_enabled: pulumi.Input[Optional[_builtins.str]] = None,
                 max_upload_file_size: pulumi.Input[Optional[_builtins.str]] = None,
                 plugin_trace_log_setting: pulumi.Input[Optional[_builtins.str]] = None,
                 power_apps_component_framework_for_canvas_apps: pulumi.Input[Optional[_builtins.bool]] = None,
                 reverse_proxy_ip_addresses: pulumi.Input[Optional[_builtins.str]] = None,
                 show_dashboard_cards_in_expanded_state: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a EnvironmentSettings resource.

        :param pulumi.Input[_builtins.str] environment_id: The ID of the environment to manage settings for. Immutable after creation.
        :param pulumi.Input[_builtins.bool] allow_application_user_access: Whether service principal (application user) access is allowed.
        :param pulumi.Input[_builtins.bool] allow_microsoft_trusted_service_tags: Whether Microsoft trusted Azure service tags are allowed for connectivity.
        :param pulumi.Input[_builtins.int] audit_retention_period_in_days: Audit log retention period in days. Use -1 for forever, or a value between 31 and 24855.
        :param pulumi.Input[_builtins.str] is_activity_logging_enabled: Whether activity logging is enabled (true or false).
        :param pulumi.Input[_builtins.str] is_audit_enabled: Whether auditing is enabled (true or false).
        :param pulumi.Input[_builtins.bool] is_read_audit_enabled: Whether read auditing is enabled (GDPR). Managed via Dataverse organizations table.
        :param pulumi.Input[_builtins.str] is_user_access_audit_enabled: Whether user access auditing is enabled (true or false).
        :param pulumi.Input[_builtins.str] max_upload_file_size: Maximum file upload size in bytes.
        :param pulumi.Input[_builtins.str] plugin_trace_log_setting: Plugin trace log setting (Off, Exception, All).
        :param pulumi.Input[_builtins.bool] power_apps_component_framework_for_canvas_apps: Whether Power Apps Component Framework (PCF) controls are enabled for canvas apps.
        :param pulumi.Input[_builtins.str] reverse_proxy_ip_addresses: Comma-separated list of allowed reverse proxy IP addresses or CIDR ranges.
        :param pulumi.Input[_builtins.bool] show_dashboard_cards_in_expanded_state: Whether dashboard cards are shown in expanded state by default.
        """
        pulumi.set(__self__, "environment_id", environment_id)
        if allow_application_user_access is not None:
            pulumi.set(__self__, "allow_application_user_access", allow_application_user_access)
        if allow_microsoft_trusted_service_tags is not None:
            pulumi.set(__self__, "allow_microsoft_trusted_service_tags", allow_microsoft_trusted_service_tags)
        if audit_retention_period_in_days is not None:
            pulumi.set(__self__, "audit_retention_period_in_days", audit_retention_period_in_days)
        if is_activity_logging_enabled is not None:
            pulumi.set(__self__, "is_activity_logging_enabled", is_activity_logging_enabled)
        if is_audit_enabled is not None:
            pulumi.set(__self__, "is_audit_enabled", is_audit_enabled)
        if is_read_audit_enabled is not None:
            pulumi.set(__self__, "is_read_audit_enabled", is_read_audit_enabled)
        if is_user_access_audit_enabled is not None:
            pulumi.set(__self__, "is_user_access_audit_enabled", is_user_access_audit_enabled)
        if max_upload_file_size is not None:
            pulumi.set(__self__, "max_upload_file_size", max_upload_file_size)
        if plugin_trace_log_setting is not None:
            pulumi.set(__self__, "plugin_trace_log_setting", plugin_trace_log_setting)
        if power_apps_component_framework_for_canvas_apps is not None:
            pulumi.set(__self__, "power_apps_component_framework_for_canvas_apps", power_apps_component_framework_for_canvas_apps)
        if reverse_proxy_ip_addresses is not None:
            pulumi.set(__self__, "reverse_proxy_ip_addresses", reverse_proxy_ip_addresses)
        if show_dashboard_cards_in_expanded_state is not None:
            pulumi.set(__self__, "show_dashboard_cards_in_expanded_state", show_dashboard_cards_in_expanded_state)

    @_builtins.property
    @pulumi.getter(name="environmentId")
    def environment_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the environment to manage settings for. Immutable after creation.
        """
        return pulumi.get(self, "environment_id")

    @environment_id.setter
    def environment_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "environment_id", value)

    @_builtins.property
    @pulumi.getter(name="allowApplicationUserAccess")
    def allow_application_user_access(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether service principal (application user) access is allowed.
        """
        return pulumi.get(self, "allow_application_user_access")

    @allow_application_user_access.setter
    def allow_application_user_access(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "allow_application_user_access", value)

    @_builtins.property
    @pulumi.getter(name="allowMicrosoftTrustedServiceTags")
    def allow_microsoft_trusted_service_tags(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether Microsoft trusted Azure service tags are allowed for connectivity.
        """
        return pulumi.get(self, "allow_microsoft_trusted_service_tags")

    @allow_microsoft_trusted_service_tags.setter
    def allow_microsoft_trusted_service_tags(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "allow_microsoft_trusted_service_tags", value)

    @_builtins.property
    @pulumi.getter(name="auditRetentionPeriodInDays")
    def audit_retention_period_in_days(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Audit log retention period in days. Use -1 for forever, or a value between 31 and 24855.
        """
        return pulumi.get(self, "audit_retention_period_in_days")

    @audit_retention_period_in_days.setter
    def audit_retention_period_in_days(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "audit_retention_period_in_days", value)

    @_builtins.property
    @pulumi.getter(name="isActivityLoggingEnabled")
    def is_activity_logging_enabled(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Whether activity logging is enabled (true or false).
        """
        return pulumi.get(self, "is_activity_logging_enabled")

    @is_activity_logging_enabled.setter
    def is_activity_logging_enabled(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "is_activity_logging_enabled", value)

    @_builtins.property
    @pulumi.getter(name="isAuditEnabled")
    def is_audit_enabled(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Whether auditing is enabled (true or false).
        """
        return pulumi.get(self, "is_audit_enabled")

    @is_audit_enabled.setter
    def is_audit_enabled(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "is_audit_enabled", value)

    @_builtins.property
    @pulumi.getter(name="isReadAuditEnabled")
    def is_read_audit_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether read auditing is enabled (GDPR). Managed via Dataverse organizations table.
        """
        return pulumi.get(self, "is_read_audit_enabled")

    @is_read_audit_enabled.setter
    def is_read_audit_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "is_read_audit_enabled", value)

    @_builtins.property
    @pulumi.getter(name="isUserAccessAuditEnabled")
    def is_user_access_audit_enabled(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Whether user access auditing is enabled (true or false).
        """
        return pulumi.get(self, "is_user_access_audit_enabled")

    @is_user_access_audit_enabled.setter
    def is_user_access_audit_enabled(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "is_user_access_audit_enabled", value)

    @_builtins.property
    @pulumi.getter(name="maxUploadFileSize")
    def max_upload_file_size(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Maximum file upload size in bytes.
        """
        return pulumi.get(self, "max_upload_file_size")

    @max_upload_file_size.setter
    def max_upload_file_size(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "max_upload_file_size", value)

    @_builtins.property
    @pulumi.getter(name="pluginTraceLogSetting")
    def plugin_trace_log_setting(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Plugin trace log setting (Off, Exception, All).
        """
        return pulumi.get(self, "plugin_trace_log_setting")

    @plugin_trace_log_setting.setter
    def plugin_trace_log_setting(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "plugin_trace_log_setting", value)

    @_builtins.property
    @pulumi.getter(name="powerAppsComponentFrameworkForCanvasApps")
    def power_apps_component_framework_for_canvas_apps(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether Power Apps Component Framework (PCF) controls are enabled for canvas apps.
        """
        return pulumi.get(self, "power_apps_component_framework_for_canvas_apps")

    @power_apps_component_framework_for_canvas_apps.setter
    def power_apps_component_framework_for_canvas_apps(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "power_apps_component_framework_for_canvas_apps", value)

    @_builtins.property
    @pulumi.getter(name="reverseProxyIpAddresses")
    def reverse_proxy_ip_addresses(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Comma-separated list of allowed reverse proxy IP addresses or CIDR ranges.
        """
        return pulumi.get(self, "reverse_proxy_ip_addresses")

    @reverse_proxy_ip_addresses.setter
    def reverse_proxy_ip_addresses(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "reverse_proxy_ip_addresses", value)

    @_builtins.property
    @pulumi.getter(name="showDashboardCardsInExpandedState")
    def show_dashboard_cards_in_expanded_state(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether dashboard cards are shown in expanded state by default.
        """
        return pulumi.get(self, "show_dashboard_cards_in_expanded_state")

    @show_dashboard_cards_in_expanded_state.setter
    def show_dashboard_cards_in_expanded_state(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "show_dashboard_cards_in_expanded_state", value)


@pulumi.type_token("powerplatform:index:EnvironmentSettings")
class EnvironmentSettings(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_application_user_access: pulumi.Input[Optional[_builtins.bool]] = None,
                 allow_microsoft_trusted_service_tags: pulumi.Input[Optional[_builtins.bool]] = None,
                 audit_retention_period_in_days: pulumi.Input[Optional[_builtins.int]] = None,
                 environment_id: pulumi.Input[Optional[_builtins.str]] = None,
                 is_activity_logging_enabled: pulumi.Input[Optional[_builtins.str]] = None,
                 is_audit_enabled: pulumi.Input[Optional[_builtins.str]] = None,
                 is_read_audit_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 is_user_access_audit_enabled: pulumi.Input[Optional[_builtins.str]] = None,
                 max_upload_file_size: pulumi.Input[Optional[_builtins.str]] = None,
                 plugin_trace_log_setting: pulumi.Input[Optional[_builtins.str]] = None,
                 power_apps_component_framework_for_canvas_apps: pulumi.Input[Optional[_builtins.bool]] = None,
                 reverse_proxy_ip_addresses: pulumi.Input[Optional[_builtins.str]] = None,
                 show_dashboard_cards_in_expanded_state: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        Manages settings on a Power Platform environment. Settings are applied via PATCH to the BAP admin API. Deletion removes the resource from Pulumi state only (settings cannot be unset).


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] allow_application_user_access: Whether service principal (application user) access is allowed.
        :param pulumi.Input[_builtins.bool] allow_microsoft_trusted_service_tags: Whether Microsoft trusted Azure service tags are allowed for connectivity.
        :param pulumi.Input[_builtins.int] audit_retention_period_in_days: Audit log retention period in days. Use -1 for forever, or a value between 31 and 24855.
        :param pulumi.Input[_builtins.str] environment_id: The ID of the environment to manage settings for. Immutable after creation.
        :param pulumi.Input[_builtins.str] is_activity_logging_enabled: Whether activity logging is enabled (true or false).
        :param pulumi.Input[_builtins.str] is_audit_enabled: Whether auditing is enabled (true or false).
        :param pulumi.Input[_builtins.bool] is_read_audit_enabled: Whether read auditing is enabled (GDPR). Managed via Dataverse organizations table.
        :param pulumi.Input[_builtins.str] is_user_access_audit_enabled: Whether user access auditing is enabled (true or false).
        :param pulumi.Input[_builtins.str] max_upload_file_size: Maximum file upload size in bytes.
        :param pulumi.Input[_builtins.str] plugin_trace_log_setting: Plugin trace log setting (Off, Exception, All).
        :param pulumi.Input[_builtins.bool] power_apps_component_framework_for_canvas_apps: Whether Power Apps Component Framework (PCF) controls are enabled for canvas apps.
        :param pulumi.Input[_builtins.str] reverse_proxy_ip_addresses: Comma-separated list of allowed reverse proxy IP addresses or CIDR ranges.
        :param pulumi.Input[_builtins.bool] show_dashboard_cards_in_expanded_state: Whether dashboard cards are shown in expanded state by default.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: EnvironmentSettingsArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages settings on a Power Platform environment. Settings are applied via PATCH to the BAP admin API. Deletion removes the resource from Pulumi state only (settings cannot be unset).


        :param str resource_name: The name of the resource.
        :param EnvironmentSettingsArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(EnvironmentSettingsArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_application_user_access: pulumi.Input[Optional[_builtins.bool]] = None,
                 allow_microsoft_trusted_service_tags: pulumi.Input[Optional[_builtins.bool]] = None,
                 audit_retention_period_in_days: pulumi.Input[Optional[_builtins.int]] = None,
                 environment_id: pulumi.Input[Optional[_builtins.str]] = None,
                 is_activity_logging_enabled: pulumi.Input[Optional[_builtins.str]] = None,
                 is_audit_enabled: pulumi.Input[Optional[_builtins.str]] = None,
                 is_read_audit_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 is_user_access_audit_enabled: pulumi.Input[Optional[_builtins.str]] = None,
                 max_upload_file_size: pulumi.Input[Optional[_builtins.str]] = None,
                 plugin_trace_log_setting: pulumi.Input[Optional[_builtins.str]] = None,
                 power_apps_component_framework_for_canvas_apps: pulumi.Input[Optional[_builtins.bool]] = None,
                 reverse_proxy_ip_addresses: pulumi.Input[Optional[_builtins.str]] = None,
                 show_dashboard_cards_in_expanded_state: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = EnvironmentSettingsArgs.__new__(EnvironmentSettingsArgs)

            __props__.__dict__["allow_application_user_access"] = allow_application_user_access
            __props__.__dict__["allow_microsoft_trusted_service_tags"] = allow_microsoft_trusted_service_tags
            __props__.__dict__["audit_retention_period_in_days"] = audit_retention_period_in_days
            if environment_id is None and not opts.urn:
                raise TypeError("Missing required property 'environment_id'")
            __props__.__dict__["environment_id"] = environment_id
            __props__.__dict__["is_activity_logging_enabled"] = is_activity_logging_enabled
            __props__.__dict__["is_audit_enabled"] = is_audit_enabled
            __props__.__dict__["is_read_audit_enabled"] = is_read_audit_enabled
            __props__.__dict__["is_user_access_audit_enabled"] = is_user_access_audit_enabled
            __props__.__dict__["max_upload_file_size"] = max_upload_file_size
            __props__.__dict__["plugin_trace_log_setting"] = plugin_trace_log_setting
            __props__.__dict__["power_apps_component_framework_for_canvas_apps"] = power_apps_component_framework_for_canvas_apps
            __props__.__dict__["reverse_proxy_ip_addresses"] = reverse_proxy_ip_addresses
            __props__.__dict__["show_dashboard_cards_in_expanded_state"] = show_dashboard_cards_in_expanded_state
        super(EnvironmentSettings, __self__).__init__(
            'powerplatform:index:EnvironmentSettings',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'EnvironmentSettings':
        """
        Get an existing EnvironmentSettings resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = EnvironmentSettingsArgs.__new__(EnvironmentSettingsArgs)

        __props__.__dict__["allow_application_user_access"] = None
        __props__.__dict__["allow_microsoft_trusted_service_tags"] = None
        __props__.__dict__["audit_retention_period_in_days"] = None
        __props__.__dict__["environment_id"] = None
        __props__.__dict__["is_activity_logging_enabled"] = None
        __props__.__dict__["is_audit_enabled"] = None
        __props__.__dict__["is_read_audit_enabled"] = None
        __props__.__dict__["is_user_access_audit_enabled"] = None
        __props__.__dict__["max_upload_file_size"] = None
        __props__.__dict__["plugin_trace_log_setting"] = None
        __props__.__dict__["power_apps_component_framework_for_canvas_apps"] = None
        __props__.__dict__["reverse_proxy_ip_addresses"] = None
        __props__.__dict__["show_dashboard_cards_in_expanded_state"] = None
        return EnvironmentSettings(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="allowApplicationUserAccess")
    def allow_application_user_access(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether service principal (application user) access is allowed.
        """
        return pulumi.get(self, "allow_application_user_access")

    @_builtins.property
    @pulumi.getter(name="allowMicrosoftTrustedServiceTags")
    def allow_microsoft_trusted_service_tags(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether Microsoft trusted Azure service tags are allowed.
        """
        return pulumi.get(self, "allow_microsoft_trusted_service_tags")

    @_builtins.property
    @pulumi.getter(name="auditRetentionPeriodInDays")
    def audit_retention_period_in_days(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Audit log retention period in days.
        """
        return pulumi.get(self, "audit_retention_period_in_days")

    @_builtins.property
    @pulumi.getter(name="environmentId")
    def environment_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the environment.
        """
        return pulumi.get(self, "environment_id")

    @_builtins.property
    @pulumi.getter(name="isActivityLoggingEnabled")
    def is_activity_logging_enabled(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Whether activity logging is enabled.
        """
        return pulumi.get(self, "is_activity_logging_enabled")

    @_builtins.property
    @pulumi.getter(name="isAuditEnabled")
    def is_audit_enabled(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Whether auditing is enabled.
        """
        return pulumi.get(self, "is_audit_enabled")

    @_builtins.property
    @pulumi.getter(name="isReadAuditEnabled")
    def is_read_audit_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether read auditing is enabled.
        """
        return pulumi.get(self, "is_read_audit_enabled")

    @_builtins.property
    @pulumi.getter(name="isUserAccessAuditEnabled")
    def is_user_access_audit_enabled(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Whether user access auditing is enabled.
        """
        return pulumi.get(self, "is_user_access_audit_enabled")

    @_builtins.property
    @pulumi.getter(name="maxUploadFileSize")
    def max_upload_file_size(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Maximum file upload size in bytes.
        """
        return pulumi.get(self, "max_upload_file_size")

    @_builtins.property
    @pulumi.getter(name="pluginTraceLogSetting")
    def plugin_trace_log_setting(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Plugin trace log setting.
        """
        return pulumi.get(self, "plugin_trace_log_setting")

    @_builtins.property
    @pulumi.getter(name="powerAppsComponentFrameworkForCanvasApps")
    def power_apps_component_framework_for_canvas_apps(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether PCF controls are enabled for canvas apps.
        """
        return pulumi.get(self, "power_apps_component_framework_for_canvas_apps")

    @_builtins.property
    @pulumi.getter(name="reverseProxyIpAddresses")
    def reverse_proxy_ip_addresses(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Allowed reverse proxy IP addresses or CIDR ranges.
        """
        return pulumi.get(self, "reverse_proxy_ip_addresses")

    @_builtins.property
    @pulumi.getter(name="showDashboardCardsInExpandedState")
    def show_dashboard_cards_in_expanded_state(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether dashboard cards are shown in expanded state by default.
        """
        return pulumi.get(self, "show_dashboard_cards_in_expanded_state")

