# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetSecurityRolesResult',
    'AwaitableGetSecurityRolesResult',
    'get_security_roles',
    'get_security_roles_output',
]

@pulumi.output_type
class GetSecurityRolesResult:
    def __init__(__self__, security_roles=None):
        if security_roles and not isinstance(security_roles, list):
            raise TypeError("Expected argument 'security_roles' to be a list")
        pulumi.set(__self__, "security_roles", security_roles)

    @_builtins.property
    @pulumi.getter(name="securityRoles")
    def security_roles(self) -> Sequence['outputs.SecurityRole']:
        """
        List of security roles.
        """
        return pulumi.get(self, "security_roles")


class AwaitableGetSecurityRolesResult(GetSecurityRolesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetSecurityRolesResult(
            security_roles=self.security_roles)


def get_security_roles(business_unit_id: Optional[_builtins.str] = None,
                       environment_id: Optional[_builtins.str] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetSecurityRolesResult:
    """
    Fetches Dataverse security roles from a Power Platform environment.


    :param _builtins.str business_unit_id: Optional business unit GUID to filter roles.
    :param _builtins.str environment_id: Environment ID to query roles from.
    """
    __args__ = dict()
    __args__['businessUnitId'] = business_unit_id
    __args__['environmentId'] = environment_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('powerplatform:index:getSecurityRoles', __args__, opts=opts, typ=GetSecurityRolesResult).value

    return AwaitableGetSecurityRolesResult(
        security_roles=pulumi.get(__ret__, 'security_roles'))
def get_security_roles_output(business_unit_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                              environment_id: Optional[pulumi.Input[_builtins.str]] = None,
                              opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetSecurityRolesResult]:
    """
    Fetches Dataverse security roles from a Power Platform environment.


    :param _builtins.str business_unit_id: Optional business unit GUID to filter roles.
    :param _builtins.str environment_id: Environment ID to query roles from.
    """
    __args__ = dict()
    __args__['businessUnitId'] = business_unit_id
    __args__['environmentId'] = environment_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('powerplatform:index:getSecurityRoles', __args__, opts=opts, typ=GetSecurityRolesResult)
    return __ret__.apply(lambda __response__: GetSecurityRolesResult(
        security_roles=pulumi.get(__response__, 'security_roles')))
