# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetConnectorsResult',
    'AwaitableGetConnectorsResult',
    'get_connectors',
    'get_connectors_output',
]

@pulumi.output_type
class GetConnectorsResult:
    def __init__(__self__, connectors=None):
        if connectors and not isinstance(connectors, list):
            raise TypeError("Expected argument 'connectors' to be a list")
        pulumi.set(__self__, "connectors", connectors)

    @_builtins.property
    @pulumi.getter
    def connectors(self) -> Sequence['outputs.ConnectorSummary']:
        """
        The list of connectors.
        """
        return pulumi.get(self, "connectors")


class AwaitableGetConnectorsResult(GetConnectorsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetConnectorsResult(
            connectors=self.connectors)


def get_connectors(environment_id: Optional[_builtins.str] = None,
                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetConnectorsResult:
    """
    Lists connectors available in a Power Platform environment.


    :param _builtins.str environment_id: The ID of the environment to list connectors for.
    """
    __args__ = dict()
    __args__['environmentId'] = environment_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('powerplatform:index:getConnectors', __args__, opts=opts, typ=GetConnectorsResult).value

    return AwaitableGetConnectorsResult(
        connectors=pulumi.get(__ret__, 'connectors'))
def get_connectors_output(environment_id: pulumi.Input[Optional[_builtins.str]] = None,
                          opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetConnectorsResult]:
    """
    Lists connectors available in a Power Platform environment.


    :param _builtins.str environment_id: The ID of the environment to list connectors for.
    """
    __args__ = dict()
    __args__['environmentId'] = environment_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('powerplatform:index:getConnectors', __args__, opts=opts, typ=GetConnectorsResult)
    return __ret__.apply(lambda __response__: GetConnectorsResult(
        connectors=pulumi.get(__response__, 'connectors')))
