# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetDlpPoliciesResult',
    'AwaitableGetDlpPoliciesResult',
    'get_dlp_policies',
    'get_dlp_policies_output',
]

@pulumi.output_type
class GetDlpPoliciesResult:
    def __init__(__self__, policies=None):
        if policies and not isinstance(policies, list):
            raise TypeError("Expected argument 'policies' to be a list")
        pulumi.set(__self__, "policies", policies)

    @_builtins.property
    @pulumi.getter
    def policies(self) -> Sequence['outputs.DlpPolicySummary']:
        """
        The list of DLP policies.
        """
        return pulumi.get(self, "policies")


class AwaitableGetDlpPoliciesResult(GetDlpPoliciesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDlpPoliciesResult(
            policies=self.policies)


def get_dlp_policies(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDlpPoliciesResult:
    """
    Lists all rule-based DLP (Data Loss Prevention) policies in the tenant.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('powerplatform:index:getDlpPolicies', __args__, opts=opts, typ=GetDlpPoliciesResult).value

    return AwaitableGetDlpPoliciesResult(
        policies=pulumi.get(__ret__, 'policies'))
def get_dlp_policies_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetDlpPoliciesResult]:
    """
    Lists all rule-based DLP (Data Loss Prevention) policies in the tenant.
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('powerplatform:index:getDlpPolicies', __args__, opts=opts, typ=GetDlpPoliciesResult)
    return __ret__.apply(lambda __response__: GetDlpPoliciesResult(
        policies=pulumi.get(__response__, 'policies')))
