# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetFlowsResult',
    'AwaitableGetFlowsResult',
    'get_flows',
    'get_flows_output',
]

@pulumi.output_type
class GetFlowsResult:
    def __init__(__self__, flows=None, total_rows_count=None, total_rows_count_limit_exceeded=None):
        if flows and not isinstance(flows, list):
            raise TypeError("Expected argument 'flows' to be a list")
        pulumi.set(__self__, "flows", flows)
        if total_rows_count and not isinstance(total_rows_count, int):
            raise TypeError("Expected argument 'total_rows_count' to be a int")
        pulumi.set(__self__, "total_rows_count", total_rows_count)
        if total_rows_count_limit_exceeded and not isinstance(total_rows_count_limit_exceeded, bool):
            raise TypeError("Expected argument 'total_rows_count_limit_exceeded' to be a bool")
        pulumi.set(__self__, "total_rows_count_limit_exceeded", total_rows_count_limit_exceeded)

    @_builtins.property
    @pulumi.getter
    def flows(self) -> Sequence['outputs.FlowSummary']:
        """
        The list of Cloud Flows.
        """
        return pulumi.get(self, "flows")

    @_builtins.property
    @pulumi.getter(name="totalRowsCount")
    def total_rows_count(self) -> _builtins.int:
        """
        Total number of flows matching the query filter (from @odata.count). Zero when the count annotation is absent.
        """
        return pulumi.get(self, "total_rows_count")

    @_builtins.property
    @pulumi.getter(name="totalRowsCountLimitExceeded")
    def total_rows_count_limit_exceeded(self) -> _builtins.bool:
        """
        True when the total row count exceeded the Dataverse limit (@Microsoft.Dynamics.CRM.totalrecordcountlimitexceeded).
        """
        return pulumi.get(self, "total_rows_count_limit_exceeded")


class AwaitableGetFlowsResult(GetFlowsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetFlowsResult(
            flows=self.flows,
            total_rows_count=self.total_rows_count,
            total_rows_count_limit_exceeded=self.total_rows_count_limit_exceeded)


def get_flows(environment_id: Optional[_builtins.str] = None,
              filter: Optional[_builtins.str] = None,
              select: Optional[Sequence[_builtins.str]] = None,
              top: Optional[_builtins.int] = None,
              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetFlowsResult:
    """
    Lists Cloud Flows in a Power Platform environment by querying the Dataverse workflow table (category=5). This approach works with service principal credentials and does not require a per-user Power Automate license. Returns the first page of results; use the 'top' parameter to control page size. Note: the service principal must be an Application User with read access to the workflow entity in Dataverse, and will see all flows visible to that principal (not a user-scoped view).


    :param _builtins.str environment_id: The ID of the environment to list flows for.
    :param _builtins.str filter: Additional OData $filter clause appended to the base 'category eq 5' filter with 'and'. Example: "statecode eq 1" to return only active flows.
    :param Sequence[_builtins.str] select: Additional Dataverse workflow columns to include in the response, merged with the required columns (workflowid, name, statecode).
    :param _builtins.int top: Maximum number of flows to return ($top). Use to limit large result sets.
    """
    __args__ = dict()
    __args__['environmentId'] = environment_id
    __args__['filter'] = filter
    __args__['select'] = select
    __args__['top'] = top
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('powerplatform:index:getFlows', __args__, opts=opts, typ=GetFlowsResult).value

    return AwaitableGetFlowsResult(
        flows=pulumi.get(__ret__, 'flows'),
        total_rows_count=pulumi.get(__ret__, 'total_rows_count'),
        total_rows_count_limit_exceeded=pulumi.get(__ret__, 'total_rows_count_limit_exceeded'))
def get_flows_output(environment_id: Optional[pulumi.Input[_builtins.str]] = None,
                     filter: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                     select: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                     top: Optional[pulumi.Input[Optional[_builtins.int]]] = None,
                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetFlowsResult]:
    """
    Lists Cloud Flows in a Power Platform environment by querying the Dataverse workflow table (category=5). This approach works with service principal credentials and does not require a per-user Power Automate license. Returns the first page of results; use the 'top' parameter to control page size. Note: the service principal must be an Application User with read access to the workflow entity in Dataverse, and will see all flows visible to that principal (not a user-scoped view).


    :param _builtins.str environment_id: The ID of the environment to list flows for.
    :param _builtins.str filter: Additional OData $filter clause appended to the base 'category eq 5' filter with 'and'. Example: "statecode eq 1" to return only active flows.
    :param Sequence[_builtins.str] select: Additional Dataverse workflow columns to include in the response, merged with the required columns (workflowid, name, statecode).
    :param _builtins.int top: Maximum number of flows to return ($top). Use to limit large result sets.
    """
    __args__ = dict()
    __args__['environmentId'] = environment_id
    __args__['filter'] = filter
    __args__['select'] = select
    __args__['top'] = top
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('powerplatform:index:getFlows', __args__, opts=opts, typ=GetFlowsResult)
    return __ret__.apply(lambda __response__: GetFlowsResult(
        flows=pulumi.get(__response__, 'flows'),
        total_rows_count=pulumi.get(__response__, 'total_rows_count'),
        total_rows_count_limit_exceeded=pulumi.get(__response__, 'total_rows_count_limit_exceeded')))
