# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetDlpPolicyMigrationConfigResult',
    'AwaitableGetDlpPolicyMigrationConfigResult',
    'get_dlp_policy_migration_config',
    'get_dlp_policy_migration_config_output',
]

@pulumi.output_type
class GetDlpPolicyMigrationConfigResult:
    def __init__(__self__, display_name=None, name=None, rule_sets=None):
        if display_name and not isinstance(display_name, str):
            raise TypeError("Expected argument 'display_name' to be a str")
        pulumi.set(__self__, "display_name", display_name)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if rule_sets and not isinstance(rule_sets, list):
            raise TypeError("Expected argument 'rule_sets' to be a list")
        pulumi.set(__self__, "rule_sets", rule_sets)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> _builtins.str:
        """
        Display name of the source DLP policy. Use as the displayName input for ResDlpPolicy.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Display name of the source DLP policy. Use as the name input for powerplatform:index:DlpPolicy.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="ruleSets")
    def rule_sets(self) -> Sequence['outputs.RuleSet']:
        """
        Rule set configurations from the source policy, ready for input to ResDlpPolicy or DlpPolicy.
        """
        return pulumi.get(self, "rule_sets")


class AwaitableGetDlpPolicyMigrationConfigResult(GetDlpPolicyMigrationConfigResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDlpPolicyMigrationConfigResult(
            display_name=self.display_name,
            name=self.name,
            rule_sets=self.rule_sets)


def get_dlp_policy_migration_config(source_policy_id: Optional[_builtins.str] = None,
                                    opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDlpPolicyMigrationConfigResult:
    """
    Reads an existing DLP policy by ID and returns its configuration ready for use with ResDlpPolicy or powerplatform:index:DlpPolicy. This function is the Pulumi equivalent of the utl-dlppolicy-replicator Terraform module. It is advisory-only: no enforcement or reclassification is applied.


    :param _builtins.str source_policy_id: The ID of the source DLP policy to read migration configuration from.
    """
    __args__ = dict()
    __args__['sourcePolicyId'] = source_policy_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('powerplatform:index:getDlpPolicyMigrationConfig', __args__, opts=opts, typ=GetDlpPolicyMigrationConfigResult).value

    return AwaitableGetDlpPolicyMigrationConfigResult(
        display_name=pulumi.get(__ret__, 'display_name'),
        name=pulumi.get(__ret__, 'name'),
        rule_sets=pulumi.get(__ret__, 'rule_sets'))
def get_dlp_policy_migration_config_output(source_policy_id: Optional[pulumi.Input[_builtins.str]] = None,
                                           opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetDlpPolicyMigrationConfigResult]:
    """
    Reads an existing DLP policy by ID and returns its configuration ready for use with ResDlpPolicy or powerplatform:index:DlpPolicy. This function is the Pulumi equivalent of the utl-dlppolicy-replicator Terraform module. It is advisory-only: no enforcement or reclassification is applied.


    :param _builtins.str source_policy_id: The ID of the source DLP policy to read migration configuration from.
    """
    __args__ = dict()
    __args__['sourcePolicyId'] = source_policy_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('powerplatform:index:getDlpPolicyMigrationConfig', __args__, opts=opts, typ=GetDlpPolicyMigrationConfigResult)
    return __ret__.apply(lambda __response__: GetDlpPolicyMigrationConfigResult(
        display_name=pulumi.get(__response__, 'display_name'),
        name=pulumi.get(__response__, 'name'),
        rule_sets=pulumi.get(__response__, 'rule_sets')))
