# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._inputs import *

__all__ = [
    'GetDataRecordsResult',
    'AwaitableGetDataRecordsResult',
    'get_data_records',
    'get_data_records_output',
]

@pulumi.output_type
class GetDataRecordsResult:
    def __init__(__self__, records=None, total_rows_count=None, total_rows_count_limit_exceeded=None):
        if records and not isinstance(records, list):
            raise TypeError("Expected argument 'records' to be a list")
        pulumi.set(__self__, "records", records)
        if total_rows_count and not isinstance(total_rows_count, int):
            raise TypeError("Expected argument 'total_rows_count' to be a int")
        pulumi.set(__self__, "total_rows_count", total_rows_count)
        if total_rows_count_limit_exceeded and not isinstance(total_rows_count_limit_exceeded, bool):
            raise TypeError("Expected argument 'total_rows_count_limit_exceeded' to be a bool")
        pulumi.set(__self__, "total_rows_count_limit_exceeded", total_rows_count_limit_exceeded)

    @_builtins.property
    @pulumi.getter
    def records(self) -> Sequence[Any]:
        """
        The list of matching Dataverse records. Each record is a map of column name to value.
        """
        return pulumi.get(self, "records")

    @_builtins.property
    @pulumi.getter(name="totalRowsCount")
    def total_rows_count(self) -> _builtins.int:
        """
        Total number of records matching the query filter (from @odata.count). Always 0 when the count annotation is absent or when `apply` is used (the count is not available in aggregation mode).
        """
        return pulumi.get(self, "total_rows_count")

    @_builtins.property
    @pulumi.getter(name="totalRowsCountLimitExceeded")
    def total_rows_count_limit_exceeded(self) -> _builtins.bool:
        """
        True when the total row count exceeded the Dataverse limit (@Microsoft.Dynamics.CRM.totalrecordcountlimitexceeded).
        """
        return pulumi.get(self, "total_rows_count_limit_exceeded")


class AwaitableGetDataRecordsResult(GetDataRecordsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDataRecordsResult(
            records=self.records,
            total_rows_count=self.total_rows_count,
            total_rows_count_limit_exceeded=self.total_rows_count_limit_exceeded)


def get_data_records(apply: Optional[_builtins.str] = None,
                     entity_collection: Optional[_builtins.str] = None,
                     environment_id: Optional[_builtins.str] = None,
                     expand: Optional[Sequence[Union['DataRecordsExpandParam', 'DataRecordsExpandParamDict']]] = None,
                     filter: Optional[_builtins.str] = None,
                     orderby: Optional[_builtins.str] = None,
                     select: Optional[Sequence[_builtins.str]] = None,
                     top: Optional[_builtins.int] = None,
                     opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDataRecordsResult:
    """
    Queries Dataverse records from a collection using OData filter, select, orderby, top, apply, and expand parameters. Returns the first page of matching records. Use the 'top' parameter to control result count for large tables.


    :param _builtins.str apply: OData $apply aggregation expression (e.g. "aggregate(revenue with sum as revenue_sum)").
    :param _builtins.str entity_collection: The plural OData collection name for the Dataverse table to query (e.g. accounts, deploymentpipelines).
    :param _builtins.str environment_id: The GUID of the Power Platform environment containing the Dataverse instance.
    :param Sequence[Union['DataRecordsExpandParam', 'DataRecordsExpandParamDict']] expand: List of navigation properties to expand in the response.
    :param _builtins.str filter: OData $filter expression (e.g. "name eq 'My Pipeline'").
    :param _builtins.str orderby: OData $orderby expression (e.g. "createdon desc").
    :param Sequence[_builtins.str] select: List of column logical names to include in the response.
    :param _builtins.int top: Maximum number of records to return ($top). Use to limit large result sets.
    """
    __args__ = dict()
    __args__['apply'] = apply
    __args__['entityCollection'] = entity_collection
    __args__['environmentId'] = environment_id
    __args__['expand'] = expand
    __args__['filter'] = filter
    __args__['orderby'] = orderby
    __args__['select'] = select
    __args__['top'] = top
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('powerplatform:index:getDataRecords', __args__, opts=opts, typ=GetDataRecordsResult).value

    return AwaitableGetDataRecordsResult(
        records=pulumi.get(__ret__, 'records'),
        total_rows_count=pulumi.get(__ret__, 'total_rows_count'),
        total_rows_count_limit_exceeded=pulumi.get(__ret__, 'total_rows_count_limit_exceeded'))
def get_data_records_output(apply: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            entity_collection: Optional[pulumi.Input[_builtins.str]] = None,
                            environment_id: Optional[pulumi.Input[_builtins.str]] = None,
                            expand: Optional[pulumi.Input[Optional[Sequence[Union['DataRecordsExpandParam', 'DataRecordsExpandParamDict']]]]] = None,
                            filter: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            orderby: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                            select: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                            top: Optional[pulumi.Input[Optional[_builtins.int]]] = None,
                            opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetDataRecordsResult]:
    """
    Queries Dataverse records from a collection using OData filter, select, orderby, top, apply, and expand parameters. Returns the first page of matching records. Use the 'top' parameter to control result count for large tables.


    :param _builtins.str apply: OData $apply aggregation expression (e.g. "aggregate(revenue with sum as revenue_sum)").
    :param _builtins.str entity_collection: The plural OData collection name for the Dataverse table to query (e.g. accounts, deploymentpipelines).
    :param _builtins.str environment_id: The GUID of the Power Platform environment containing the Dataverse instance.
    :param Sequence[Union['DataRecordsExpandParam', 'DataRecordsExpandParamDict']] expand: List of navigation properties to expand in the response.
    :param _builtins.str filter: OData $filter expression (e.g. "name eq 'My Pipeline'").
    :param _builtins.str orderby: OData $orderby expression (e.g. "createdon desc").
    :param Sequence[_builtins.str] select: List of column logical names to include in the response.
    :param _builtins.int top: Maximum number of records to return ($top). Use to limit large result sets.
    """
    __args__ = dict()
    __args__['apply'] = apply
    __args__['entityCollection'] = entity_collection
    __args__['environmentId'] = environment_id
    __args__['expand'] = expand
    __args__['filter'] = filter
    __args__['orderby'] = orderby
    __args__['select'] = select
    __args__['top'] = top
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('powerplatform:index:getDataRecords', __args__, opts=opts, typ=GetDataRecordsResult)
    return __ret__.apply(lambda __response__: GetDataRecordsResult(
        records=pulumi.get(__response__, 'records'),
        total_rows_count=pulumi.get(__response__, 'total_rows_count'),
        total_rows_count_limit_exceeded=pulumi.get(__response__, 'total_rows_count_limit_exceeded')))
