# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'DataverseConfigArgs',
    'DataverseConfigArgsDict',
    'PipelineEnvironmentEntryArgs',
    'PipelineEnvironmentEntryArgsDict',
    'PipelineStageConfigArgs',
    'PipelineStageConfigArgsDict',
]

class DataverseConfigArgsDict(TypedDict):
    """
    Dataverse provisioning configuration.

        Mirrors the ``var.dataverse`` object in the AVM ``res-environment`` module.
        Passing a :class:`DataverseConfig` instance triggers Dataverse provisioning
        on the underlying ``Environment`` resource.

        Field names follow the AVM variable names (snake_case).  The component maps
        them to the camelCase wire names expected by the Pulumi provider.
        
    """
    administration_mode_enabled: NotRequired[_builtins.bool]
    background_operation_enabled: NotRequired[_builtins.bool]
    currency_code: NotRequired[_builtins.str]
    domain: NotRequired[_builtins.str]
    language_code: NotRequired[_builtins.int]
    security_group_id: NotRequired[_builtins.str]
    template_metadata: NotRequired[_builtins.str]
    templates: NotRequired[Sequence[_builtins.str]]

@pulumi.input_type
class DataverseConfigArgs:
    def __init__(__self__, *,
                 administration_mode_enabled: Optional[_builtins.bool] = None,
                 background_operation_enabled: Optional[_builtins.bool] = None,
                 currency_code: Optional[_builtins.str] = None,
                 domain: Optional[_builtins.str] = None,
                 language_code: Optional[_builtins.int] = None,
                 security_group_id: Optional[_builtins.str] = None,
                 template_metadata: Optional[_builtins.str] = None,
                 templates: Optional[Sequence[_builtins.str]] = None):
        """
        Dataverse provisioning configuration.

            Mirrors the ``var.dataverse`` object in the AVM ``res-environment`` module.
            Passing a :class:`DataverseConfig` instance triggers Dataverse provisioning
            on the underlying ``Environment`` resource.

            Field names follow the AVM variable names (snake_case).  The component maps
            them to the camelCase wire names expected by the Pulumi provider.
            
        """
        if administration_mode_enabled is not None:
            pulumi.set(__self__, "administration_mode_enabled", administration_mode_enabled)
        if background_operation_enabled is not None:
            pulumi.set(__self__, "background_operation_enabled", background_operation_enabled)
        if currency_code is not None:
            pulumi.set(__self__, "currency_code", currency_code)
        if domain is not None:
            pulumi.set(__self__, "domain", domain)
        if language_code is not None:
            pulumi.set(__self__, "language_code", language_code)
        if security_group_id is not None:
            pulumi.set(__self__, "security_group_id", security_group_id)
        if template_metadata is not None:
            pulumi.set(__self__, "template_metadata", template_metadata)
        if templates is not None:
            pulumi.set(__self__, "templates", templates)

    @_builtins.property
    @pulumi.getter(name="administrationModeEnabled")
    def administration_mode_enabled(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "administration_mode_enabled")

    @administration_mode_enabled.setter
    def administration_mode_enabled(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "administration_mode_enabled", value)

    @_builtins.property
    @pulumi.getter(name="backgroundOperationEnabled")
    def background_operation_enabled(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "background_operation_enabled")

    @background_operation_enabled.setter
    def background_operation_enabled(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "background_operation_enabled", value)

    @_builtins.property
    @pulumi.getter(name="currencyCode")
    def currency_code(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "currency_code")

    @currency_code.setter
    def currency_code(self, value: Optional[_builtins.str]):
        pulumi.set(self, "currency_code", value)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: Optional[_builtins.str]):
        pulumi.set(self, "domain", value)

    @_builtins.property
    @pulumi.getter(name="languageCode")
    def language_code(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "language_code")

    @language_code.setter
    def language_code(self, value: Optional[_builtins.int]):
        pulumi.set(self, "language_code", value)

    @_builtins.property
    @pulumi.getter(name="securityGroupId")
    def security_group_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "security_group_id")

    @security_group_id.setter
    def security_group_id(self, value: Optional[_builtins.str]):
        pulumi.set(self, "security_group_id", value)

    @_builtins.property
    @pulumi.getter(name="templateMetadata")
    def template_metadata(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "template_metadata")

    @template_metadata.setter
    def template_metadata(self, value: Optional[_builtins.str]):
        pulumi.set(self, "template_metadata", value)

    @_builtins.property
    @pulumi.getter
    def templates(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "templates")

    @templates.setter
    def templates(self, value: Optional[Sequence[_builtins.str]]):
        pulumi.set(self, "templates", value)


class PipelineEnvironmentEntryArgsDict(TypedDict):
    """
    One environment entry in the ResDeploymentPipeline environments map.
    """
    id: pulumi.Input[_builtins.str]
    """
    Power Platform environment ID (GUID).
    """
    name: pulumi.Input[_builtins.str]
    """
    Display name for the deployment environment record.
    """

@pulumi.input_type
class PipelineEnvironmentEntryArgs:
    def __init__(__self__, *,
                 id: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str]):
        """
        One environment entry in the ResDeploymentPipeline environments map.

        :param pulumi.Input[_builtins.str] id: Power Platform environment ID (GUID).
        :param pulumi.Input[_builtins.str] name: Display name for the deployment environment record.
        """
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def id(self) -> pulumi.Input[_builtins.str]:
        """
        Power Platform environment ID (GUID).
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Display name for the deployment environment record.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)


class PipelineStageConfigArgsDict(TypedDict):
    """
    Configuration for one deployment stage.
    """
    environment_key: pulumi.Input[_builtins.str]
    """
    Key in the environments map identifying the target environment.
    """
    deployment_spn_client_id: NotRequired[pulumi.Input[_builtins.str]]
    """
    Service principal client ID for delegated deployment.
    """
    description: NotRequired[pulumi.Input[_builtins.str]]
    """
    Optional stage description.
    """
    is_sharing_enabled: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Whether sharing is enabled for this stage. Default: true.
    """
    require_predeployment_approval: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Require pre-deployment approval. Default: false.
    """
    require_preexport_approval: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Require pre-export approval (stage 0 only). Default: false.
    """
    use_delegated_deployment: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Use delegated deployment. Default: false.
    """

@pulumi.input_type
class PipelineStageConfigArgs:
    def __init__(__self__, *,
                 environment_key: pulumi.Input[_builtins.str],
                 deployment_spn_client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 is_sharing_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 require_predeployment_approval: Optional[pulumi.Input[_builtins.bool]] = None,
                 require_preexport_approval: Optional[pulumi.Input[_builtins.bool]] = None,
                 use_delegated_deployment: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        Configuration for one deployment stage.

        :param pulumi.Input[_builtins.str] environment_key: Key in the environments map identifying the target environment.
        :param pulumi.Input[_builtins.str] deployment_spn_client_id: Service principal client ID for delegated deployment.
        :param pulumi.Input[_builtins.str] description: Optional stage description.
        :param pulumi.Input[_builtins.bool] is_sharing_enabled: Whether sharing is enabled for this stage. Default: true.
        :param pulumi.Input[_builtins.bool] require_predeployment_approval: Require pre-deployment approval. Default: false.
        :param pulumi.Input[_builtins.bool] require_preexport_approval: Require pre-export approval (stage 0 only). Default: false.
        :param pulumi.Input[_builtins.bool] use_delegated_deployment: Use delegated deployment. Default: false.
        """
        pulumi.set(__self__, "environment_key", environment_key)
        if deployment_spn_client_id is not None:
            pulumi.set(__self__, "deployment_spn_client_id", deployment_spn_client_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if is_sharing_enabled is not None:
            pulumi.set(__self__, "is_sharing_enabled", is_sharing_enabled)
        if require_predeployment_approval is not None:
            pulumi.set(__self__, "require_predeployment_approval", require_predeployment_approval)
        if require_preexport_approval is not None:
            pulumi.set(__self__, "require_preexport_approval", require_preexport_approval)
        if use_delegated_deployment is not None:
            pulumi.set(__self__, "use_delegated_deployment", use_delegated_deployment)

    @_builtins.property
    @pulumi.getter(name="environmentKey")
    def environment_key(self) -> pulumi.Input[_builtins.str]:
        """
        Key in the environments map identifying the target environment.
        """
        return pulumi.get(self, "environment_key")

    @environment_key.setter
    def environment_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "environment_key", value)

    @_builtins.property
    @pulumi.getter(name="deploymentSpnClientId")
    def deployment_spn_client_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Service principal client ID for delegated deployment.
        """
        return pulumi.get(self, "deployment_spn_client_id")

    @deployment_spn_client_id.setter
    def deployment_spn_client_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "deployment_spn_client_id", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional stage description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="isSharingEnabled")
    def is_sharing_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether sharing is enabled for this stage. Default: true.
        """
        return pulumi.get(self, "is_sharing_enabled")

    @is_sharing_enabled.setter
    def is_sharing_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_sharing_enabled", value)

    @_builtins.property
    @pulumi.getter(name="requirePredeploymentApproval")
    def require_predeployment_approval(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Require pre-deployment approval. Default: false.
        """
        return pulumi.get(self, "require_predeployment_approval")

    @require_predeployment_approval.setter
    def require_predeployment_approval(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "require_predeployment_approval", value)

    @_builtins.property
    @pulumi.getter(name="requirePreexportApproval")
    def require_preexport_approval(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Require pre-export approval (stage 0 only). Default: false.
        """
        return pulumi.get(self, "require_preexport_approval")

    @require_preexport_approval.setter
    def require_preexport_approval(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "require_preexport_approval", value)

    @_builtins.property
    @pulumi.getter(name="useDelegatedDeployment")
    def use_delegated_deployment(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Use delegated deployment. Default: false.
        """
        return pulumi.get(self, "use_delegated_deployment")

    @use_delegated_deployment.setter
    def use_delegated_deployment(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "use_delegated_deployment", value)


