# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._inputs import *

__all__ = ['ResDeploymentPipelineArgs', 'ResDeploymentPipeline']

@pulumi.input_type
class ResDeploymentPipelineArgs:
    def __init__(__self__, *,
                 dev_environment_key: _builtins.str,
                 environments: Mapping[str, pulumi.Input['PipelineEnvironmentEntryArgs']],
                 host_environment_id: _builtins.str,
                 pipeline_name: _builtins.str,
                 pipeline_stages: Sequence[pulumi.Input['PipelineStageConfigArgs']],
                 deployment_pipeline_user_role_id: Optional[_builtins.str] = None,
                 enable_ai_deployment_notes: Optional[_builtins.bool] = None,
                 enable_redeployment: Optional[_builtins.bool] = None,
                 enable_telemetry: Optional[_builtins.bool] = None,
                 lifecycle_state: Optional[_builtins.str] = None,
                 pipeline_description: Optional[_builtins.str] = None,
                 root_business_unit_id: Optional[_builtins.str] = None,
                 security_group_id: Optional[_builtins.str] = None):
        """
        The set of arguments for constructing a ResDeploymentPipeline resource.
        """
        pulumi.set(__self__, "dev_environment_key", dev_environment_key)
        pulumi.set(__self__, "environments", environments)
        pulumi.set(__self__, "host_environment_id", host_environment_id)
        pulumi.set(__self__, "pipeline_name", pipeline_name)
        pulumi.set(__self__, "pipeline_stages", pipeline_stages)
        if deployment_pipeline_user_role_id is not None:
            pulumi.set(__self__, "deployment_pipeline_user_role_id", deployment_pipeline_user_role_id)
        if enable_ai_deployment_notes is not None:
            pulumi.set(__self__, "enable_ai_deployment_notes", enable_ai_deployment_notes)
        if enable_redeployment is not None:
            pulumi.set(__self__, "enable_redeployment", enable_redeployment)
        if enable_telemetry is not None:
            pulumi.set(__self__, "enable_telemetry", enable_telemetry)
        if lifecycle_state is not None:
            pulumi.set(__self__, "lifecycle_state", lifecycle_state)
        if pipeline_description is not None:
            pulumi.set(__self__, "pipeline_description", pipeline_description)
        if root_business_unit_id is not None:
            pulumi.set(__self__, "root_business_unit_id", root_business_unit_id)
        if security_group_id is not None:
            pulumi.set(__self__, "security_group_id", security_group_id)

    @_builtins.property
    @pulumi.getter(name="devEnvironmentKey")
    def dev_environment_key(self) -> _builtins.str:
        return pulumi.get(self, "dev_environment_key")

    @dev_environment_key.setter
    def dev_environment_key(self, value: _builtins.str):
        pulumi.set(self, "dev_environment_key", value)

    @_builtins.property
    @pulumi.getter
    def environments(self) -> Mapping[str, pulumi.Input['PipelineEnvironmentEntryArgs']]:
        return pulumi.get(self, "environments")

    @environments.setter
    def environments(self, value: Mapping[str, pulumi.Input['PipelineEnvironmentEntryArgs']]):
        pulumi.set(self, "environments", value)

    @_builtins.property
    @pulumi.getter(name="hostEnvironmentId")
    def host_environment_id(self) -> _builtins.str:
        return pulumi.get(self, "host_environment_id")

    @host_environment_id.setter
    def host_environment_id(self, value: _builtins.str):
        pulumi.set(self, "host_environment_id", value)

    @_builtins.property
    @pulumi.getter(name="pipelineName")
    def pipeline_name(self) -> _builtins.str:
        return pulumi.get(self, "pipeline_name")

    @pipeline_name.setter
    def pipeline_name(self, value: _builtins.str):
        pulumi.set(self, "pipeline_name", value)

    @_builtins.property
    @pulumi.getter(name="pipelineStages")
    def pipeline_stages(self) -> Sequence[pulumi.Input['PipelineStageConfigArgs']]:
        return pulumi.get(self, "pipeline_stages")

    @pipeline_stages.setter
    def pipeline_stages(self, value: Sequence[pulumi.Input['PipelineStageConfigArgs']]):
        pulumi.set(self, "pipeline_stages", value)

    @_builtins.property
    @pulumi.getter(name="deploymentPipelineUserRoleId")
    def deployment_pipeline_user_role_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "deployment_pipeline_user_role_id")

    @deployment_pipeline_user_role_id.setter
    def deployment_pipeline_user_role_id(self, value: Optional[_builtins.str]):
        pulumi.set(self, "deployment_pipeline_user_role_id", value)

    @_builtins.property
    @pulumi.getter(name="enableAiDeploymentNotes")
    def enable_ai_deployment_notes(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "enable_ai_deployment_notes")

    @enable_ai_deployment_notes.setter
    def enable_ai_deployment_notes(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "enable_ai_deployment_notes", value)

    @_builtins.property
    @pulumi.getter(name="enableRedeployment")
    def enable_redeployment(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "enable_redeployment")

    @enable_redeployment.setter
    def enable_redeployment(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "enable_redeployment", value)

    @_builtins.property
    @pulumi.getter(name="enableTelemetry")
    def enable_telemetry(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "enable_telemetry")

    @enable_telemetry.setter
    def enable_telemetry(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "enable_telemetry", value)

    @_builtins.property
    @pulumi.getter(name="lifecycleState")
    def lifecycle_state(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "lifecycle_state")

    @lifecycle_state.setter
    def lifecycle_state(self, value: Optional[_builtins.str]):
        pulumi.set(self, "lifecycle_state", value)

    @_builtins.property
    @pulumi.getter(name="pipelineDescription")
    def pipeline_description(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "pipeline_description")

    @pipeline_description.setter
    def pipeline_description(self, value: Optional[_builtins.str]):
        pulumi.set(self, "pipeline_description", value)

    @_builtins.property
    @pulumi.getter(name="rootBusinessUnitId")
    def root_business_unit_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "root_business_unit_id")

    @root_business_unit_id.setter
    def root_business_unit_id(self, value: Optional[_builtins.str]):
        pulumi.set(self, "root_business_unit_id", value)

    @_builtins.property
    @pulumi.getter(name="securityGroupId")
    def security_group_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "security_group_id")

    @security_group_id.setter
    def security_group_id(self, value: Optional[_builtins.str]):
        pulumi.set(self, "security_group_id", value)


@pulumi.type_token("powerplatform:components:ResDeploymentPipeline")
class ResDeploymentPipeline(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 deployment_pipeline_user_role_id: Optional[_builtins.str] = None,
                 dev_environment_key: Optional[_builtins.str] = None,
                 enable_ai_deployment_notes: Optional[_builtins.bool] = None,
                 enable_redeployment: Optional[_builtins.bool] = None,
                 enable_telemetry: Optional[_builtins.bool] = None,
                 environments: Optional[Mapping[str, pulumi.Input[Union['PipelineEnvironmentEntryArgs', 'PipelineEnvironmentEntryArgsDict']]]] = None,
                 host_environment_id: Optional[_builtins.str] = None,
                 lifecycle_state: Optional[_builtins.str] = None,
                 pipeline_description: Optional[_builtins.str] = None,
                 pipeline_name: Optional[_builtins.str] = None,
                 pipeline_stages: Optional[Sequence[pulumi.Input[Union['PipelineStageConfigArgs', 'PipelineStageConfigArgsDict']]]] = None,
                 root_business_unit_id: Optional[_builtins.str] = None,
                 security_group_id: Optional[_builtins.str] = None,
                 __props__=None):
        """
        AVM-aligned component that manages a Power Platform deployment pipeline lifecycle.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ResDeploymentPipelineArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        AVM-aligned component that manages a Power Platform deployment pipeline lifecycle.


        :param str resource_name: The name of the resource.
        :param ResDeploymentPipelineArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ResDeploymentPipelineArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 deployment_pipeline_user_role_id: Optional[_builtins.str] = None,
                 dev_environment_key: Optional[_builtins.str] = None,
                 enable_ai_deployment_notes: Optional[_builtins.bool] = None,
                 enable_redeployment: Optional[_builtins.bool] = None,
                 enable_telemetry: Optional[_builtins.bool] = None,
                 environments: Optional[Mapping[str, pulumi.Input[Union['PipelineEnvironmentEntryArgs', 'PipelineEnvironmentEntryArgsDict']]]] = None,
                 host_environment_id: Optional[_builtins.str] = None,
                 lifecycle_state: Optional[_builtins.str] = None,
                 pipeline_description: Optional[_builtins.str] = None,
                 pipeline_name: Optional[_builtins.str] = None,
                 pipeline_stages: Optional[Sequence[pulumi.Input[Union['PipelineStageConfigArgs', 'PipelineStageConfigArgsDict']]]] = None,
                 root_business_unit_id: Optional[_builtins.str] = None,
                 security_group_id: Optional[_builtins.str] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ResDeploymentPipelineArgs.__new__(ResDeploymentPipelineArgs)

            __props__.__dict__["deployment_pipeline_user_role_id"] = deployment_pipeline_user_role_id
            if dev_environment_key is None and not opts.urn:
                raise TypeError("Missing required property 'dev_environment_key'")
            __props__.__dict__["dev_environment_key"] = dev_environment_key
            __props__.__dict__["enable_ai_deployment_notes"] = enable_ai_deployment_notes
            __props__.__dict__["enable_redeployment"] = enable_redeployment
            __props__.__dict__["enable_telemetry"] = enable_telemetry
            if environments is None and not opts.urn:
                raise TypeError("Missing required property 'environments'")
            __props__.__dict__["environments"] = environments
            if host_environment_id is None and not opts.urn:
                raise TypeError("Missing required property 'host_environment_id'")
            __props__.__dict__["host_environment_id"] = host_environment_id
            __props__.__dict__["lifecycle_state"] = lifecycle_state
            __props__.__dict__["pipeline_description"] = pipeline_description
            if pipeline_name is None and not opts.urn:
                raise TypeError("Missing required property 'pipeline_name'")
            __props__.__dict__["pipeline_name"] = pipeline_name
            if pipeline_stages is None and not opts.urn:
                raise TypeError("Missing required property 'pipeline_stages'")
            __props__.__dict__["pipeline_stages"] = pipeline_stages
            __props__.__dict__["root_business_unit_id"] = root_business_unit_id
            __props__.__dict__["security_group_id"] = security_group_id
            __props__.__dict__["deployment_environment_ids"] = None
            __props__.__dict__["deployment_stage_ids"] = None
            __props__.__dict__["pipeline_id"] = None
            __props__.__dict__["pipeline_team_id"] = None
            __props__.__dict__["resource_id"] = None
        super(ResDeploymentPipeline, __self__).__init__(
            'powerplatform:components:ResDeploymentPipeline',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="deploymentEnvironmentIds")
    def deployment_environment_ids(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "deployment_environment_ids")

    @_builtins.property
    @pulumi.getter(name="deploymentStageIds")
    def deployment_stage_ids(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        return pulumi.get(self, "deployment_stage_ids")

    @_builtins.property
    @pulumi.getter(name="pipelineId")
    def pipeline_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "pipeline_id")

    @_builtins.property
    @pulumi.getter(name="pipelineName")
    def pipeline_name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "pipeline_name")

    @_builtins.property
    @pulumi.getter(name="pipelineTeamId")
    def pipeline_team_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "pipeline_team_id")

    @_builtins.property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "resource_id")

