// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class TenantIntelligenceSettings {
    /**
     * @return Disable Copilot.
     * 
     */
    private @Nullable Boolean disableCopilot;
    /**
     * @return Enable OpenAI bot publishing.
     * 
     */
    private @Nullable Boolean enableOpenAiBotPublishing;

    private TenantIntelligenceSettings() {}
    /**
     * @return Disable Copilot.
     * 
     */
    public Optional<Boolean> disableCopilot() {
        return Optional.ofNullable(this.disableCopilot);
    }
    /**
     * @return Enable OpenAI bot publishing.
     * 
     */
    public Optional<Boolean> enableOpenAiBotPublishing() {
        return Optional.ofNullable(this.enableOpenAiBotPublishing);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(TenantIntelligenceSettings defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean disableCopilot;
        private @Nullable Boolean enableOpenAiBotPublishing;
        public Builder() {}
        public Builder(TenantIntelligenceSettings defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.disableCopilot = defaults.disableCopilot;
    	      this.enableOpenAiBotPublishing = defaults.enableOpenAiBotPublishing;
        }

        @CustomType.Setter
        public Builder disableCopilot(@Nullable Boolean disableCopilot) {

            this.disableCopilot = disableCopilot;
            return this;
        }
        @CustomType.Setter
        public Builder enableOpenAiBotPublishing(@Nullable Boolean enableOpenAiBotPublishing) {

            this.enableOpenAiBotPublishing = enableOpenAiBotPublishing;
            return this;
        }
        public TenantIntelligenceSettings build() {
            final var _resultValue = new TenantIntelligenceSettings();
            _resultValue.disableCopilot = disableCopilot;
            _resultValue.enableOpenAiBotPublishing = enableOpenAiBotPublishing;
            return _resultValue;
        }
    }
}
