// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class TenantPowerAutomateSettings {
    /**
     * @return Disable Copilot for Power Automate.
     * 
     */
    private @Nullable Boolean disableCopilot;

    private TenantPowerAutomateSettings() {}
    /**
     * @return Disable Copilot for Power Automate.
     * 
     */
    public Optional<Boolean> disableCopilot() {
        return Optional.ofNullable(this.disableCopilot);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(TenantPowerAutomateSettings defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean disableCopilot;
        public Builder() {}
        public Builder(TenantPowerAutomateSettings defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.disableCopilot = defaults.disableCopilot;
        }

        @CustomType.Setter
        public Builder disableCopilot(@Nullable Boolean disableCopilot) {

            this.disableCopilot = disableCopilot;
            return this;
        }
        public TenantPowerAutomateSettings build() {
            final var _resultValue = new TenantPowerAutomateSettings();
            _resultValue.disableCopilot = disableCopilot;
            return _resultValue;
        }
    }
}
