// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package components

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rpothin/pulumi-powerplatform/sdk/go/powerplatform/internal"
)

var _ = internal.GetEnvOrDefault

// Dataverse provisioning configuration.
//
//	Mirrors the ``var.dataverse`` object in the AVM ``res-environment`` module.
//	Passing a :class:`DataverseConfig` instance triggers Dataverse provisioning
//	on the underlying ``Environment`` resource.
//
//	Field names follow the AVM variable names (snake_case).  The component maps
//	them to the camelCase wire names expected by the Pulumi provider.
type DataverseConfig struct {
	AdministrationModeEnabled  *bool    `pulumi:"administrationModeEnabled"`
	BackgroundOperationEnabled *bool    `pulumi:"backgroundOperationEnabled"`
	CurrencyCode               *string  `pulumi:"currencyCode"`
	Domain                     *string  `pulumi:"domain"`
	LanguageCode               *int     `pulumi:"languageCode"`
	SecurityGroupId            *string  `pulumi:"securityGroupId"`
	TemplateMetadata           *string  `pulumi:"templateMetadata"`
	Templates                  []string `pulumi:"templates"`
}

// DataverseConfigInput is an input type that accepts DataverseConfigArgs and DataverseConfigOutput values.
// You can construct a concrete instance of `DataverseConfigInput` via:
//
//	DataverseConfigArgs{...}
type DataverseConfigInput interface {
	pulumi.Input

	ToDataverseConfigOutput() DataverseConfigOutput
	ToDataverseConfigOutputWithContext(context.Context) DataverseConfigOutput
}

// Dataverse provisioning configuration.
//
//	Mirrors the ``var.dataverse`` object in the AVM ``res-environment`` module.
//	Passing a :class:`DataverseConfig` instance triggers Dataverse provisioning
//	on the underlying ``Environment`` resource.
//
//	Field names follow the AVM variable names (snake_case).  The component maps
//	them to the camelCase wire names expected by the Pulumi provider.
type DataverseConfigArgs struct {
	AdministrationModeEnabled  *bool    `pulumi:"administrationModeEnabled"`
	BackgroundOperationEnabled *bool    `pulumi:"backgroundOperationEnabled"`
	CurrencyCode               *string  `pulumi:"currencyCode"`
	Domain                     *string  `pulumi:"domain"`
	LanguageCode               *int     `pulumi:"languageCode"`
	SecurityGroupId            *string  `pulumi:"securityGroupId"`
	TemplateMetadata           *string  `pulumi:"templateMetadata"`
	Templates                  []string `pulumi:"templates"`
}

func (DataverseConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DataverseConfig)(nil)).Elem()
}

func (i DataverseConfigArgs) ToDataverseConfigOutput() DataverseConfigOutput {
	return i.ToDataverseConfigOutputWithContext(context.Background())
}

func (i DataverseConfigArgs) ToDataverseConfigOutputWithContext(ctx context.Context) DataverseConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataverseConfigOutput)
}

func (i DataverseConfigArgs) ToDataverseConfigPtrOutput() DataverseConfigPtrOutput {
	return i.ToDataverseConfigPtrOutputWithContext(context.Background())
}

func (i DataverseConfigArgs) ToDataverseConfigPtrOutputWithContext(ctx context.Context) DataverseConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataverseConfigOutput).ToDataverseConfigPtrOutputWithContext(ctx)
}

// DataverseConfigPtrInput is an input type that accepts DataverseConfigArgs, DataverseConfigPtr and DataverseConfigPtrOutput values.
// You can construct a concrete instance of `DataverseConfigPtrInput` via:
//
//	        DataverseConfigArgs{...}
//
//	or:
//
//	        nil
type DataverseConfigPtrInput interface {
	pulumi.Input

	ToDataverseConfigPtrOutput() DataverseConfigPtrOutput
	ToDataverseConfigPtrOutputWithContext(context.Context) DataverseConfigPtrOutput
}

type dataverseConfigPtrType DataverseConfigArgs

func DataverseConfigPtr(v *DataverseConfigArgs) DataverseConfigPtrInput {
	return (*dataverseConfigPtrType)(v)
}

func (*dataverseConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DataverseConfig)(nil)).Elem()
}

func (i *dataverseConfigPtrType) ToDataverseConfigPtrOutput() DataverseConfigPtrOutput {
	return i.ToDataverseConfigPtrOutputWithContext(context.Background())
}

func (i *dataverseConfigPtrType) ToDataverseConfigPtrOutputWithContext(ctx context.Context) DataverseConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataverseConfigPtrOutput)
}

// Dataverse provisioning configuration.
//
//	Mirrors the ``var.dataverse`` object in the AVM ``res-environment`` module.
//	Passing a :class:`DataverseConfig` instance triggers Dataverse provisioning
//	on the underlying ``Environment`` resource.
//
//	Field names follow the AVM variable names (snake_case).  The component maps
//	them to the camelCase wire names expected by the Pulumi provider.
type DataverseConfigOutput struct{ *pulumi.OutputState }

func (DataverseConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DataverseConfig)(nil)).Elem()
}

func (o DataverseConfigOutput) ToDataverseConfigOutput() DataverseConfigOutput {
	return o
}

func (o DataverseConfigOutput) ToDataverseConfigOutputWithContext(ctx context.Context) DataverseConfigOutput {
	return o
}

func (o DataverseConfigOutput) ToDataverseConfigPtrOutput() DataverseConfigPtrOutput {
	return o.ToDataverseConfigPtrOutputWithContext(context.Background())
}

func (o DataverseConfigOutput) ToDataverseConfigPtrOutputWithContext(ctx context.Context) DataverseConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DataverseConfig) *DataverseConfig {
		return &v
	}).(DataverseConfigPtrOutput)
}

func (o DataverseConfigOutput) AdministrationModeEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v DataverseConfig) *bool { return v.AdministrationModeEnabled }).(pulumi.BoolPtrOutput)
}

func (o DataverseConfigOutput) BackgroundOperationEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v DataverseConfig) *bool { return v.BackgroundOperationEnabled }).(pulumi.BoolPtrOutput)
}

func (o DataverseConfigOutput) CurrencyCode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DataverseConfig) *string { return v.CurrencyCode }).(pulumi.StringPtrOutput)
}

func (o DataverseConfigOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DataverseConfig) *string { return v.Domain }).(pulumi.StringPtrOutput)
}

func (o DataverseConfigOutput) LanguageCode() pulumi.IntPtrOutput {
	return o.ApplyT(func(v DataverseConfig) *int { return v.LanguageCode }).(pulumi.IntPtrOutput)
}

func (o DataverseConfigOutput) SecurityGroupId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DataverseConfig) *string { return v.SecurityGroupId }).(pulumi.StringPtrOutput)
}

func (o DataverseConfigOutput) TemplateMetadata() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DataverseConfig) *string { return v.TemplateMetadata }).(pulumi.StringPtrOutput)
}

func (o DataverseConfigOutput) Templates() pulumi.StringArrayOutput {
	return o.ApplyT(func(v DataverseConfig) []string { return v.Templates }).(pulumi.StringArrayOutput)
}

type DataverseConfigPtrOutput struct{ *pulumi.OutputState }

func (DataverseConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DataverseConfig)(nil)).Elem()
}

func (o DataverseConfigPtrOutput) ToDataverseConfigPtrOutput() DataverseConfigPtrOutput {
	return o
}

func (o DataverseConfigPtrOutput) ToDataverseConfigPtrOutputWithContext(ctx context.Context) DataverseConfigPtrOutput {
	return o
}

func (o DataverseConfigPtrOutput) Elem() DataverseConfigOutput {
	return o.ApplyT(func(v *DataverseConfig) DataverseConfig {
		if v != nil {
			return *v
		}
		var ret DataverseConfig
		return ret
	}).(DataverseConfigOutput)
}

func (o DataverseConfigPtrOutput) AdministrationModeEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DataverseConfig) *bool {
		if v == nil {
			return nil
		}
		return v.AdministrationModeEnabled
	}).(pulumi.BoolPtrOutput)
}

func (o DataverseConfigPtrOutput) BackgroundOperationEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DataverseConfig) *bool {
		if v == nil {
			return nil
		}
		return v.BackgroundOperationEnabled
	}).(pulumi.BoolPtrOutput)
}

func (o DataverseConfigPtrOutput) CurrencyCode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DataverseConfig) *string {
		if v == nil {
			return nil
		}
		return v.CurrencyCode
	}).(pulumi.StringPtrOutput)
}

func (o DataverseConfigPtrOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DataverseConfig) *string {
		if v == nil {
			return nil
		}
		return v.Domain
	}).(pulumi.StringPtrOutput)
}

func (o DataverseConfigPtrOutput) LanguageCode() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DataverseConfig) *int {
		if v == nil {
			return nil
		}
		return v.LanguageCode
	}).(pulumi.IntPtrOutput)
}

func (o DataverseConfigPtrOutput) SecurityGroupId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DataverseConfig) *string {
		if v == nil {
			return nil
		}
		return v.SecurityGroupId
	}).(pulumi.StringPtrOutput)
}

func (o DataverseConfigPtrOutput) TemplateMetadata() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DataverseConfig) *string {
		if v == nil {
			return nil
		}
		return v.TemplateMetadata
	}).(pulumi.StringPtrOutput)
}

func (o DataverseConfigPtrOutput) Templates() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DataverseConfig) []string {
		if v == nil {
			return nil
		}
		return v.Templates
	}).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DataverseConfigInput)(nil)).Elem(), DataverseConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DataverseConfigPtrInput)(nil)).Elem(), DataverseConfigArgs{})
	pulumi.RegisterOutputType(DataverseConfigOutput{})
	pulumi.RegisterOutputType(DataverseConfigPtrOutput{})
}
