// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package components

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rpothin/pulumi-powerplatform/sdk/go/powerplatform/internal"
)

// AVM-aligned component that manages a Power Platform deployment pipeline lifecycle through deployment environments, stages, and optional team sharing.
type ResDeploymentPipeline struct {
	pulumi.ResourceState

	// Map of environment keys to deployment environment record IDs.
	DeploymentEnvironmentIds pulumi.StringMapOutput `pulumi:"deploymentEnvironmentIds"`
	// Map of environment keys to deployment stage record IDs.
	DeploymentStageIds pulumi.StringMapOutput `pulumi:"deploymentStageIds"`
	// Deployment pipeline record ID.
	PipelineId pulumi.StringOutput `pulumi:"pipelineId"`
	// Pipeline display name.
	PipelineName pulumi.StringOutput `pulumi:"pipelineName"`
	// Team record ID (empty string when no securityGroupId was provided).
	PipelineTeamId pulumi.StringOutput `pulumi:"pipelineTeamId"`
	// AVM-standard primary output: deployment pipeline record ID.
	ResourceId pulumi.StringOutput `pulumi:"resourceId"`
}

// NewResDeploymentPipeline registers a new resource with the given unique name, arguments, and options.
func NewResDeploymentPipeline(ctx *pulumi.Context,
	name string, args *ResDeploymentPipelineArgs, opts ...pulumi.ResourceOption) (*ResDeploymentPipeline, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Environments == nil {
		return nil, errors.New("invalid value for required argument 'Environments'")
	}
	if args.PipelineStages == nil {
		return nil, errors.New("invalid value for required argument 'PipelineStages'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ResDeploymentPipeline
	err := ctx.RegisterRemoteComponentResource("powerplatform:components:ResDeploymentPipeline", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type resDeploymentPipelineArgs struct {
	// Deployment Pipeline User security role ID. Required when securityGroupId is set.
	DeploymentPipelineUserRoleId *string `pulumi:"deploymentPipelineUserRoleId"`
	// Key in environments identifying the development (source) environment.
	DevEnvironmentKey string `pulumi:"devEnvironmentKey"`
	// Enable AI deployment notes. Default: true.
	EnableAiDeploymentNotes *bool `pulumi:"enableAiDeploymentNotes"`
	// Enable redeployment. Default: true.
	EnableRedeployment *bool `pulumi:"enableRedeployment"`
	// Enable telemetry. Default: true.
	EnableTelemetry *bool `pulumi:"enableTelemetry"`
	// Map of environment entries. Minimum 2 entries. Keys must be known at plan time.
	Environments map[string]PipelineEnvironmentEntry `pulumi:"environments"`
	// Pipelines Host environment ID. Required.
	HostEnvironmentId string `pulumi:"hostEnvironmentId"`
	// active or inactive. Default: active.
	LifecycleState *string `pulumi:"lifecycleState"`
	// Pipeline description (max 500 characters).
	PipelineDescription *string `pulumi:"pipelineDescription"`
	// Pipeline display name (1–100 characters). Required.
	PipelineName string `pulumi:"pipelineName"`
	// Deployment stages (1–6). Each stage maps to a target environment.
	PipelineStages []PipelineStageConfig `pulumi:"pipelineStages"`
	// Root business unit ID in the host environment. Required when securityGroupId is set.
	RootBusinessUnitId *string `pulumi:"rootBusinessUnitId"`
	// Entra ID security group GUID. When set, creates a team and shares the pipeline.
	SecurityGroupId *string `pulumi:"securityGroupId"`
}

// The set of arguments for constructing a ResDeploymentPipeline resource.
type ResDeploymentPipelineArgs struct {
	// Deployment Pipeline User security role ID. Required when securityGroupId is set.
	DeploymentPipelineUserRoleId *string
	// Key in environments identifying the development (source) environment.
	DevEnvironmentKey string
	// Enable AI deployment notes. Default: true.
	EnableAiDeploymentNotes *bool
	// Enable redeployment. Default: true.
	EnableRedeployment *bool
	// Enable telemetry. Default: true.
	EnableTelemetry *bool
	// Map of environment entries. Minimum 2 entries. Keys must be known at plan time.
	Environments map[string]PipelineEnvironmentEntryInput
	// Pipelines Host environment ID. Required.
	HostEnvironmentId string
	// active or inactive. Default: active.
	LifecycleState *string
	// Pipeline description (max 500 characters).
	PipelineDescription *string
	// Pipeline display name (1–100 characters). Required.
	PipelineName string
	// Deployment stages (1–6). Each stage maps to a target environment.
	PipelineStages []PipelineStageConfigInput
	// Root business unit ID in the host environment. Required when securityGroupId is set.
	RootBusinessUnitId *string
	// Entra ID security group GUID. When set, creates a team and shares the pipeline.
	SecurityGroupId *string
}

func (ResDeploymentPipelineArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*resDeploymentPipelineArgs)(nil)).Elem()
}

type ResDeploymentPipelineInput interface {
	pulumi.Input

	ToResDeploymentPipelineOutput() ResDeploymentPipelineOutput
	ToResDeploymentPipelineOutputWithContext(ctx context.Context) ResDeploymentPipelineOutput
}

func (*ResDeploymentPipeline) ElementType() reflect.Type {
	return reflect.TypeOf((**ResDeploymentPipeline)(nil)).Elem()
}

func (i *ResDeploymentPipeline) ToResDeploymentPipelineOutput() ResDeploymentPipelineOutput {
	return i.ToResDeploymentPipelineOutputWithContext(context.Background())
}

func (i *ResDeploymentPipeline) ToResDeploymentPipelineOutputWithContext(ctx context.Context) ResDeploymentPipelineOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResDeploymentPipelineOutput)
}

type ResDeploymentPipelineOutput struct{ *pulumi.OutputState }

func (ResDeploymentPipelineOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ResDeploymentPipeline)(nil)).Elem()
}

func (o ResDeploymentPipelineOutput) ToResDeploymentPipelineOutput() ResDeploymentPipelineOutput {
	return o
}

func (o ResDeploymentPipelineOutput) ToResDeploymentPipelineOutputWithContext(ctx context.Context) ResDeploymentPipelineOutput {
	return o
}

// Map of environment keys to deployment environment record IDs.
func (o ResDeploymentPipelineOutput) DeploymentEnvironmentIds() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ResDeploymentPipeline) pulumi.StringMapOutput { return v.DeploymentEnvironmentIds }).(pulumi.StringMapOutput)
}

// Map of environment keys to deployment stage record IDs.
func (o ResDeploymentPipelineOutput) DeploymentStageIds() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ResDeploymentPipeline) pulumi.StringMapOutput { return v.DeploymentStageIds }).(pulumi.StringMapOutput)
}

// Deployment pipeline record ID.
func (o ResDeploymentPipelineOutput) PipelineId() pulumi.StringOutput {
	return o.ApplyT(func(v *ResDeploymentPipeline) pulumi.StringOutput { return v.PipelineId }).(pulumi.StringOutput)
}

// Pipeline display name.
func (o ResDeploymentPipelineOutput) PipelineName() pulumi.StringOutput {
	return o.ApplyT(func(v *ResDeploymentPipeline) pulumi.StringOutput { return v.PipelineName }).(pulumi.StringOutput)
}

// Team record ID (empty string when no securityGroupId was provided).
func (o ResDeploymentPipelineOutput) PipelineTeamId() pulumi.StringOutput {
	return o.ApplyT(func(v *ResDeploymentPipeline) pulumi.StringOutput { return v.PipelineTeamId }).(pulumi.StringOutput)
}

// AVM-standard primary output: deployment pipeline record ID.
func (o ResDeploymentPipelineOutput) ResourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *ResDeploymentPipeline) pulumi.StringOutput { return v.ResourceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ResDeploymentPipelineInput)(nil)).Elem(), &ResDeploymentPipeline{})
	pulumi.RegisterOutputType(ResDeploymentPipelineOutput{})
}
