// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class EnvironmentBackupArgs extends com.pulumi.resources.ResourceArgs {

    public static final EnvironmentBackupArgs Empty = new EnvironmentBackupArgs();

    /**
     * The ID of the environment to back up.
     * 
     */
    @Import(name="environmentId", required=true)
    private Output<String> environmentId;

    /**
     * @return The ID of the environment to back up.
     * 
     */
    public Output<String> environmentId() {
        return this.environmentId;
    }

    /**
     * A descriptive label for the backup.
     * 
     */
    @Import(name="label", required=true)
    private Output<String> label;

    /**
     * @return A descriptive label for the backup.
     * 
     */
    public Output<String> label() {
        return this.label;
    }

    private EnvironmentBackupArgs() {}

    private EnvironmentBackupArgs(EnvironmentBackupArgs $) {
        this.environmentId = $.environmentId;
        this.label = $.label;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EnvironmentBackupArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EnvironmentBackupArgs $;

        public Builder() {
            $ = new EnvironmentBackupArgs();
        }

        public Builder(EnvironmentBackupArgs defaults) {
            $ = new EnvironmentBackupArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param environmentId The ID of the environment to back up.
         * 
         * @return builder
         * 
         */
        public Builder environmentId(Output<String> environmentId) {
            $.environmentId = environmentId;
            return this;
        }

        /**
         * @param environmentId The ID of the environment to back up.
         * 
         * @return builder
         * 
         */
        public Builder environmentId(String environmentId) {
            return environmentId(Output.of(environmentId));
        }

        /**
         * @param label A descriptive label for the backup.
         * 
         * @return builder
         * 
         */
        public Builder label(Output<String> label) {
            $.label = label;
            return this;
        }

        /**
         * @param label A descriptive label for the backup.
         * 
         * @return builder
         * 
         */
        public Builder label(String label) {
            return label(Output.of(label));
        }

        public EnvironmentBackupArgs build() {
            if ($.environmentId == null) {
                throw new MissingRequiredPropertyException("EnvironmentBackupArgs", "environmentId");
            }
            if ($.label == null) {
                throw new MissingRequiredPropertyException("EnvironmentBackupArgs", "label");
            }
            return $;
        }
    }

}
