// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.github.rpothin.powerplatform;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.github.rpothin.powerplatform.EnvironmentBackupArgs;
import com.github.rpothin.powerplatform.Utilities;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Creates a manual backup of a Power Platform environment. Backups are immutable — any change to inputs triggers replacement.
 * 
 */
@ResourceType(type="powerplatform:index:EnvironmentBackup")
public class EnvironmentBackup extends com.pulumi.resources.CustomResource {
    /**
     * The date and time when the backup expires.
     * 
     */
    @Export(name="backupExpiryDateTime", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> backupExpiryDateTime;

    /**
     * @return The date and time when the backup expires.
     * 
     */
    public Output<Optional<String>> backupExpiryDateTime() {
        return Codegen.optional(this.backupExpiryDateTime);
    }
    /**
     * The date and time when the backup was created.
     * 
     */
    @Export(name="backupPointDateTime", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> backupPointDateTime;

    /**
     * @return The date and time when the backup was created.
     * 
     */
    public Output<Optional<String>> backupPointDateTime() {
        return Codegen.optional(this.backupPointDateTime);
    }
    /**
     * The ID of the backed-up environment.
     * 
     */
    @Export(name="environmentId", refs={String.class}, tree="[0]")
    private Output<String> environmentId;

    /**
     * @return The ID of the backed-up environment.
     * 
     */
    public Output<String> environmentId() {
        return this.environmentId;
    }
    /**
     * The label for the backup.
     * 
     */
    @Export(name="label", refs={String.class}, tree="[0]")
    private Output<String> label;

    /**
     * @return The label for the backup.
     * 
     */
    public Output<String> label() {
        return this.label;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public EnvironmentBackup(java.lang.String name) {
        this(name, EnvironmentBackupArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public EnvironmentBackup(java.lang.String name, EnvironmentBackupArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public EnvironmentBackup(java.lang.String name, EnvironmentBackupArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("powerplatform:index:EnvironmentBackup", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private EnvironmentBackup(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("powerplatform:index:EnvironmentBackup", name, null, makeResourceOptions(options, id), false);
    }

    private static EnvironmentBackupArgs makeArgs(EnvironmentBackupArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? EnvironmentBackupArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/rpothin")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static EnvironmentBackup get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new EnvironmentBackup(name, id, options);
    }
}
