// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.github.rpothin.powerplatform;

import com.github.rpothin.powerplatform.Utilities;
import com.github.rpothin.powerplatform.inputs.GetAppsArgs;
import com.github.rpothin.powerplatform.inputs.GetAppsPlainArgs;
import com.github.rpothin.powerplatform.inputs.GetConnectorsArgs;
import com.github.rpothin.powerplatform.inputs.GetConnectorsPlainArgs;
import com.github.rpothin.powerplatform.inputs.GetEnvironmentsArgs;
import com.github.rpothin.powerplatform.inputs.GetEnvironmentsPlainArgs;
import com.github.rpothin.powerplatform.inputs.GetFlowsArgs;
import com.github.rpothin.powerplatform.inputs.GetFlowsPlainArgs;
import com.github.rpothin.powerplatform.outputs.GetAppsResult;
import com.github.rpothin.powerplatform.outputs.GetConnectorsResult;
import com.github.rpothin.powerplatform.outputs.GetEnvironmentsResult;
import com.github.rpothin.powerplatform.outputs.GetFlowsResult;
import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import java.util.concurrent.CompletableFuture;

public final class PowerplatformFunctions {
    /**
     * Lists Power Apps in a Power Platform environment.
     * 
     */
    public static Output<GetAppsResult> getApps(GetAppsArgs args) {
        return getApps(args, InvokeOptions.Empty);
    }
    /**
     * Lists Power Apps in a Power Platform environment.
     * 
     */
    public static CompletableFuture<GetAppsResult> getAppsPlain(GetAppsPlainArgs args) {
        return getAppsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Lists Power Apps in a Power Platform environment.
     * 
     */
    public static Output<GetAppsResult> getApps(GetAppsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getApps", TypeShape.of(GetAppsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists Power Apps in a Power Platform environment.
     * 
     */
    public static Output<GetAppsResult> getApps(GetAppsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getApps", TypeShape.of(GetAppsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists Power Apps in a Power Platform environment.
     * 
     */
    public static CompletableFuture<GetAppsResult> getAppsPlain(GetAppsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("powerplatform:index:getApps", TypeShape.of(GetAppsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists connectors available in a Power Platform environment.
     * 
     */
    public static Output<GetConnectorsResult> getConnectors(GetConnectorsArgs args) {
        return getConnectors(args, InvokeOptions.Empty);
    }
    /**
     * Lists connectors available in a Power Platform environment.
     * 
     */
    public static CompletableFuture<GetConnectorsResult> getConnectorsPlain(GetConnectorsPlainArgs args) {
        return getConnectorsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Lists connectors available in a Power Platform environment.
     * 
     */
    public static Output<GetConnectorsResult> getConnectors(GetConnectorsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getConnectors", TypeShape.of(GetConnectorsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists connectors available in a Power Platform environment.
     * 
     */
    public static Output<GetConnectorsResult> getConnectors(GetConnectorsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getConnectors", TypeShape.of(GetConnectorsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists connectors available in a Power Platform environment.
     * 
     */
    public static CompletableFuture<GetConnectorsResult> getConnectorsPlain(GetConnectorsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("powerplatform:index:getConnectors", TypeShape.of(GetConnectorsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Retrieves a list of Power Platform environments available for the authenticated user.
     * 
     */
    public static Output<GetEnvironmentsResult> getEnvironments() {
        return getEnvironments(GetEnvironmentsArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Retrieves a list of Power Platform environments available for the authenticated user.
     * 
     */
    public static CompletableFuture<GetEnvironmentsResult> getEnvironmentsPlain() {
        return getEnvironmentsPlain(GetEnvironmentsPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Retrieves a list of Power Platform environments available for the authenticated user.
     * 
     */
    public static Output<GetEnvironmentsResult> getEnvironments(GetEnvironmentsArgs args) {
        return getEnvironments(args, InvokeOptions.Empty);
    }
    /**
     * Retrieves a list of Power Platform environments available for the authenticated user.
     * 
     */
    public static CompletableFuture<GetEnvironmentsResult> getEnvironmentsPlain(GetEnvironmentsPlainArgs args) {
        return getEnvironmentsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Retrieves a list of Power Platform environments available for the authenticated user.
     * 
     */
    public static Output<GetEnvironmentsResult> getEnvironments(GetEnvironmentsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getEnvironments", TypeShape.of(GetEnvironmentsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Retrieves a list of Power Platform environments available for the authenticated user.
     * 
     */
    public static Output<GetEnvironmentsResult> getEnvironments(GetEnvironmentsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getEnvironments", TypeShape.of(GetEnvironmentsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Retrieves a list of Power Platform environments available for the authenticated user.
     * 
     */
    public static CompletableFuture<GetEnvironmentsResult> getEnvironmentsPlain(GetEnvironmentsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("powerplatform:index:getEnvironments", TypeShape.of(GetEnvironmentsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists Cloud Flows in a Power Platform environment.
     * 
     */
    public static Output<GetFlowsResult> getFlows(GetFlowsArgs args) {
        return getFlows(args, InvokeOptions.Empty);
    }
    /**
     * Lists Cloud Flows in a Power Platform environment.
     * 
     */
    public static CompletableFuture<GetFlowsResult> getFlowsPlain(GetFlowsPlainArgs args) {
        return getFlowsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Lists Cloud Flows in a Power Platform environment.
     * 
     */
    public static Output<GetFlowsResult> getFlows(GetFlowsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getFlows", TypeShape.of(GetFlowsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists Cloud Flows in a Power Platform environment.
     * 
     */
    public static Output<GetFlowsResult> getFlows(GetFlowsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getFlows", TypeShape.of(GetFlowsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists Cloud Flows in a Power Platform environment.
     * 
     */
    public static CompletableFuture<GetFlowsResult> getFlowsPlain(GetFlowsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("powerplatform:index:getFlows", TypeShape.of(GetFlowsResult.class), args, Utilities.withVersion(options));
    }
}
