// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.powerplatform.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class EnvironmentSummary {
    /**
     * @return The Azure region of the environment.
     * 
     */
    private @Nullable String azureRegion;
    /**
     * @return The Dataverse organization ID.
     * 
     */
    private @Nullable String dataverseId;
    /**
     * @return The display name of the environment.
     * 
     */
    private @Nullable String displayName;
    /**
     * @return The domain name of the Dataverse database.
     * 
     */
    private @Nullable String domainName;
    /**
     * @return The environment group to which this environment belongs.
     * 
     */
    private @Nullable String environmentGroupId;
    /**
     * @return The geographical region of the environment.
     * 
     */
    private @Nullable String geo;
    /**
     * @return The unique identifier of the environment.
     * 
     */
    private @Nullable String id;
    /**
     * @return The security group that controls access.
     * 
     */
    private @Nullable String securityGroupId;
    /**
     * @return The current state of the environment.
     * 
     */
    private @Nullable String state;
    /**
     * @return The tenant that the environment belongs to.
     * 
     */
    private @Nullable String tenantId;
    /**
     * @return The type (SKU) of the environment.
     * 
     */
    private @Nullable String type;
    /**
     * @return The URL of the Dataverse database.
     * 
     */
    private @Nullable String url;
    /**
     * @return The version of the Dataverse database.
     * 
     */
    private @Nullable String version;

    private EnvironmentSummary() {}
    /**
     * @return The Azure region of the environment.
     * 
     */
    public Optional<String> azureRegion() {
        return Optional.ofNullable(this.azureRegion);
    }
    /**
     * @return The Dataverse organization ID.
     * 
     */
    public Optional<String> dataverseId() {
        return Optional.ofNullable(this.dataverseId);
    }
    /**
     * @return The display name of the environment.
     * 
     */
    public Optional<String> displayName() {
        return Optional.ofNullable(this.displayName);
    }
    /**
     * @return The domain name of the Dataverse database.
     * 
     */
    public Optional<String> domainName() {
        return Optional.ofNullable(this.domainName);
    }
    /**
     * @return The environment group to which this environment belongs.
     * 
     */
    public Optional<String> environmentGroupId() {
        return Optional.ofNullable(this.environmentGroupId);
    }
    /**
     * @return The geographical region of the environment.
     * 
     */
    public Optional<String> geo() {
        return Optional.ofNullable(this.geo);
    }
    /**
     * @return The unique identifier of the environment.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    /**
     * @return The security group that controls access.
     * 
     */
    public Optional<String> securityGroupId() {
        return Optional.ofNullable(this.securityGroupId);
    }
    /**
     * @return The current state of the environment.
     * 
     */
    public Optional<String> state() {
        return Optional.ofNullable(this.state);
    }
    /**
     * @return The tenant that the environment belongs to.
     * 
     */
    public Optional<String> tenantId() {
        return Optional.ofNullable(this.tenantId);
    }
    /**
     * @return The type (SKU) of the environment.
     * 
     */
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }
    /**
     * @return The URL of the Dataverse database.
     * 
     */
    public Optional<String> url() {
        return Optional.ofNullable(this.url);
    }
    /**
     * @return The version of the Dataverse database.
     * 
     */
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(EnvironmentSummary defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String azureRegion;
        private @Nullable String dataverseId;
        private @Nullable String displayName;
        private @Nullable String domainName;
        private @Nullable String environmentGroupId;
        private @Nullable String geo;
        private @Nullable String id;
        private @Nullable String securityGroupId;
        private @Nullable String state;
        private @Nullable String tenantId;
        private @Nullable String type;
        private @Nullable String url;
        private @Nullable String version;
        public Builder() {}
        public Builder(EnvironmentSummary defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.azureRegion = defaults.azureRegion;
    	      this.dataverseId = defaults.dataverseId;
    	      this.displayName = defaults.displayName;
    	      this.domainName = defaults.domainName;
    	      this.environmentGroupId = defaults.environmentGroupId;
    	      this.geo = defaults.geo;
    	      this.id = defaults.id;
    	      this.securityGroupId = defaults.securityGroupId;
    	      this.state = defaults.state;
    	      this.tenantId = defaults.tenantId;
    	      this.type = defaults.type;
    	      this.url = defaults.url;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder azureRegion(@Nullable String azureRegion) {

            this.azureRegion = azureRegion;
            return this;
        }
        @CustomType.Setter
        public Builder dataverseId(@Nullable String dataverseId) {

            this.dataverseId = dataverseId;
            return this;
        }
        @CustomType.Setter
        public Builder displayName(@Nullable String displayName) {

            this.displayName = displayName;
            return this;
        }
        @CustomType.Setter
        public Builder domainName(@Nullable String domainName) {

            this.domainName = domainName;
            return this;
        }
        @CustomType.Setter
        public Builder environmentGroupId(@Nullable String environmentGroupId) {

            this.environmentGroupId = environmentGroupId;
            return this;
        }
        @CustomType.Setter
        public Builder geo(@Nullable String geo) {

            this.geo = geo;
            return this;
        }
        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder securityGroupId(@Nullable String securityGroupId) {

            this.securityGroupId = securityGroupId;
            return this;
        }
        @CustomType.Setter
        public Builder state(@Nullable String state) {

            this.state = state;
            return this;
        }
        @CustomType.Setter
        public Builder tenantId(@Nullable String tenantId) {

            this.tenantId = tenantId;
            return this;
        }
        @CustomType.Setter
        public Builder type(@Nullable String type) {

            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder url(@Nullable String url) {

            this.url = url;
            return this;
        }
        @CustomType.Setter
        public Builder version(@Nullable String version) {

            this.version = version;
            return this;
        }
        public EnvironmentSummary build() {
            final var _resultValue = new EnvironmentSummary();
            _resultValue.azureRegion = azureRegion;
            _resultValue.dataverseId = dataverseId;
            _resultValue.displayName = displayName;
            _resultValue.domainName = domainName;
            _resultValue.environmentGroupId = environmentGroupId;
            _resultValue.geo = geo;
            _resultValue.id = id;
            _resultValue.securityGroupId = securityGroupId;
            _resultValue.state = state;
            _resultValue.tenantId = tenantId;
            _resultValue.type = type;
            _resultValue.url = url;
            _resultValue.version = version;
            return _resultValue;
        }
    }
}
