// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.powerplatform.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.powerplatform.outputs.FlowSummary;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetFlowsResult {
    /**
     * @return The list of Cloud Flows.
     * 
     */
    private List<FlowSummary> flows;

    private GetFlowsResult() {}
    /**
     * @return The list of Cloud Flows.
     * 
     */
    public List<FlowSummary> flows() {
        return this.flows;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetFlowsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<FlowSummary> flows;
        public Builder() {}
        public Builder(GetFlowsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.flows = defaults.flows;
        }

        @CustomType.Setter
        public Builder flows(List<FlowSummary> flows) {
            if (flows == null) {
              throw new MissingRequiredPropertyException("GetFlowsResult", "flows");
            }
            this.flows = flows;
            return this;
        }
        public Builder flows(FlowSummary... flows) {
            return flows(List.of(flows));
        }
        public GetFlowsResult build() {
            final var _resultValue = new GetFlowsResult();
            _resultValue.flows = flows;
            return _resultValue;
        }
    }
}
