// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.github.rpothin.powerplatform.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetAppsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAppsPlainArgs Empty = new GetAppsPlainArgs();

    /**
     * The ID of the environment to list apps for.
     * 
     */
    @Import(name="environmentId", required=true)
    private String environmentId;

    /**
     * @return The ID of the environment to list apps for.
     * 
     */
    public String environmentId() {
        return this.environmentId;
    }

    private GetAppsPlainArgs() {}

    private GetAppsPlainArgs(GetAppsPlainArgs $) {
        this.environmentId = $.environmentId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAppsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAppsPlainArgs $;

        public Builder() {
            $ = new GetAppsPlainArgs();
        }

        public Builder(GetAppsPlainArgs defaults) {
            $ = new GetAppsPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param environmentId The ID of the environment to list apps for.
         * 
         * @return builder
         * 
         */
        public Builder environmentId(String environmentId) {
            $.environmentId = environmentId;
            return this;
        }

        public GetAppsPlainArgs build() {
            if ($.environmentId == null) {
                throw new MissingRequiredPropertyException("GetAppsPlainArgs", "environmentId");
            }
            return $;
        }
    }

}
