// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package powerplatform

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rpothin/pulumi-powerplatform/sdk/go/powerplatform/internal"
)

// Creates a manual backup of a Power Platform environment. Backups are immutable — any change to inputs triggers replacement.
type EnvironmentBackup struct {
	pulumi.CustomResourceState

	// The date and time when the backup expires.
	BackupExpiryDateTime pulumi.StringPtrOutput `pulumi:"backupExpiryDateTime"`
	// The date and time when the backup was created.
	BackupPointDateTime pulumi.StringPtrOutput `pulumi:"backupPointDateTime"`
	// The ID of the backed-up environment.
	EnvironmentId pulumi.StringOutput `pulumi:"environmentId"`
	// The label for the backup.
	Label pulumi.StringOutput `pulumi:"label"`
}

// NewEnvironmentBackup registers a new resource with the given unique name, arguments, and options.
func NewEnvironmentBackup(ctx *pulumi.Context,
	name string, args *EnvironmentBackupArgs, opts ...pulumi.ResourceOption) (*EnvironmentBackup, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EnvironmentId == nil {
		return nil, errors.New("invalid value for required argument 'EnvironmentId'")
	}
	if args.Label == nil {
		return nil, errors.New("invalid value for required argument 'Label'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource EnvironmentBackup
	err := ctx.RegisterResource("powerplatform:index:EnvironmentBackup", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEnvironmentBackup gets an existing EnvironmentBackup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEnvironmentBackup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EnvironmentBackupState, opts ...pulumi.ResourceOption) (*EnvironmentBackup, error) {
	var resource EnvironmentBackup
	err := ctx.ReadResource("powerplatform:index:EnvironmentBackup", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering EnvironmentBackup resources.
type environmentBackupState struct {
}

type EnvironmentBackupState struct {
}

func (EnvironmentBackupState) ElementType() reflect.Type {
	return reflect.TypeOf((*environmentBackupState)(nil)).Elem()
}

type environmentBackupArgs struct {
	// The ID of the environment to back up.
	EnvironmentId string `pulumi:"environmentId"`
	// A descriptive label for the backup.
	Label string `pulumi:"label"`
}

// The set of arguments for constructing a EnvironmentBackup resource.
type EnvironmentBackupArgs struct {
	// The ID of the environment to back up.
	EnvironmentId pulumi.StringInput
	// A descriptive label for the backup.
	Label pulumi.StringInput
}

func (EnvironmentBackupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*environmentBackupArgs)(nil)).Elem()
}

type EnvironmentBackupInput interface {
	pulumi.Input

	ToEnvironmentBackupOutput() EnvironmentBackupOutput
	ToEnvironmentBackupOutputWithContext(ctx context.Context) EnvironmentBackupOutput
}

func (*EnvironmentBackup) ElementType() reflect.Type {
	return reflect.TypeOf((**EnvironmentBackup)(nil)).Elem()
}

func (i *EnvironmentBackup) ToEnvironmentBackupOutput() EnvironmentBackupOutput {
	return i.ToEnvironmentBackupOutputWithContext(context.Background())
}

func (i *EnvironmentBackup) ToEnvironmentBackupOutputWithContext(ctx context.Context) EnvironmentBackupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnvironmentBackupOutput)
}

type EnvironmentBackupOutput struct{ *pulumi.OutputState }

func (EnvironmentBackupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EnvironmentBackup)(nil)).Elem()
}

func (o EnvironmentBackupOutput) ToEnvironmentBackupOutput() EnvironmentBackupOutput {
	return o
}

func (o EnvironmentBackupOutput) ToEnvironmentBackupOutputWithContext(ctx context.Context) EnvironmentBackupOutput {
	return o
}

// The date and time when the backup expires.
func (o EnvironmentBackupOutput) BackupExpiryDateTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EnvironmentBackup) pulumi.StringPtrOutput { return v.BackupExpiryDateTime }).(pulumi.StringPtrOutput)
}

// The date and time when the backup was created.
func (o EnvironmentBackupOutput) BackupPointDateTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EnvironmentBackup) pulumi.StringPtrOutput { return v.BackupPointDateTime }).(pulumi.StringPtrOutput)
}

// The ID of the backed-up environment.
func (o EnvironmentBackupOutput) EnvironmentId() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentBackup) pulumi.StringOutput { return v.EnvironmentId }).(pulumi.StringOutput)
}

// The label for the backup.
func (o EnvironmentBackupOutput) Label() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentBackup) pulumi.StringOutput { return v.Label }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EnvironmentBackupInput)(nil)).Elem(), &EnvironmentBackup{})
	pulumi.RegisterOutputType(EnvironmentBackupOutput{})
}
