// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package powerplatform

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rpothin/pulumi-powerplatform/sdk/go/powerplatform/internal"
)

// Lists connectors available in a Power Platform environment.
func GetConnectors(ctx *pulumi.Context, args *GetConnectorsArgs, opts ...pulumi.InvokeOption) (*GetConnectorsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetConnectorsResult
	err := ctx.Invoke("powerplatform:index:getConnectors", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetConnectorsArgs struct {
	// The ID of the environment to list connectors for.
	EnvironmentId string `pulumi:"environmentId"`
}

type GetConnectorsResult struct {
	// The list of connectors.
	Connectors []ConnectorSummary `pulumi:"connectors"`
}

func GetConnectorsOutput(ctx *pulumi.Context, args GetConnectorsOutputArgs, opts ...pulumi.InvokeOption) GetConnectorsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetConnectorsResultOutput, error) {
			args := v.(GetConnectorsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("powerplatform:index:getConnectors", args, GetConnectorsResultOutput{}, options).(GetConnectorsResultOutput), nil
		}).(GetConnectorsResultOutput)
}

type GetConnectorsOutputArgs struct {
	// The ID of the environment to list connectors for.
	EnvironmentId pulumi.StringInput `pulumi:"environmentId"`
}

func (GetConnectorsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetConnectorsArgs)(nil)).Elem()
}

type GetConnectorsResultOutput struct{ *pulumi.OutputState }

func (GetConnectorsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetConnectorsResult)(nil)).Elem()
}

func (o GetConnectorsResultOutput) ToGetConnectorsResultOutput() GetConnectorsResultOutput {
	return o
}

func (o GetConnectorsResultOutput) ToGetConnectorsResultOutputWithContext(ctx context.Context) GetConnectorsResultOutput {
	return o
}

// The list of connectors.
func (o GetConnectorsResultOutput) Connectors() ConnectorSummaryArrayOutput {
	return o.ApplyT(func(v GetConnectorsResult) []ConnectorSummary { return v.Connectors }).(ConnectorSummaryArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetConnectorsResultOutput{})
}
