// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package powerplatform

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rpothin/pulumi-powerplatform/sdk/go/powerplatform/internal"
)

// Queries Dataverse records from a collection using OData filter, select, orderby, top, apply, and expand parameters. Returns the first page of matching records. Use the 'top' parameter to control result count for large tables.
func GetDataRecords(ctx *pulumi.Context, args *GetDataRecordsArgs, opts ...pulumi.InvokeOption) (*GetDataRecordsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDataRecordsResult
	err := ctx.Invoke("powerplatform:index:getDataRecords", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetDataRecordsArgs struct {
	// OData $apply aggregation expression (e.g. "aggregate(revenue with sum as revenue_sum)").
	Apply *string `pulumi:"apply"`
	// The plural OData collection name for the Dataverse table to query (e.g. accounts, deploymentpipelines).
	EntityCollection string `pulumi:"entityCollection"`
	// The GUID of the Power Platform environment containing the Dataverse instance.
	EnvironmentId string `pulumi:"environmentId"`
	// List of navigation properties to expand in the response.
	Expand []DataRecordsExpandParam `pulumi:"expand"`
	// OData $filter expression (e.g. "name eq 'My Pipeline'").
	Filter *string `pulumi:"filter"`
	// OData $orderby expression (e.g. "createdon desc").
	Orderby *string `pulumi:"orderby"`
	// List of column logical names to include in the response.
	Select []string `pulumi:"select"`
	// Maximum number of records to return ($top). Use to limit large result sets.
	Top *int `pulumi:"top"`
}

type GetDataRecordsResult struct {
	// The list of matching Dataverse records. Each record is a map of column name to value.
	Records []interface{} `pulumi:"records"`
	// Total number of records matching the query filter (from @odata.count). Always 0 when the count annotation is absent or when `apply` is used (the count is not available in aggregation mode).
	TotalRowsCount int `pulumi:"totalRowsCount"`
	// True when the total row count exceeded the Dataverse limit (@Microsoft.Dynamics.CRM.totalrecordcountlimitexceeded).
	TotalRowsCountLimitExceeded bool `pulumi:"totalRowsCountLimitExceeded"`
}

func GetDataRecordsOutput(ctx *pulumi.Context, args GetDataRecordsOutputArgs, opts ...pulumi.InvokeOption) GetDataRecordsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDataRecordsResultOutput, error) {
			args := v.(GetDataRecordsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("powerplatform:index:getDataRecords", args, GetDataRecordsResultOutput{}, options).(GetDataRecordsResultOutput), nil
		}).(GetDataRecordsResultOutput)
}

type GetDataRecordsOutputArgs struct {
	// OData $apply aggregation expression (e.g. "aggregate(revenue with sum as revenue_sum)").
	Apply pulumi.StringPtrInput `pulumi:"apply"`
	// The plural OData collection name for the Dataverse table to query (e.g. accounts, deploymentpipelines).
	EntityCollection pulumi.StringInput `pulumi:"entityCollection"`
	// The GUID of the Power Platform environment containing the Dataverse instance.
	EnvironmentId pulumi.StringInput `pulumi:"environmentId"`
	// List of navigation properties to expand in the response.
	Expand DataRecordsExpandParamArrayInput `pulumi:"expand"`
	// OData $filter expression (e.g. "name eq 'My Pipeline'").
	Filter pulumi.StringPtrInput `pulumi:"filter"`
	// OData $orderby expression (e.g. "createdon desc").
	Orderby pulumi.StringPtrInput `pulumi:"orderby"`
	// List of column logical names to include in the response.
	Select pulumi.StringArrayInput `pulumi:"select"`
	// Maximum number of records to return ($top). Use to limit large result sets.
	Top pulumi.IntPtrInput `pulumi:"top"`
}

func (GetDataRecordsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDataRecordsArgs)(nil)).Elem()
}

type GetDataRecordsResultOutput struct{ *pulumi.OutputState }

func (GetDataRecordsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDataRecordsResult)(nil)).Elem()
}

func (o GetDataRecordsResultOutput) ToGetDataRecordsResultOutput() GetDataRecordsResultOutput {
	return o
}

func (o GetDataRecordsResultOutput) ToGetDataRecordsResultOutputWithContext(ctx context.Context) GetDataRecordsResultOutput {
	return o
}

// The list of matching Dataverse records. Each record is a map of column name to value.
func (o GetDataRecordsResultOutput) Records() pulumi.ArrayOutput {
	return o.ApplyT(func(v GetDataRecordsResult) []interface{} { return v.Records }).(pulumi.ArrayOutput)
}

// Total number of records matching the query filter (from @odata.count). Always 0 when the count annotation is absent or when `apply` is used (the count is not available in aggregation mode).
func (o GetDataRecordsResultOutput) TotalRowsCount() pulumi.IntOutput {
	return o.ApplyT(func(v GetDataRecordsResult) int { return v.TotalRowsCount }).(pulumi.IntOutput)
}

// True when the total row count exceeded the Dataverse limit (@Microsoft.Dynamics.CRM.totalrecordcountlimitexceeded).
func (o GetDataRecordsResultOutput) TotalRowsCountLimitExceeded() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDataRecordsResult) bool { return v.TotalRowsCountLimitExceeded }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDataRecordsResultOutput{})
}
