// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Components
{
    /// <summary>
    /// AVM-aligned component that manages a Power Platform deployment pipeline lifecycle.
    /// </summary>
    [PowerplatformResourceType("powerplatform:components:ResDeploymentPipeline")]
    public partial class ResDeploymentPipeline : global::Pulumi.ComponentResource
    {
        [Output("deploymentEnvironmentIds")]
        public Output<ImmutableDictionary<string, string>> DeploymentEnvironmentIds { get; private set; } = null!;

        [Output("deploymentStageIds")]
        public Output<ImmutableDictionary<string, string>> DeploymentStageIds { get; private set; } = null!;

        [Output("pipelineId")]
        public Output<string> PipelineId { get; private set; } = null!;

        [Output("pipelineName")]
        public Output<string> PipelineName { get; private set; } = null!;

        [Output("pipelineTeamId")]
        public Output<string> PipelineTeamId { get; private set; } = null!;

        [Output("resourceId")]
        public Output<string> ResourceId { get; private set; } = null!;


        /// <summary>
        /// Create a ResDeploymentPipeline resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ResDeploymentPipeline(string name, ResDeploymentPipelineArgs args, ComponentResourceOptions? options = null)
            : base("powerplatform:components:ResDeploymentPipeline", name, args ?? new ResDeploymentPipelineArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/rpothin",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ResDeploymentPipelineArgs : global::Pulumi.ResourceArgs
    {
        [Input("deploymentPipelineUserRoleId")]
        public string? DeploymentPipelineUserRoleId { get; set; }

        [Input("devEnvironmentKey", required: true)]
        public string DevEnvironmentKey { get; set; } = null!;

        [Input("enableAiDeploymentNotes")]
        public bool? EnableAiDeploymentNotes { get; set; }

        [Input("enableRedeployment")]
        public bool? EnableRedeployment { get; set; }

        [Input("enableTelemetry")]
        public bool? EnableTelemetry { get; set; }

        [Input("environments", required: true)]
        private Dictionary<string, Inputs.PipelineEnvironmentEntryArgs>? _environments;
        public Dictionary<string, Inputs.PipelineEnvironmentEntryArgs> Environments
        {
            get => _environments ?? (_environments = new Dictionary<string, Inputs.PipelineEnvironmentEntryArgs>());
            set => _environments = value;
        }

        [Input("hostEnvironmentId", required: true)]
        public string HostEnvironmentId { get; set; } = null!;

        [Input("lifecycleState")]
        public string? LifecycleState { get; set; }

        [Input("pipelineDescription")]
        public string? PipelineDescription { get; set; }

        [Input("pipelineName", required: true)]
        public string PipelineName { get; set; } = null!;

        [Input("pipelineStages", required: true)]
        private List<Inputs.PipelineStageConfigArgs>? _pipelineStages;
        public List<Inputs.PipelineStageConfigArgs> PipelineStages
        {
            get => _pipelineStages ?? (_pipelineStages = new List<Inputs.PipelineStageConfigArgs>());
            set => _pipelineStages = value;
        }

        [Input("rootBusinessUnitId")]
        public string? RootBusinessUnitId { get; set; }

        [Input("securityGroupId")]
        public string? SecurityGroupId { get; set; }

        public ResDeploymentPipelineArgs()
        {
        }
        public static new ResDeploymentPipelineArgs Empty => new ResDeploymentPipelineArgs();
    }
}
