// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Components
{
    /// <summary>
    /// AVM-aligned Pulumi component for Power Platform Tenant Settings.
    /// 
    ///     Composes a single ``powerplatform:components:TenantSettings`` child resource
    ///     with an opinionated, AVM-compatible interface.
    ///     
    ///     .. important::
    ///         ``TenantSettings`` is a singleton resource — only one exists per AAD
    ///         tenant.  Assign ownership of this component to a single, dedicated
    ///         infrastructure stack to avoid conflicts.
    ///     
    ///     Example (Python)::
    ///     
    ///         import rpothin_powerplatform as pp
    ///     
    ///         tenant_cfg = pp.components.ResTenantSettings(
    ///             "tenant-settings",
    ///             pp.components.ResTenantSettingsArgs(
    ///                 disable_environment_creation_by_non_admin_users=True,
    ///                 disable_trial_environment_creation_by_non_admin_users=True,
    ///             ),
    ///         )
    /// </summary>
    [PowerplatformResourceType("powerplatform:components:ResTenantSettings")]
    public partial class ResTenantSettings : global::Pulumi.ComponentResource
    {
        [Output("resourceId")]
        public Output<string> ResourceId { get; private set; } = null!;

        [Output("tenantId")]
        public Output<string> TenantId { get; private set; } = null!;


        /// <summary>
        /// Create a ResTenantSettings resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ResTenantSettings(string name, ResTenantSettingsArgs? args = null, ComponentResourceOptions? options = null)
            : base("powerplatform:components:ResTenantSettings", name, args ?? new ResTenantSettingsArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/rpothin",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ResTenantSettingsArgs : global::Pulumi.ResourceArgs
    {
        [Input("disableCapacityAllocationByEnvironmentAdmins")]
        public bool? DisableCapacityAllocationByEnvironmentAdmins { get; set; }

        [Input("disableEnvironmentCreationByNonAdminUsers")]
        public bool? DisableEnvironmentCreationByNonAdminUsers { get; set; }

        [Input("disableNewsletterSendout")]
        public bool? DisableNewsletterSendout { get; set; }

        [Input("disableNpsCommentsReachout")]
        public bool? DisableNpsCommentsReachout { get; set; }

        [Input("disablePortalsCreationByNonAdminUsers")]
        public bool? DisablePortalsCreationByNonAdminUsers { get; set; }

        [Input("disableSupportTicketsVisibleByAllUsers")]
        public bool? DisableSupportTicketsVisibleByAllUsers { get; set; }

        [Input("disableSurveyFeedback")]
        public bool? DisableSurveyFeedback { get; set; }

        [Input("disableTrialEnvironmentCreationByNonAdminUsers")]
        public bool? DisableTrialEnvironmentCreationByNonAdminUsers { get; set; }

        [Input("enableTelemetry")]
        public bool? EnableTelemetry { get; set; }

        [Input("powerPlatform")]
        private Dictionary<string, object>? _powerPlatform;
        public Dictionary<string, object> PowerPlatform
        {
            get => _powerPlatform ?? (_powerPlatform = new Dictionary<string, object>());
            set => _powerPlatform = value;
        }

        [Input("walkMeOptOut")]
        public bool? WalkMeOptOut { get; set; }

        public ResTenantSettingsArgs()
        {
        }
        public static new ResTenantSettingsArgs Empty => new ResTenantSettingsArgs();
    }
}
