// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a Power Platform environment group. Environment groups allow you to organize environments and apply policies at a group level.
 */
export class EnvironmentGroup extends pulumi.CustomResource {
    /**
     * Get an existing EnvironmentGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): EnvironmentGroup {
        return new EnvironmentGroup(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'powerplatform:index:EnvironmentGroup';

    /**
     * Returns true if the given object is an instance of EnvironmentGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EnvironmentGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EnvironmentGroup.__pulumiType;
    }

    /**
     * The timestamp when the group was created.
     */
    declare public /*out*/ readonly createdTime: pulumi.Output<string | undefined>;
    /**
     * The description of the environment group.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The display name of the environment group.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * The timestamp when the group was last modified.
     */
    declare public /*out*/ readonly lastModifiedTime: pulumi.Output<string | undefined>;
    /**
     * The ID of the parent environment group.
     */
    declare public readonly parentGroupId: pulumi.Output<string | undefined>;

    /**
     * Create a EnvironmentGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EnvironmentGroupArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["parentGroupId"] = args?.parentGroupId;
            resourceInputs["createdTime"] = undefined /*out*/;
            resourceInputs["lastModifiedTime"] = undefined /*out*/;
        } else {
            resourceInputs["createdTime"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["displayName"] = undefined /*out*/;
            resourceInputs["lastModifiedTime"] = undefined /*out*/;
            resourceInputs["parentGroupId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EnvironmentGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a EnvironmentGroup resource.
 */
export interface EnvironmentGroupArgs {
    /**
     * A description of the environment group.
     */
    description?: pulumi.Input<string>;
    /**
     * The display name for the environment group.
     */
    displayName: pulumi.Input<string>;
    /**
     * The ID of the parent environment group, if this is a nested group.
     */
    parentGroupId?: pulumi.Input<string>;
}
