// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Outputs
{

    /// <summary>
    /// Summary information about a Power Platform connector.
    /// </summary>
    [OutputType]
    public sealed class ConnectorSummary
    {
        /// <summary>
        /// The display name of the connector.
        /// </summary>
        public readonly string? DisplayName;
        /// <summary>
        /// The unique identifier of the connector.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The internal name of the connector.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The type of the connector.
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private ConnectorSummary(
            string? displayName,

            string? id,

            string? name,

            string? type)
        {
            DisplayName = displayName;
            Id = id;
            Name = name;
            Type = type;
        }
    }
}
