// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Outputs
{

    /// <summary>
    /// Power Pages settings.
    /// </summary>
    [OutputType]
    public sealed class TenantPowerPagesSettings
    {
        [OutputConstructor]
        private TenantPowerPagesSettings()
        {
        }
    }
}
