// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Outputs
{

    /// <summary>
    /// Teams integration settings.
    /// </summary>
    [OutputType]
    public sealed class TenantTeamsIntegrationSettings
    {
        /// <summary>
        /// Share with colleagues user limit.
        /// </summary>
        public readonly int? ShareWithColleaguesUserLimit;

        [OutputConstructor]
        private TenantTeamsIntegrationSettings(int? shareWithColleaguesUserLimit)
        {
            ShareWithColleaguesUserLimit = shareWithColleaguesUserLimit;
        }
    }
}
