// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Outputs
{

    /// <summary>
    /// Intelligence settings.
    /// </summary>
    [OutputType]
    public sealed class TenantIntelligenceSettings
    {
        /// <summary>
        /// Disable Copilot.
        /// </summary>
        public readonly bool? DisableCopilot;
        /// <summary>
        /// Enable OpenAI bot publishing.
        /// </summary>
        public readonly bool? EnableOpenAiBotPublishing;

        [OutputConstructor]
        private TenantIntelligenceSettings(
            bool? disableCopilot,

            bool? enableOpenAiBotPublishing)
        {
            DisableCopilot = disableCopilot;
            EnableOpenAiBotPublishing = enableOpenAiBotPublishing;
        }
    }
}
