// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.powerplatform;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.powerplatform.BillingPolicyArgs;
import com.pulumi.powerplatform.Utilities;
import com.pulumi.powerplatform.outputs.BillingInstrument;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a Power Platform billing policy. Billing policies control pay-as-you-go billing for Power Platform environments.
 * 
 */
@ResourceType(type="powerplatform:index:BillingPolicy")
public class BillingPolicy extends com.pulumi.resources.CustomResource {
    /**
     * The billing instrument details.
     * 
     */
    @Export(name="billingInstrument", refs={BillingInstrument.class}, tree="[0]")
    private Output</* @Nullable */ BillingInstrument> billingInstrument;

    /**
     * @return The billing instrument details.
     * 
     */
    public Output<Optional<BillingInstrument>> billingInstrument() {
        return Codegen.optional(this.billingInstrument);
    }
    /**
     * The timestamp when the billing policy was created.
     * 
     */
    @Export(name="createdOn", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> createdOn;

    /**
     * @return The timestamp when the billing policy was created.
     * 
     */
    public Output<Optional<String>> createdOn() {
        return Codegen.optional(this.createdOn);
    }
    /**
     * The timestamp when the billing policy was last modified.
     * 
     */
    @Export(name="lastModifiedOn", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastModifiedOn;

    /**
     * @return The timestamp when the billing policy was last modified.
     * 
     */
    public Output<Optional<String>> lastModifiedOn() {
        return Codegen.optional(this.lastModifiedOn);
    }
    /**
     * The geographic location of the billing policy.
     * 
     */
    @Export(name="location", refs={String.class}, tree="[0]")
    private Output<String> location;

    /**
     * @return The geographic location of the billing policy.
     * 
     */
    public Output<String> location() {
        return this.location;
    }
    /**
     * The name of the billing policy.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the billing policy.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The status of the billing policy.
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> status;

    /**
     * @return The status of the billing policy.
     * 
     */
    public Output<Optional<String>> status() {
        return Codegen.optional(this.status);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public BillingPolicy(java.lang.String name) {
        this(name, BillingPolicyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public BillingPolicy(java.lang.String name, BillingPolicyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public BillingPolicy(java.lang.String name, BillingPolicyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("powerplatform:index:BillingPolicy", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private BillingPolicy(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("powerplatform:index:BillingPolicy", name, null, makeResourceOptions(options, id), false);
    }

    private static BillingPolicyArgs makeArgs(BillingPolicyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? BillingPolicyArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/rpothin")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static BillingPolicy get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new BillingPolicy(name, id, options);
    }
}
