// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package powerplatform

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rpothin/pulumi-powerplatform/sdk/go/powerplatform/internal"
)

// Manages a Power Platform billing policy. Billing policies control pay-as-you-go billing for Power Platform environments.
type BillingPolicy struct {
	pulumi.CustomResourceState

	// The billing instrument details.
	BillingInstrument BillingInstrumentPtrOutput `pulumi:"billingInstrument"`
	// The timestamp when the billing policy was created.
	CreatedOn pulumi.StringPtrOutput `pulumi:"createdOn"`
	// The timestamp when the billing policy was last modified.
	LastModifiedOn pulumi.StringPtrOutput `pulumi:"lastModifiedOn"`
	// The geographic location of the billing policy.
	Location pulumi.StringOutput `pulumi:"location"`
	// The name of the billing policy.
	Name pulumi.StringOutput `pulumi:"name"`
	// The status of the billing policy.
	Status pulumi.StringPtrOutput `pulumi:"status"`
}

// NewBillingPolicy registers a new resource with the given unique name, arguments, and options.
func NewBillingPolicy(ctx *pulumi.Context,
	name string, args *BillingPolicyArgs, opts ...pulumi.ResourceOption) (*BillingPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Location == nil {
		return nil, errors.New("invalid value for required argument 'Location'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource BillingPolicy
	err := ctx.RegisterResource("powerplatform:index:BillingPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBillingPolicy gets an existing BillingPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBillingPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BillingPolicyState, opts ...pulumi.ResourceOption) (*BillingPolicy, error) {
	var resource BillingPolicy
	err := ctx.ReadResource("powerplatform:index:BillingPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering BillingPolicy resources.
type billingPolicyState struct {
}

type BillingPolicyState struct {
}

func (BillingPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*billingPolicyState)(nil)).Elem()
}

type billingPolicyArgs struct {
	// The billing instrument (Azure subscription) details.
	BillingInstrument *BillingInstrument `pulumi:"billingInstrument"`
	// The geographic location for the billing policy (e.g., unitedstates, europe).
	Location string `pulumi:"location"`
	// The name of the billing policy.
	Name string `pulumi:"name"`
	// The status of the billing policy: Enabled or Disabled.
	Status *string `pulumi:"status"`
}

// The set of arguments for constructing a BillingPolicy resource.
type BillingPolicyArgs struct {
	// The billing instrument (Azure subscription) details.
	BillingInstrument BillingInstrumentPtrInput
	// The geographic location for the billing policy (e.g., unitedstates, europe).
	Location pulumi.StringInput
	// The name of the billing policy.
	Name pulumi.StringInput
	// The status of the billing policy: Enabled or Disabled.
	Status pulumi.StringPtrInput
}

func (BillingPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*billingPolicyArgs)(nil)).Elem()
}

type BillingPolicyInput interface {
	pulumi.Input

	ToBillingPolicyOutput() BillingPolicyOutput
	ToBillingPolicyOutputWithContext(ctx context.Context) BillingPolicyOutput
}

func (*BillingPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**BillingPolicy)(nil)).Elem()
}

func (i *BillingPolicy) ToBillingPolicyOutput() BillingPolicyOutput {
	return i.ToBillingPolicyOutputWithContext(context.Background())
}

func (i *BillingPolicy) ToBillingPolicyOutputWithContext(ctx context.Context) BillingPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BillingPolicyOutput)
}

type BillingPolicyOutput struct{ *pulumi.OutputState }

func (BillingPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BillingPolicy)(nil)).Elem()
}

func (o BillingPolicyOutput) ToBillingPolicyOutput() BillingPolicyOutput {
	return o
}

func (o BillingPolicyOutput) ToBillingPolicyOutputWithContext(ctx context.Context) BillingPolicyOutput {
	return o
}

// The billing instrument details.
func (o BillingPolicyOutput) BillingInstrument() BillingInstrumentPtrOutput {
	return o.ApplyT(func(v *BillingPolicy) BillingInstrumentPtrOutput { return v.BillingInstrument }).(BillingInstrumentPtrOutput)
}

// The timestamp when the billing policy was created.
func (o BillingPolicyOutput) CreatedOn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BillingPolicy) pulumi.StringPtrOutput { return v.CreatedOn }).(pulumi.StringPtrOutput)
}

// The timestamp when the billing policy was last modified.
func (o BillingPolicyOutput) LastModifiedOn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BillingPolicy) pulumi.StringPtrOutput { return v.LastModifiedOn }).(pulumi.StringPtrOutput)
}

// The geographic location of the billing policy.
func (o BillingPolicyOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v *BillingPolicy) pulumi.StringOutput { return v.Location }).(pulumi.StringOutput)
}

// The name of the billing policy.
func (o BillingPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *BillingPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The status of the billing policy.
func (o BillingPolicyOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BillingPolicy) pulumi.StringPtrOutput { return v.Status }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BillingPolicyInput)(nil)).Elem(), &BillingPolicy{})
	pulumi.RegisterOutputType(BillingPolicyOutput{})
}
