// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package powerplatform

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rpothin/pulumi-powerplatform/sdk/go/powerplatform/internal"
)

// Manages a Power Platform Data Loss Prevention (DLP) policy. DLP policies define rules to control how connectors can share data. Note: Deletion removes all rule sets from the policy, as the SDK does not expose a direct policy delete endpoint.
type DlpPolicy struct {
	pulumi.CustomResourceState

	// The timestamp when the policy was last modified.
	LastModified pulumi.StringPtrOutput `pulumi:"lastModified"`
	// The name of the DLP policy.
	Name pulumi.StringOutput `pulumi:"name"`
	// The number of rule sets in the policy.
	RuleSetCount pulumi.IntPtrOutput `pulumi:"ruleSetCount"`
	// The rule sets that define the DLP policy rules.
	RuleSets RuleSetArrayOutput `pulumi:"ruleSets"`
	// The tenant ID that owns the policy.
	TenantId pulumi.StringPtrOutput `pulumi:"tenantId"`
}

// NewDlpPolicy registers a new resource with the given unique name, arguments, and options.
func NewDlpPolicy(ctx *pulumi.Context,
	name string, args *DlpPolicyArgs, opts ...pulumi.ResourceOption) (*DlpPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DlpPolicy
	err := ctx.RegisterResource("powerplatform:index:DlpPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDlpPolicy gets an existing DlpPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDlpPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DlpPolicyState, opts ...pulumi.ResourceOption) (*DlpPolicy, error) {
	var resource DlpPolicy
	err := ctx.ReadResource("powerplatform:index:DlpPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DlpPolicy resources.
type dlpPolicyState struct {
}

type DlpPolicyState struct {
}

func (DlpPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*dlpPolicyState)(nil)).Elem()
}

type dlpPolicyArgs struct {
	// The name of the DLP policy.
	Name string `pulumi:"name"`
	// The rule sets that define the DLP policy rules.
	RuleSets []RuleSet `pulumi:"ruleSets"`
}

// The set of arguments for constructing a DlpPolicy resource.
type DlpPolicyArgs struct {
	// The name of the DLP policy.
	Name pulumi.StringInput
	// The rule sets that define the DLP policy rules.
	RuleSets RuleSetArrayInput
}

func (DlpPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dlpPolicyArgs)(nil)).Elem()
}

type DlpPolicyInput interface {
	pulumi.Input

	ToDlpPolicyOutput() DlpPolicyOutput
	ToDlpPolicyOutputWithContext(ctx context.Context) DlpPolicyOutput
}

func (*DlpPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**DlpPolicy)(nil)).Elem()
}

func (i *DlpPolicy) ToDlpPolicyOutput() DlpPolicyOutput {
	return i.ToDlpPolicyOutputWithContext(context.Background())
}

func (i *DlpPolicy) ToDlpPolicyOutputWithContext(ctx context.Context) DlpPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DlpPolicyOutput)
}

type DlpPolicyOutput struct{ *pulumi.OutputState }

func (DlpPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DlpPolicy)(nil)).Elem()
}

func (o DlpPolicyOutput) ToDlpPolicyOutput() DlpPolicyOutput {
	return o
}

func (o DlpPolicyOutput) ToDlpPolicyOutputWithContext(ctx context.Context) DlpPolicyOutput {
	return o
}

// The timestamp when the policy was last modified.
func (o DlpPolicyOutput) LastModified() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DlpPolicy) pulumi.StringPtrOutput { return v.LastModified }).(pulumi.StringPtrOutput)
}

// The name of the DLP policy.
func (o DlpPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *DlpPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The number of rule sets in the policy.
func (o DlpPolicyOutput) RuleSetCount() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DlpPolicy) pulumi.IntPtrOutput { return v.RuleSetCount }).(pulumi.IntPtrOutput)
}

// The rule sets that define the DLP policy rules.
func (o DlpPolicyOutput) RuleSets() RuleSetArrayOutput {
	return o.ApplyT(func(v *DlpPolicy) RuleSetArrayOutput { return v.RuleSets }).(RuleSetArrayOutput)
}

// The tenant ID that owns the policy.
func (o DlpPolicyOutput) TenantId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DlpPolicy) pulumi.StringPtrOutput { return v.TenantId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DlpPolicyInput)(nil)).Elem(), &DlpPolicy{})
	pulumi.RegisterOutputType(DlpPolicyOutput{})
}
