// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package powerplatform

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rpothin/pulumi-powerplatform/sdk/go/powerplatform/internal"
)

// Manages a Power Platform environment. Environments are containers for apps, flows, data, and other resources. Uses the BAP admin REST API for lifecycle management.
type Environment struct {
	pulumi.CustomResourceState

	// Whether Bing Search integration is allowed.
	AllowBingSearch pulumi.BoolPtrOutput `pulumi:"allowBingSearch"`
	// Whether data can move across geographic boundaries for Copilot features.
	AllowMovingDataAcrossRegions pulumi.BoolPtrOutput `pulumi:"allowMovingDataAcrossRegions"`
	// Specific Azure region within the location geo.
	AzureRegion pulumi.StringPtrOutput `pulumi:"azureRegion"`
	// ID of the billing policy linked to this environment.
	BillingPolicyId pulumi.StringPtrOutput `pulumi:"billingPolicyId"`
	// Release wave cadence: Frequent or Moderate.
	Cadence pulumi.StringPtrOutput `pulumi:"cadence"`
	// The timestamp when the environment was created.
	CreatedTime pulumi.StringPtrOutput `pulumi:"createdTime"`
	// Dataverse database configuration. Presence triggers Dataverse provisioning.
	Dataverse DataversePtrOutput `pulumi:"dataverse"`
	// The description of the environment.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The display name of the environment.
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// Enterprise policies associated with the environment.
	EnterprisePolicies EnterprisePolicyArrayOutput `pulumi:"enterprisePolicies"`
	// ID of the environment group.
	EnvironmentGroupId pulumi.StringPtrOutput `pulumi:"environmentGroupId"`
	// The type (SKU) of the environment.
	EnvironmentType pulumi.StringOutput `pulumi:"environmentType"`
	// The timestamp when the environment was last modified.
	LastModifiedTime pulumi.StringPtrOutput `pulumi:"lastModifiedTime"`
	// GUID of the linked app.
	LinkedAppId pulumi.StringPtrOutput `pulumi:"linkedAppId"`
	// Type of linked app: Canvas or ModelDriven.
	LinkedAppType pulumi.StringPtrOutput `pulumi:"linkedAppType"`
	// URL of the linked app. Computed.
	LinkedAppUrl pulumi.StringPtrOutput `pulumi:"linkedAppUrl"`
	// The geographic region of the environment.
	Location pulumi.StringOutput `pulumi:"location"`
	// AAD user or group GUID who owns the environment.
	OwnerId pulumi.StringPtrOutput `pulumi:"ownerId"`
	// The current state of the environment (e.g., Ready, Preparing).
	State pulumi.StringPtrOutput `pulumi:"state"`
}

// NewEnvironment registers a new resource with the given unique name, arguments, and options.
func NewEnvironment(ctx *pulumi.Context,
	name string, args *EnvironmentArgs, opts ...pulumi.ResourceOption) (*Environment, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DisplayName == nil {
		return nil, errors.New("invalid value for required argument 'DisplayName'")
	}
	if args.EnvironmentType == nil {
		return nil, errors.New("invalid value for required argument 'EnvironmentType'")
	}
	if args.Location == nil {
		return nil, errors.New("invalid value for required argument 'Location'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Environment
	err := ctx.RegisterResource("powerplatform:index:Environment", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEnvironment gets an existing Environment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEnvironment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EnvironmentState, opts ...pulumi.ResourceOption) (*Environment, error) {
	var resource Environment
	err := ctx.ReadResource("powerplatform:index:Environment", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Environment resources.
type environmentState struct {
}

type EnvironmentState struct {
}

func (EnvironmentState) ElementType() reflect.Type {
	return reflect.TypeOf((*environmentState)(nil)).Elem()
}

type environmentArgs struct {
	// Allow Bing Search integration (AI generative features).
	AllowBingSearch *bool `pulumi:"allowBingSearch"`
	// Allow data to move across geographic boundaries for Copilot features.
	AllowMovingDataAcrossRegions *bool `pulumi:"allowMovingDataAcrossRegions"`
	// Specific Azure region within the location geo (e.g. westus2). Immutable after creation.
	AzureRegion *string `pulumi:"azureRegion"`
	// ID of the billing policy to link to this environment.
	BillingPolicyId *string `pulumi:"billingPolicyId"`
	// Release wave cadence: Frequent or Moderate. Immutable after creation.
	Cadence *string `pulumi:"cadence"`
	// Dataverse database configuration. Presence triggers Dataverse provisioning.
	Dataverse *Dataverse `pulumi:"dataverse"`
	// A description of the environment.
	Description *string `pulumi:"description"`
	// The display name of the environment.
	DisplayName string `pulumi:"displayName"`
	// Set of enterprise policies associated with the environment.
	EnterprisePolicies []EnterprisePolicy `pulumi:"enterprisePolicies"`
	// ID of the environment group this environment belongs to.
	EnvironmentGroupId *string `pulumi:"environmentGroupId"`
	// The type (SKU) of the environment: Sandbox, Production, Trial, Developer, or Default. Immutable after creation.
	EnvironmentType string `pulumi:"environmentType"`
	// GUID of the linked app.
	LinkedAppId *string `pulumi:"linkedAppId"`
	// Type of linked app: Canvas or ModelDriven.
	LinkedAppType *string `pulumi:"linkedAppType"`
	// The geographic region for the environment (e.g., unitedstates, europe). Immutable after creation.
	Location string `pulumi:"location"`
	// AAD user or group GUID who owns the environment. Only valid for Developer environments.
	OwnerId *string `pulumi:"ownerId"`
}

// The set of arguments for constructing a Environment resource.
type EnvironmentArgs struct {
	// Allow Bing Search integration (AI generative features).
	AllowBingSearch pulumi.BoolPtrInput
	// Allow data to move across geographic boundaries for Copilot features.
	AllowMovingDataAcrossRegions pulumi.BoolPtrInput
	// Specific Azure region within the location geo (e.g. westus2). Immutable after creation.
	AzureRegion pulumi.StringPtrInput
	// ID of the billing policy to link to this environment.
	BillingPolicyId pulumi.StringPtrInput
	// Release wave cadence: Frequent or Moderate. Immutable after creation.
	Cadence pulumi.StringPtrInput
	// Dataverse database configuration. Presence triggers Dataverse provisioning.
	Dataverse DataversePtrInput
	// A description of the environment.
	Description pulumi.StringPtrInput
	// The display name of the environment.
	DisplayName pulumi.StringInput
	// Set of enterprise policies associated with the environment.
	EnterprisePolicies EnterprisePolicyArrayInput
	// ID of the environment group this environment belongs to.
	EnvironmentGroupId pulumi.StringPtrInput
	// The type (SKU) of the environment: Sandbox, Production, Trial, Developer, or Default. Immutable after creation.
	EnvironmentType pulumi.StringInput
	// GUID of the linked app.
	LinkedAppId pulumi.StringPtrInput
	// Type of linked app: Canvas or ModelDriven.
	LinkedAppType pulumi.StringPtrInput
	// The geographic region for the environment (e.g., unitedstates, europe). Immutable after creation.
	Location pulumi.StringInput
	// AAD user or group GUID who owns the environment. Only valid for Developer environments.
	OwnerId pulumi.StringPtrInput
}

func (EnvironmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*environmentArgs)(nil)).Elem()
}

type EnvironmentInput interface {
	pulumi.Input

	ToEnvironmentOutput() EnvironmentOutput
	ToEnvironmentOutputWithContext(ctx context.Context) EnvironmentOutput
}

func (*Environment) ElementType() reflect.Type {
	return reflect.TypeOf((**Environment)(nil)).Elem()
}

func (i *Environment) ToEnvironmentOutput() EnvironmentOutput {
	return i.ToEnvironmentOutputWithContext(context.Background())
}

func (i *Environment) ToEnvironmentOutputWithContext(ctx context.Context) EnvironmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnvironmentOutput)
}

type EnvironmentOutput struct{ *pulumi.OutputState }

func (EnvironmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Environment)(nil)).Elem()
}

func (o EnvironmentOutput) ToEnvironmentOutput() EnvironmentOutput {
	return o
}

func (o EnvironmentOutput) ToEnvironmentOutputWithContext(ctx context.Context) EnvironmentOutput {
	return o
}

// Whether Bing Search integration is allowed.
func (o EnvironmentOutput) AllowBingSearch() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.BoolPtrOutput { return v.AllowBingSearch }).(pulumi.BoolPtrOutput)
}

// Whether data can move across geographic boundaries for Copilot features.
func (o EnvironmentOutput) AllowMovingDataAcrossRegions() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.BoolPtrOutput { return v.AllowMovingDataAcrossRegions }).(pulumi.BoolPtrOutput)
}

// Specific Azure region within the location geo.
func (o EnvironmentOutput) AzureRegion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.AzureRegion }).(pulumi.StringPtrOutput)
}

// ID of the billing policy linked to this environment.
func (o EnvironmentOutput) BillingPolicyId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.BillingPolicyId }).(pulumi.StringPtrOutput)
}

// Release wave cadence: Frequent or Moderate.
func (o EnvironmentOutput) Cadence() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.Cadence }).(pulumi.StringPtrOutput)
}

// The timestamp when the environment was created.
func (o EnvironmentOutput) CreatedTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.CreatedTime }).(pulumi.StringPtrOutput)
}

// Dataverse database configuration. Presence triggers Dataverse provisioning.
func (o EnvironmentOutput) Dataverse() DataversePtrOutput {
	return o.ApplyT(func(v *Environment) DataversePtrOutput { return v.Dataverse }).(DataversePtrOutput)
}

// The description of the environment.
func (o EnvironmentOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The display name of the environment.
func (o EnvironmentOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringOutput { return v.DisplayName }).(pulumi.StringOutput)
}

// Enterprise policies associated with the environment.
func (o EnvironmentOutput) EnterprisePolicies() EnterprisePolicyArrayOutput {
	return o.ApplyT(func(v *Environment) EnterprisePolicyArrayOutput { return v.EnterprisePolicies }).(EnterprisePolicyArrayOutput)
}

// ID of the environment group.
func (o EnvironmentOutput) EnvironmentGroupId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.EnvironmentGroupId }).(pulumi.StringPtrOutput)
}

// The type (SKU) of the environment.
func (o EnvironmentOutput) EnvironmentType() pulumi.StringOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringOutput { return v.EnvironmentType }).(pulumi.StringOutput)
}

// The timestamp when the environment was last modified.
func (o EnvironmentOutput) LastModifiedTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.LastModifiedTime }).(pulumi.StringPtrOutput)
}

// GUID of the linked app.
func (o EnvironmentOutput) LinkedAppId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.LinkedAppId }).(pulumi.StringPtrOutput)
}

// Type of linked app: Canvas or ModelDriven.
func (o EnvironmentOutput) LinkedAppType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.LinkedAppType }).(pulumi.StringPtrOutput)
}

// URL of the linked app. Computed.
func (o EnvironmentOutput) LinkedAppUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.LinkedAppUrl }).(pulumi.StringPtrOutput)
}

// The geographic region of the environment.
func (o EnvironmentOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringOutput { return v.Location }).(pulumi.StringOutput)
}

// AAD user or group GUID who owns the environment.
func (o EnvironmentOutput) OwnerId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.OwnerId }).(pulumi.StringPtrOutput)
}

// The current state of the environment (e.g., Ready, Preparing).
func (o EnvironmentOutput) State() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.State }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EnvironmentInput)(nil)).Elem(), &Environment{})
	pulumi.RegisterOutputType(EnvironmentOutput{})
}
