// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package powerplatform

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rpothin/pulumi-powerplatform/sdk/go/powerplatform/internal"
)

// Lists all rule-based DLP (Data Loss Prevention) policies in the tenant.
func GetDlpPolicies(ctx *pulumi.Context, args *GetDlpPoliciesArgs, opts ...pulumi.InvokeOption) (*GetDlpPoliciesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDlpPoliciesResult
	err := ctx.Invoke("powerplatform:index:getDlpPolicies", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetDlpPoliciesArgs struct {
}

type GetDlpPoliciesResult struct {
	// The list of DLP policies.
	Policies []DlpPolicySummary `pulumi:"policies"`
}

func GetDlpPoliciesOutput(ctx *pulumi.Context, args GetDlpPoliciesOutputArgs, opts ...pulumi.InvokeOption) GetDlpPoliciesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDlpPoliciesResultOutput, error) {
			args := v.(GetDlpPoliciesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("powerplatform:index:getDlpPolicies", args, GetDlpPoliciesResultOutput{}, options).(GetDlpPoliciesResultOutput), nil
		}).(GetDlpPoliciesResultOutput)
}

type GetDlpPoliciesOutputArgs struct {
}

func (GetDlpPoliciesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDlpPoliciesArgs)(nil)).Elem()
}

type GetDlpPoliciesResultOutput struct{ *pulumi.OutputState }

func (GetDlpPoliciesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDlpPoliciesResult)(nil)).Elem()
}

func (o GetDlpPoliciesResultOutput) ToGetDlpPoliciesResultOutput() GetDlpPoliciesResultOutput {
	return o
}

func (o GetDlpPoliciesResultOutput) ToGetDlpPoliciesResultOutputWithContext(ctx context.Context) GetDlpPoliciesResultOutput {
	return o
}

// The list of DLP policies.
func (o GetDlpPoliciesResultOutput) Policies() DlpPolicySummaryArrayOutput {
	return o.ApplyT(func(v GetDlpPoliciesResult) []DlpPolicySummary { return v.Policies }).(DlpPolicySummaryArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDlpPoliciesResultOutput{})
}
