// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package powerplatform

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rpothin/pulumi-powerplatform/sdk/go/powerplatform/internal"
)

// Reads an existing DLP policy by ID and returns its configuration ready for use with ResDlpPolicy or powerplatform:index:DlpPolicy. This function is the Pulumi equivalent of the utl-dlppolicy-replicator Terraform module. It is advisory-only: no enforcement or reclassification is applied.
func GetDlpPolicyMigrationConfig(ctx *pulumi.Context, args *GetDlpPolicyMigrationConfigArgs, opts ...pulumi.InvokeOption) (*GetDlpPolicyMigrationConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDlpPolicyMigrationConfigResult
	err := ctx.Invoke("powerplatform:index:getDlpPolicyMigrationConfig", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetDlpPolicyMigrationConfigArgs struct {
	// The ID of the source DLP policy to read migration configuration from.
	SourcePolicyId string `pulumi:"sourcePolicyId"`
}

type GetDlpPolicyMigrationConfigResult struct {
	// Display name of the source DLP policy. Use as the displayName input for ResDlpPolicy.
	DisplayName string `pulumi:"displayName"`
	// Display name of the source DLP policy. Use as the name input for powerplatform:index:DlpPolicy.
	Name string `pulumi:"name"`
	// Rule set configurations from the source policy, ready for input to ResDlpPolicy or DlpPolicy.
	RuleSets []RuleSet `pulumi:"ruleSets"`
}

func GetDlpPolicyMigrationConfigOutput(ctx *pulumi.Context, args GetDlpPolicyMigrationConfigOutputArgs, opts ...pulumi.InvokeOption) GetDlpPolicyMigrationConfigResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDlpPolicyMigrationConfigResultOutput, error) {
			args := v.(GetDlpPolicyMigrationConfigArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("powerplatform:index:getDlpPolicyMigrationConfig", args, GetDlpPolicyMigrationConfigResultOutput{}, options).(GetDlpPolicyMigrationConfigResultOutput), nil
		}).(GetDlpPolicyMigrationConfigResultOutput)
}

type GetDlpPolicyMigrationConfigOutputArgs struct {
	// The ID of the source DLP policy to read migration configuration from.
	SourcePolicyId pulumi.StringInput `pulumi:"sourcePolicyId"`
}

func (GetDlpPolicyMigrationConfigOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDlpPolicyMigrationConfigArgs)(nil)).Elem()
}

type GetDlpPolicyMigrationConfigResultOutput struct{ *pulumi.OutputState }

func (GetDlpPolicyMigrationConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDlpPolicyMigrationConfigResult)(nil)).Elem()
}

func (o GetDlpPolicyMigrationConfigResultOutput) ToGetDlpPolicyMigrationConfigResultOutput() GetDlpPolicyMigrationConfigResultOutput {
	return o
}

func (o GetDlpPolicyMigrationConfigResultOutput) ToGetDlpPolicyMigrationConfigResultOutputWithContext(ctx context.Context) GetDlpPolicyMigrationConfigResultOutput {
	return o
}

// Display name of the source DLP policy. Use as the displayName input for ResDlpPolicy.
func (o GetDlpPolicyMigrationConfigResultOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v GetDlpPolicyMigrationConfigResult) string { return v.DisplayName }).(pulumi.StringOutput)
}

// Display name of the source DLP policy. Use as the name input for powerplatform:index:DlpPolicy.
func (o GetDlpPolicyMigrationConfigResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetDlpPolicyMigrationConfigResult) string { return v.Name }).(pulumi.StringOutput)
}

// Rule set configurations from the source policy, ready for input to ResDlpPolicy or DlpPolicy.
func (o GetDlpPolicyMigrationConfigResultOutput) RuleSets() RuleSetArrayOutput {
	return o.ApplyT(func(v GetDlpPolicyMigrationConfigResult) []RuleSet { return v.RuleSets }).(RuleSetArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDlpPolicyMigrationConfigResultOutput{})
}
