// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package powerplatform

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rpothin/pulumi-powerplatform/sdk/go/powerplatform/internal"
)

// Fetches Dataverse security roles from a Power Platform environment.
func GetSecurityRoles(ctx *pulumi.Context, args *GetSecurityRolesArgs, opts ...pulumi.InvokeOption) (*GetSecurityRolesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetSecurityRolesResult
	err := ctx.Invoke("powerplatform:index:getSecurityRoles", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetSecurityRolesArgs struct {
	// Optional business unit GUID to filter roles.
	BusinessUnitId *string `pulumi:"businessUnitId"`
	// Environment ID to query roles from.
	EnvironmentId string `pulumi:"environmentId"`
}

type GetSecurityRolesResult struct {
	// List of security roles.
	SecurityRoles []SecurityRole `pulumi:"securityRoles"`
}

func GetSecurityRolesOutput(ctx *pulumi.Context, args GetSecurityRolesOutputArgs, opts ...pulumi.InvokeOption) GetSecurityRolesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetSecurityRolesResultOutput, error) {
			args := v.(GetSecurityRolesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("powerplatform:index:getSecurityRoles", args, GetSecurityRolesResultOutput{}, options).(GetSecurityRolesResultOutput), nil
		}).(GetSecurityRolesResultOutput)
}

type GetSecurityRolesOutputArgs struct {
	// Optional business unit GUID to filter roles.
	BusinessUnitId pulumi.StringPtrInput `pulumi:"businessUnitId"`
	// Environment ID to query roles from.
	EnvironmentId pulumi.StringInput `pulumi:"environmentId"`
}

func (GetSecurityRolesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSecurityRolesArgs)(nil)).Elem()
}

type GetSecurityRolesResultOutput struct{ *pulumi.OutputState }

func (GetSecurityRolesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSecurityRolesResult)(nil)).Elem()
}

func (o GetSecurityRolesResultOutput) ToGetSecurityRolesResultOutput() GetSecurityRolesResultOutput {
	return o
}

func (o GetSecurityRolesResultOutput) ToGetSecurityRolesResultOutputWithContext(ctx context.Context) GetSecurityRolesResultOutput {
	return o
}

// List of security roles.
func (o GetSecurityRolesResultOutput) SecurityRoles() SecurityRoleArrayOutput {
	return o.ApplyT(func(v GetSecurityRolesResult) []SecurityRole { return v.SecurityRoles }).(SecurityRoleArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetSecurityRolesResultOutput{})
}
