// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package powerplatform

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/rpothin/pulumi-powerplatform/sdk/go/powerplatform/internal"
)

// Grants read access to a Dataverse deployment pipeline for a team.
//
// All input properties are immutable; any change triggers replacement.
type PipelineSharing struct {
	pulumi.CustomResourceState

	// Requested access mask.
	AccessMask pulumi.StringPtrOutput `pulumi:"accessMask"`
	// Host environment ID.
	EnvironmentId pulumi.StringOutput `pulumi:"environmentId"`
	// Actual access mask granted.
	GrantedAccessMask pulumi.StringOutput `pulumi:"grantedAccessMask"`
	// Deployment pipeline record ID.
	PipelineId pulumi.StringOutput `pulumi:"pipelineId"`
	// Team record ID.
	TeamId pulumi.StringOutput `pulumi:"teamId"`
}

// NewPipelineSharing registers a new resource with the given unique name, arguments, and options.
func NewPipelineSharing(ctx *pulumi.Context,
	name string, args *PipelineSharingArgs, opts ...pulumi.ResourceOption) (*PipelineSharing, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EnvironmentId == nil {
		return nil, errors.New("invalid value for required argument 'EnvironmentId'")
	}
	if args.PipelineId == nil {
		return nil, errors.New("invalid value for required argument 'PipelineId'")
	}
	if args.TeamId == nil {
		return nil, errors.New("invalid value for required argument 'TeamId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PipelineSharing
	err := ctx.RegisterResource("powerplatform:index:PipelineSharing", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPipelineSharing gets an existing PipelineSharing resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPipelineSharing(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PipelineSharingState, opts ...pulumi.ResourceOption) (*PipelineSharing, error) {
	var resource PipelineSharing
	err := ctx.ReadResource("powerplatform:index:PipelineSharing", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PipelineSharing resources.
type pipelineSharingState struct {
}

type PipelineSharingState struct {
}

func (PipelineSharingState) ElementType() reflect.Type {
	return reflect.TypeOf((*pipelineSharingState)(nil)).Elem()
}

type pipelineSharingArgs struct {
	// Access mask. Default: ReadAccess.
	AccessMask *string `pulumi:"accessMask"`
	// Host environment ID.
	EnvironmentId string `pulumi:"environmentId"`
	// Deployment pipeline record ID.
	PipelineId string `pulumi:"pipelineId"`
	// Team record ID to grant access to.
	TeamId string `pulumi:"teamId"`
}

// The set of arguments for constructing a PipelineSharing resource.
type PipelineSharingArgs struct {
	// Access mask. Default: ReadAccess.
	AccessMask pulumi.StringPtrInput
	// Host environment ID.
	EnvironmentId pulumi.StringInput
	// Deployment pipeline record ID.
	PipelineId pulumi.StringInput
	// Team record ID to grant access to.
	TeamId pulumi.StringInput
}

func (PipelineSharingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*pipelineSharingArgs)(nil)).Elem()
}

type PipelineSharingInput interface {
	pulumi.Input

	ToPipelineSharingOutput() PipelineSharingOutput
	ToPipelineSharingOutputWithContext(ctx context.Context) PipelineSharingOutput
}

func (*PipelineSharing) ElementType() reflect.Type {
	return reflect.TypeOf((**PipelineSharing)(nil)).Elem()
}

func (i *PipelineSharing) ToPipelineSharingOutput() PipelineSharingOutput {
	return i.ToPipelineSharingOutputWithContext(context.Background())
}

func (i *PipelineSharing) ToPipelineSharingOutputWithContext(ctx context.Context) PipelineSharingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PipelineSharingOutput)
}

type PipelineSharingOutput struct{ *pulumi.OutputState }

func (PipelineSharingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PipelineSharing)(nil)).Elem()
}

func (o PipelineSharingOutput) ToPipelineSharingOutput() PipelineSharingOutput {
	return o
}

func (o PipelineSharingOutput) ToPipelineSharingOutputWithContext(ctx context.Context) PipelineSharingOutput {
	return o
}

// Requested access mask.
func (o PipelineSharingOutput) AccessMask() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PipelineSharing) pulumi.StringPtrOutput { return v.AccessMask }).(pulumi.StringPtrOutput)
}

// Host environment ID.
func (o PipelineSharingOutput) EnvironmentId() pulumi.StringOutput {
	return o.ApplyT(func(v *PipelineSharing) pulumi.StringOutput { return v.EnvironmentId }).(pulumi.StringOutput)
}

// Actual access mask granted.
func (o PipelineSharingOutput) GrantedAccessMask() pulumi.StringOutput {
	return o.ApplyT(func(v *PipelineSharing) pulumi.StringOutput { return v.GrantedAccessMask }).(pulumi.StringOutput)
}

// Deployment pipeline record ID.
func (o PipelineSharingOutput) PipelineId() pulumi.StringOutput {
	return o.ApplyT(func(v *PipelineSharing) pulumi.StringOutput { return v.PipelineId }).(pulumi.StringOutput)
}

// Team record ID.
func (o PipelineSharingOutput) TeamId() pulumi.StringOutput {
	return o.ApplyT(func(v *PipelineSharing) pulumi.StringOutput { return v.TeamId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PipelineSharingInput)(nil)).Elem(), &PipelineSharing{})
	pulumi.RegisterOutputType(PipelineSharingOutput{})
}
