// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class Dataverse {
    /**
     * @return Whether the Dataverse instance is in administration mode.
     * 
     */
    private @Nullable Boolean administrationModeEnabled;
    /**
     * @return Whether background operations are enabled during administration mode.
     * 
     */
    private @Nullable Boolean backgroundOperationEnabled;
    /**
     * @return Currency code for the Dataverse database (e.g. USD). Immutable after creation.
     * 
     */
    private @Nullable String currencyCode;
    /**
     * @return Domain prefix for the Dataverse instance URL.
     * 
     */
    private @Nullable String domainName;
    /**
     * @return Base language LCID (e.g. 1033). Immutable after creation.
     * 
     */
    private @Nullable Integer languageCode;
    /**
     * @return Dataverse organization GUID. Computed.
     * 
     */
    private @Nullable String organizationId;
    /**
     * @return AAD security group GUID restricting environment access.
     * 
     */
    private @Nullable String securityGroupId;
    /**
     * @return JSON metadata for provisioning templates. Immutable after creation.
     * 
     */
    private @Nullable String templateMetadata;
    /**
     * @return Provisioning templates (e.g. D365_Sales). Immutable after creation.
     * 
     */
    private @Nullable List<String> templates;
    /**
     * @return Dataverse unique name. Computed.
     * 
     */
    private @Nullable String uniqueName;
    /**
     * @return URL of the Dataverse instance. Computed.
     * 
     */
    private @Nullable String url;
    /**
     * @return Dataverse version string. Computed.
     * 
     */
    private @Nullable String version;

    private Dataverse() {}
    /**
     * @return Whether the Dataverse instance is in administration mode.
     * 
     */
    public Optional<Boolean> administrationModeEnabled() {
        return Optional.ofNullable(this.administrationModeEnabled);
    }
    /**
     * @return Whether background operations are enabled during administration mode.
     * 
     */
    public Optional<Boolean> backgroundOperationEnabled() {
        return Optional.ofNullable(this.backgroundOperationEnabled);
    }
    /**
     * @return Currency code for the Dataverse database (e.g. USD). Immutable after creation.
     * 
     */
    public Optional<String> currencyCode() {
        return Optional.ofNullable(this.currencyCode);
    }
    /**
     * @return Domain prefix for the Dataverse instance URL.
     * 
     */
    public Optional<String> domainName() {
        return Optional.ofNullable(this.domainName);
    }
    /**
     * @return Base language LCID (e.g. 1033). Immutable after creation.
     * 
     */
    public Optional<Integer> languageCode() {
        return Optional.ofNullable(this.languageCode);
    }
    /**
     * @return Dataverse organization GUID. Computed.
     * 
     */
    public Optional<String> organizationId() {
        return Optional.ofNullable(this.organizationId);
    }
    /**
     * @return AAD security group GUID restricting environment access.
     * 
     */
    public Optional<String> securityGroupId() {
        return Optional.ofNullable(this.securityGroupId);
    }
    /**
     * @return JSON metadata for provisioning templates. Immutable after creation.
     * 
     */
    public Optional<String> templateMetadata() {
        return Optional.ofNullable(this.templateMetadata);
    }
    /**
     * @return Provisioning templates (e.g. D365_Sales). Immutable after creation.
     * 
     */
    public List<String> templates() {
        return this.templates == null ? List.of() : this.templates;
    }
    /**
     * @return Dataverse unique name. Computed.
     * 
     */
    public Optional<String> uniqueName() {
        return Optional.ofNullable(this.uniqueName);
    }
    /**
     * @return URL of the Dataverse instance. Computed.
     * 
     */
    public Optional<String> url() {
        return Optional.ofNullable(this.url);
    }
    /**
     * @return Dataverse version string. Computed.
     * 
     */
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(Dataverse defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean administrationModeEnabled;
        private @Nullable Boolean backgroundOperationEnabled;
        private @Nullable String currencyCode;
        private @Nullable String domainName;
        private @Nullable Integer languageCode;
        private @Nullable String organizationId;
        private @Nullable String securityGroupId;
        private @Nullable String templateMetadata;
        private @Nullable List<String> templates;
        private @Nullable String uniqueName;
        private @Nullable String url;
        private @Nullable String version;
        public Builder() {}
        public Builder(Dataverse defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.administrationModeEnabled = defaults.administrationModeEnabled;
    	      this.backgroundOperationEnabled = defaults.backgroundOperationEnabled;
    	      this.currencyCode = defaults.currencyCode;
    	      this.domainName = defaults.domainName;
    	      this.languageCode = defaults.languageCode;
    	      this.organizationId = defaults.organizationId;
    	      this.securityGroupId = defaults.securityGroupId;
    	      this.templateMetadata = defaults.templateMetadata;
    	      this.templates = defaults.templates;
    	      this.uniqueName = defaults.uniqueName;
    	      this.url = defaults.url;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder administrationModeEnabled(@Nullable Boolean administrationModeEnabled) {

            this.administrationModeEnabled = administrationModeEnabled;
            return this;
        }
        @CustomType.Setter
        public Builder backgroundOperationEnabled(@Nullable Boolean backgroundOperationEnabled) {

            this.backgroundOperationEnabled = backgroundOperationEnabled;
            return this;
        }
        @CustomType.Setter
        public Builder currencyCode(@Nullable String currencyCode) {

            this.currencyCode = currencyCode;
            return this;
        }
        @CustomType.Setter
        public Builder domainName(@Nullable String domainName) {

            this.domainName = domainName;
            return this;
        }
        @CustomType.Setter
        public Builder languageCode(@Nullable Integer languageCode) {

            this.languageCode = languageCode;
            return this;
        }
        @CustomType.Setter
        public Builder organizationId(@Nullable String organizationId) {

            this.organizationId = organizationId;
            return this;
        }
        @CustomType.Setter
        public Builder securityGroupId(@Nullable String securityGroupId) {

            this.securityGroupId = securityGroupId;
            return this;
        }
        @CustomType.Setter
        public Builder templateMetadata(@Nullable String templateMetadata) {

            this.templateMetadata = templateMetadata;
            return this;
        }
        @CustomType.Setter
        public Builder templates(@Nullable List<String> templates) {

            this.templates = templates;
            return this;
        }
        public Builder templates(String... templates) {
            return templates(List.of(templates));
        }
        @CustomType.Setter
        public Builder uniqueName(@Nullable String uniqueName) {

            this.uniqueName = uniqueName;
            return this;
        }
        @CustomType.Setter
        public Builder url(@Nullable String url) {

            this.url = url;
            return this;
        }
        @CustomType.Setter
        public Builder version(@Nullable String version) {

            this.version = version;
            return this;
        }
        public Dataverse build() {
            final var _resultValue = new Dataverse();
            _resultValue.administrationModeEnabled = administrationModeEnabled;
            _resultValue.backgroundOperationEnabled = backgroundOperationEnabled;
            _resultValue.currencyCode = currencyCode;
            _resultValue.domainName = domainName;
            _resultValue.languageCode = languageCode;
            _resultValue.organizationId = organizationId;
            _resultValue.securityGroupId = securityGroupId;
            _resultValue.templateMetadata = templateMetadata;
            _resultValue.templates = templates;
            _resultValue.uniqueName = uniqueName;
            _resultValue.url = url;
            _resultValue.version = version;
            return _resultValue;
        }
    }
}
