// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.outputs;

import com.pulumi.core.annotations.CustomType;
import io.github.rpothin.powerplatform.outputs.RuleSet;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DlpPolicySummary {
    /**
     * @return The unique identifier of the DLP policy.
     * 
     */
    private @Nullable String id;
    /**
     * @return The ISO 8601 timestamp when the policy was last modified.
     * 
     */
    private @Nullable String lastModified;
    /**
     * @return The display name of the DLP policy.
     * 
     */
    private @Nullable String name;
    /**
     * @return The total number of rule sets in the policy.
     * 
     */
    private @Nullable Integer ruleSetCount;
    /**
     * @return The rule sets that define the DLP policy rules.
     * 
     */
    private @Nullable List<RuleSet> ruleSets;
    /**
     * @return The ID of the tenant owning the DLP policy.
     * 
     */
    private @Nullable String tenantId;

    private DlpPolicySummary() {}
    /**
     * @return The unique identifier of the DLP policy.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    /**
     * @return The ISO 8601 timestamp when the policy was last modified.
     * 
     */
    public Optional<String> lastModified() {
        return Optional.ofNullable(this.lastModified);
    }
    /**
     * @return The display name of the DLP policy.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return The total number of rule sets in the policy.
     * 
     */
    public Optional<Integer> ruleSetCount() {
        return Optional.ofNullable(this.ruleSetCount);
    }
    /**
     * @return The rule sets that define the DLP policy rules.
     * 
     */
    public List<RuleSet> ruleSets() {
        return this.ruleSets == null ? List.of() : this.ruleSets;
    }
    /**
     * @return The ID of the tenant owning the DLP policy.
     * 
     */
    public Optional<String> tenantId() {
        return Optional.ofNullable(this.tenantId);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DlpPolicySummary defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String id;
        private @Nullable String lastModified;
        private @Nullable String name;
        private @Nullable Integer ruleSetCount;
        private @Nullable List<RuleSet> ruleSets;
        private @Nullable String tenantId;
        public Builder() {}
        public Builder(DlpPolicySummary defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.lastModified = defaults.lastModified;
    	      this.name = defaults.name;
    	      this.ruleSetCount = defaults.ruleSetCount;
    	      this.ruleSets = defaults.ruleSets;
    	      this.tenantId = defaults.tenantId;
        }

        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder lastModified(@Nullable String lastModified) {

            this.lastModified = lastModified;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder ruleSetCount(@Nullable Integer ruleSetCount) {

            this.ruleSetCount = ruleSetCount;
            return this;
        }
        @CustomType.Setter
        public Builder ruleSets(@Nullable List<RuleSet> ruleSets) {

            this.ruleSets = ruleSets;
            return this;
        }
        public Builder ruleSets(RuleSet... ruleSets) {
            return ruleSets(List.of(ruleSets));
        }
        @CustomType.Setter
        public Builder tenantId(@Nullable String tenantId) {

            this.tenantId = tenantId;
            return this;
        }
        public DlpPolicySummary build() {
            final var _resultValue = new DlpPolicySummary();
            _resultValue.id = id;
            _resultValue.lastModified = lastModified;
            _resultValue.name = name;
            _resultValue.ruleSetCount = ruleSetCount;
            _resultValue.ruleSets = ruleSets;
            _resultValue.tenantId = tenantId;
            return _resultValue;
        }
    }
}
