// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetDataRecordsResult {
    /**
     * @return The list of matching Dataverse records. Each record is a map of column name to value.
     * 
     */
    private List<Object> records;
    /**
     * @return Total number of records matching the query filter (from {@literal @}odata.count). Always 0 when the count annotation is absent or when `apply` is used (the count is not available in aggregation mode).
     * 
     */
    private Integer totalRowsCount;
    /**
     * @return True when the total row count exceeded the Dataverse limit ({@literal @}Microsoft.Dynamics.CRM.totalrecordcountlimitexceeded).
     * 
     */
    private Boolean totalRowsCountLimitExceeded;

    private GetDataRecordsResult() {}
    /**
     * @return The list of matching Dataverse records. Each record is a map of column name to value.
     * 
     */
    public List<Object> records() {
        return this.records;
    }
    /**
     * @return Total number of records matching the query filter (from {@literal @}odata.count). Always 0 when the count annotation is absent or when `apply` is used (the count is not available in aggregation mode).
     * 
     */
    public Integer totalRowsCount() {
        return this.totalRowsCount;
    }
    /**
     * @return True when the total row count exceeded the Dataverse limit ({@literal @}Microsoft.Dynamics.CRM.totalrecordcountlimitexceeded).
     * 
     */
    public Boolean totalRowsCountLimitExceeded() {
        return this.totalRowsCountLimitExceeded;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDataRecordsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<Object> records;
        private Integer totalRowsCount;
        private Boolean totalRowsCountLimitExceeded;
        public Builder() {}
        public Builder(GetDataRecordsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.records = defaults.records;
    	      this.totalRowsCount = defaults.totalRowsCount;
    	      this.totalRowsCountLimitExceeded = defaults.totalRowsCountLimitExceeded;
        }

        @CustomType.Setter
        public Builder records(List<Object> records) {
            if (records == null) {
              throw new MissingRequiredPropertyException("GetDataRecordsResult", "records");
            }
            this.records = records;
            return this;
        }
        public Builder records(Object... records) {
            return records(List.of(records));
        }
        @CustomType.Setter
        public Builder totalRowsCount(Integer totalRowsCount) {
            if (totalRowsCount == null) {
              throw new MissingRequiredPropertyException("GetDataRecordsResult", "totalRowsCount");
            }
            this.totalRowsCount = totalRowsCount;
            return this;
        }
        @CustomType.Setter
        public Builder totalRowsCountLimitExceeded(Boolean totalRowsCountLimitExceeded) {
            if (totalRowsCountLimitExceeded == null) {
              throw new MissingRequiredPropertyException("GetDataRecordsResult", "totalRowsCountLimitExceeded");
            }
            this.totalRowsCountLimitExceeded = totalRowsCountLimitExceeded;
            return this;
        }
        public GetDataRecordsResult build() {
            final var _resultValue = new GetDataRecordsResult();
            _resultValue.records = records;
            _resultValue.totalRowsCount = totalRowsCount;
            _resultValue.totalRowsCountLimitExceeded = totalRowsCountLimitExceeded;
            return _resultValue;
        }
    }
}
