// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.rpothin.powerplatform.outputs.DlpPolicySummary;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetDlpPoliciesResult {
    /**
     * @return The list of DLP policies.
     * 
     */
    private List<DlpPolicySummary> policies;

    private GetDlpPoliciesResult() {}
    /**
     * @return The list of DLP policies.
     * 
     */
    public List<DlpPolicySummary> policies() {
        return this.policies;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDlpPoliciesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<DlpPolicySummary> policies;
        public Builder() {}
        public Builder(GetDlpPoliciesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.policies = defaults.policies;
        }

        @CustomType.Setter
        public Builder policies(List<DlpPolicySummary> policies) {
            if (policies == null) {
              throw new MissingRequiredPropertyException("GetDlpPoliciesResult", "policies");
            }
            this.policies = policies;
            return this;
        }
        public Builder policies(DlpPolicySummary... policies) {
            return policies(List.of(policies));
        }
        public GetDlpPoliciesResult build() {
            final var _resultValue = new GetDlpPoliciesResult();
            _resultValue.policies = policies;
            return _resultValue;
        }
    }
}
