// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class RuleSet {
    /**
     * @return The unique identifier of the rule set.
     * 
     */
    private @Nullable String id;
    /**
     * @return The inputs for the rule set, which may vary based on the rule.
     * 
     */
    private @Nullable Map<String,Object> inputs;
    /**
     * @return The version of the rule set.
     * 
     */
    private @Nullable String version;

    private RuleSet() {}
    /**
     * @return The unique identifier of the rule set.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    /**
     * @return The inputs for the rule set, which may vary based on the rule.
     * 
     */
    public Map<String,Object> inputs() {
        return this.inputs == null ? Map.of() : this.inputs;
    }
    /**
     * @return The version of the rule set.
     * 
     */
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(RuleSet defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String id;
        private @Nullable Map<String,Object> inputs;
        private @Nullable String version;
        public Builder() {}
        public Builder(RuleSet defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.inputs = defaults.inputs;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder inputs(@Nullable Map<String,Object> inputs) {

            this.inputs = inputs;
            return this;
        }
        @CustomType.Setter
        public Builder version(@Nullable String version) {

            this.version = version;
            return this;
        }
        public RuleSet build() {
            final var _resultValue = new RuleSet();
            _resultValue.id = id;
            _resultValue.inputs = inputs;
            _resultValue.version = version;
            return _resultValue;
        }
    }
}
