// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform
{
    public static class GetApps
    {
        /// <summary>
        /// Lists Power Apps in a Power Platform environment.
        /// </summary>
        public static Task<GetAppsResult> InvokeAsync(GetAppsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAppsResult>("powerplatform:index:getApps", args ?? new GetAppsArgs(), options.WithDefaults());

        /// <summary>
        /// Lists Power Apps in a Power Platform environment.
        /// </summary>
        public static Output<GetAppsResult> Invoke(GetAppsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAppsResult>("powerplatform:index:getApps", args ?? new GetAppsInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Lists Power Apps in a Power Platform environment.
        /// </summary>
        public static Output<GetAppsResult> Invoke(GetAppsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAppsResult>("powerplatform:index:getApps", args ?? new GetAppsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAppsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the environment to list apps for.
        /// </summary>
        [Input("environmentId", required: true)]
        public string EnvironmentId { get; set; } = null!;

        public GetAppsArgs()
        {
        }
        public static new GetAppsArgs Empty => new GetAppsArgs();
    }

    public sealed class GetAppsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the environment to list apps for.
        /// </summary>
        [Input("environmentId", required: true)]
        public Input<string> EnvironmentId { get; set; } = null!;

        public GetAppsInvokeArgs()
        {
        }
        public static new GetAppsInvokeArgs Empty => new GetAppsInvokeArgs();
    }


    [OutputType]
    public sealed class GetAppsResult
    {
        /// <summary>
        /// The list of Power Apps.
        /// </summary>
        public readonly ImmutableArray<Outputs.AppSummary> Apps;

        [OutputConstructor]
        private GetAppsResult(ImmutableArray<Outputs.AppSummary> apps)
        {
            Apps = apps;
        }
    }
}
