// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Outputs
{

    /// <summary>
    /// Azure billing instrument (subscription) details for a billing policy.
    /// </summary>
    [OutputType]
    public sealed class BillingInstrument
    {
        /// <summary>
        /// The billing instrument identifier.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The Azure resource group within the subscription.
        /// </summary>
        public readonly string? ResourceGroup;
        /// <summary>
        /// The Azure subscription ID.
        /// </summary>
        public readonly string? SubscriptionId;

        [OutputConstructor]
        private BillingInstrument(
            string? id,

            string? resourceGroup,

            string? subscriptionId)
        {
            Id = id;
            ResourceGroup = resourceGroup;
            SubscriptionId = subscriptionId;
        }
    }
}
