// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Outputs
{

    /// <summary>
    /// User management settings.
    /// </summary>
    [OutputType]
    public sealed class TenantUserManagementSettings
    {
        /// <summary>
        /// Enable delete disabled user in all environments.
        /// </summary>
        public readonly bool? EnableDeleteDisabledUserInAllEnvironments;

        [OutputConstructor]
        private TenantUserManagementSettings(bool? enableDeleteDisabledUserInAllEnvironments)
        {
            EnableDeleteDisabledUserInAllEnvironments = enableDeleteDisabledUserInAllEnvironments;
        }
    }
}
