// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Outputs
{

    /// <summary>
    /// Licensing settings.
    /// </summary>
    [OutputType]
    public sealed class TenantLicensingSettings
    {
        /// <summary>
        /// Disable billing policy creation by non-admin users.
        /// </summary>
        public readonly bool? DisableBillingPolicyCreationByNonAdminUsers;
        /// <summary>
        /// Disable use of unassigned AI Builder credits.
        /// </summary>
        public readonly bool? DisableUseOfUnassignedAIBuilderCredits;
        /// <summary>
        /// Enable tenant capacity report for environment admins.
        /// </summary>
        public readonly bool? EnableTenantCapacityReportForEnvironmentAdmins;
        /// <summary>
        /// Enable tenant licensing report for environment admins.
        /// </summary>
        public readonly bool? EnableTenantLicensingReportForEnvironmentAdmins;
        /// <summary>
        /// Storage capacity consumption warning threshold.
        /// </summary>
        public readonly int? StorageCapacityConsumptionWarningThreshold;

        [OutputConstructor]
        private TenantLicensingSettings(
            bool? disableBillingPolicyCreationByNonAdminUsers,

            bool? disableUseOfUnassignedAIBuilderCredits,

            bool? enableTenantCapacityReportForEnvironmentAdmins,

            bool? enableTenantLicensingReportForEnvironmentAdmins,

            int? storageCapacityConsumptionWarningThreshold)
        {
            DisableBillingPolicyCreationByNonAdminUsers = disableBillingPolicyCreationByNonAdminUsers;
            DisableUseOfUnassignedAIBuilderCredits = disableUseOfUnassignedAIBuilderCredits;
            EnableTenantCapacityReportForEnvironmentAdmins = enableTenantCapacityReportForEnvironmentAdmins;
            EnableTenantLicensingReportForEnvironmentAdmins = enableTenantLicensingReportForEnvironmentAdmins;
            StorageCapacityConsumptionWarningThreshold = storageCapacityConsumptionWarningThreshold;
        }
    }
}
