// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform;

import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("powerplatform");
/**
 * The Azure AD Application (Client) ID. Can also be set with the AZURE_CLIENT_ID environment variable.
 * 
 */
    public Optional<String> clientId() {
        return Codegen.stringProp("clientId").config(config).get();
    }
/**
 * The Azure AD Client Secret. Can also be set with the AZURE_CLIENT_SECRET environment variable.
 * 
 */
    public Optional<String> clientSecret() {
        return Codegen.stringProp("clientSecret").config(config).get();
    }
/**
 * The Azure AD Tenant ID for authenticating with Power Platform. Can also be set with the AZURE_TENANT_ID environment variable.
 * 
 */
    public Optional<String> tenantId() {
        return Codegen.stringProp("tenantId").config(config).get();
    }
}
