// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class EnvironmentArgs extends com.pulumi.resources.ResourceArgs {

    public static final EnvironmentArgs Empty = new EnvironmentArgs();

    /**
     * The currency code for the Dataverse database (e.g., USD, EUR).
     * 
     */
    @Import(name="currencyCode")
    private @Nullable Output<String> currencyCode;

    /**
     * @return The currency code for the Dataverse database (e.g., USD, EUR).
     * 
     */
    public Optional<Output<String>> currencyCode() {
        return Optional.ofNullable(this.currencyCode);
    }

    /**
     * A description of the environment.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return A description of the environment.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The display name of the environment.
     * 
     */
    @Import(name="displayName", required=true)
    private Output<String> displayName;

    /**
     * @return The display name of the environment.
     * 
     */
    public Output<String> displayName() {
        return this.displayName;
    }

    /**
     * The domain name for the Dataverse database associated with the environment.
     * 
     */
    @Import(name="domainName")
    private @Nullable Output<String> domainName;

    /**
     * @return The domain name for the Dataverse database associated with the environment.
     * 
     */
    public Optional<Output<String>> domainName() {
        return Optional.ofNullable(this.domainName);
    }

    /**
     * The type (SKU) of the environment: Sandbox, Production, Trial, Developer, or Default. Immutable after creation.
     * 
     */
    @Import(name="environmentType", required=true)
    private Output<String> environmentType;

    /**
     * @return The type (SKU) of the environment: Sandbox, Production, Trial, Developer, or Default. Immutable after creation.
     * 
     */
    public Output<String> environmentType() {
        return this.environmentType;
    }

    /**
     * The base language code for the Dataverse database (e.g., 1033 for English).
     * 
     */
    @Import(name="languageCode")
    private @Nullable Output<String> languageCode;

    /**
     * @return The base language code for the Dataverse database (e.g., 1033 for English).
     * 
     */
    public Optional<Output<String>> languageCode() {
        return Optional.ofNullable(this.languageCode);
    }

    /**
     * The geographic region for the environment (e.g., unitedstates, europe). Immutable after creation.
     * 
     */
    @Import(name="location", required=true)
    private Output<String> location;

    /**
     * @return The geographic region for the environment (e.g., unitedstates, europe). Immutable after creation.
     * 
     */
    public Output<String> location() {
        return this.location;
    }

    private EnvironmentArgs() {}

    private EnvironmentArgs(EnvironmentArgs $) {
        this.currencyCode = $.currencyCode;
        this.description = $.description;
        this.displayName = $.displayName;
        this.domainName = $.domainName;
        this.environmentType = $.environmentType;
        this.languageCode = $.languageCode;
        this.location = $.location;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EnvironmentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EnvironmentArgs $;

        public Builder() {
            $ = new EnvironmentArgs();
        }

        public Builder(EnvironmentArgs defaults) {
            $ = new EnvironmentArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param currencyCode The currency code for the Dataverse database (e.g., USD, EUR).
         * 
         * @return builder
         * 
         */
        public Builder currencyCode(@Nullable Output<String> currencyCode) {
            $.currencyCode = currencyCode;
            return this;
        }

        /**
         * @param currencyCode The currency code for the Dataverse database (e.g., USD, EUR).
         * 
         * @return builder
         * 
         */
        public Builder currencyCode(String currencyCode) {
            return currencyCode(Output.of(currencyCode));
        }

        /**
         * @param description A description of the environment.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description A description of the environment.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param displayName The display name of the environment.
         * 
         * @return builder
         * 
         */
        public Builder displayName(Output<String> displayName) {
            $.displayName = displayName;
            return this;
        }

        /**
         * @param displayName The display name of the environment.
         * 
         * @return builder
         * 
         */
        public Builder displayName(String displayName) {
            return displayName(Output.of(displayName));
        }

        /**
         * @param domainName The domain name for the Dataverse database associated with the environment.
         * 
         * @return builder
         * 
         */
        public Builder domainName(@Nullable Output<String> domainName) {
            $.domainName = domainName;
            return this;
        }

        /**
         * @param domainName The domain name for the Dataverse database associated with the environment.
         * 
         * @return builder
         * 
         */
        public Builder domainName(String domainName) {
            return domainName(Output.of(domainName));
        }

        /**
         * @param environmentType The type (SKU) of the environment: Sandbox, Production, Trial, Developer, or Default. Immutable after creation.
         * 
         * @return builder
         * 
         */
        public Builder environmentType(Output<String> environmentType) {
            $.environmentType = environmentType;
            return this;
        }

        /**
         * @param environmentType The type (SKU) of the environment: Sandbox, Production, Trial, Developer, or Default. Immutable after creation.
         * 
         * @return builder
         * 
         */
        public Builder environmentType(String environmentType) {
            return environmentType(Output.of(environmentType));
        }

        /**
         * @param languageCode The base language code for the Dataverse database (e.g., 1033 for English).
         * 
         * @return builder
         * 
         */
        public Builder languageCode(@Nullable Output<String> languageCode) {
            $.languageCode = languageCode;
            return this;
        }

        /**
         * @param languageCode The base language code for the Dataverse database (e.g., 1033 for English).
         * 
         * @return builder
         * 
         */
        public Builder languageCode(String languageCode) {
            return languageCode(Output.of(languageCode));
        }

        /**
         * @param location The geographic region for the environment (e.g., unitedstates, europe). Immutable after creation.
         * 
         * @return builder
         * 
         */
        public Builder location(Output<String> location) {
            $.location = location;
            return this;
        }

        /**
         * @param location The geographic region for the environment (e.g., unitedstates, europe). Immutable after creation.
         * 
         * @return builder
         * 
         */
        public Builder location(String location) {
            return location(Output.of(location));
        }

        public EnvironmentArgs build() {
            if ($.displayName == null) {
                throw new MissingRequiredPropertyException("EnvironmentArgs", "displayName");
            }
            if ($.environmentType == null) {
                throw new MissingRequiredPropertyException("EnvironmentArgs", "environmentType");
            }
            if ($.location == null) {
                throw new MissingRequiredPropertyException("EnvironmentArgs", "location");
            }
            return $;
        }
    }

}
