// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.rpothin.powerplatform.EnvironmentArgs;
import io.github.rpothin.powerplatform.Utilities;
import io.github.rpothin.powerplatform.outputs.EnterprisePolicy;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a Power Platform environment. Environments are containers for apps, flows, data, and other resources. Uses the BAP admin REST API for lifecycle management.
 * 
 */
@ResourceType(type="powerplatform:index:Environment")
public class Environment extends com.pulumi.resources.CustomResource {
    /**
     * Whether the environment Dataverse database is in administration-only mode.
     * 
     */
    @Export(name="administrationModeEnabled", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> administrationModeEnabled;

    /**
     * @return Whether the environment Dataverse database is in administration-only mode.
     * 
     */
    public Output<Optional<Boolean>> administrationModeEnabled() {
        return Codegen.optional(this.administrationModeEnabled);
    }
    /**
     * Whether Bing Search integration is allowed.
     * 
     */
    @Export(name="allowBingSearch", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> allowBingSearch;

    /**
     * @return Whether Bing Search integration is allowed.
     * 
     */
    public Output<Optional<Boolean>> allowBingSearch() {
        return Codegen.optional(this.allowBingSearch);
    }
    /**
     * Whether data can move across geographic boundaries for Copilot features.
     * 
     */
    @Export(name="allowMovingDataAcrossRegions", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> allowMovingDataAcrossRegions;

    /**
     * @return Whether data can move across geographic boundaries for Copilot features.
     * 
     */
    public Output<Optional<Boolean>> allowMovingDataAcrossRegions() {
        return Codegen.optional(this.allowMovingDataAcrossRegions);
    }
    /**
     * Specific Azure region within the location geo.
     * 
     */
    @Export(name="azureRegion", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> azureRegion;

    /**
     * @return Specific Azure region within the location geo.
     * 
     */
    public Output<Optional<String>> azureRegion() {
        return Codegen.optional(this.azureRegion);
    }
    /**
     * Whether background operations are enabled during administration mode.
     * 
     */
    @Export(name="backgroundOperationEnabled", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> backgroundOperationEnabled;

    /**
     * @return Whether background operations are enabled during administration mode.
     * 
     */
    public Output<Optional<Boolean>> backgroundOperationEnabled() {
        return Codegen.optional(this.backgroundOperationEnabled);
    }
    /**
     * ID of the billing policy linked to this environment.
     * 
     */
    @Export(name="billingPolicyId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> billingPolicyId;

    /**
     * @return ID of the billing policy linked to this environment.
     * 
     */
    public Output<Optional<String>> billingPolicyId() {
        return Codegen.optional(this.billingPolicyId);
    }
    /**
     * Release wave cadence: Frequent or Moderate.
     * 
     */
    @Export(name="cadence", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> cadence;

    /**
     * @return Release wave cadence: Frequent or Moderate.
     * 
     */
    public Output<Optional<String>> cadence() {
        return Codegen.optional(this.cadence);
    }
    /**
     * The timestamp when the environment was created.
     * 
     */
    @Export(name="createdTime", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> createdTime;

    /**
     * @return The timestamp when the environment was created.
     * 
     */
    public Output<Optional<String>> createdTime() {
        return Codegen.optional(this.createdTime);
    }
    /**
     * The currency code of the Dataverse database.
     * 
     */
    @Export(name="currencyCode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> currencyCode;

    /**
     * @return The currency code of the Dataverse database.
     * 
     */
    public Output<Optional<String>> currencyCode() {
        return Codegen.optional(this.currencyCode);
    }
    /**
     * Dataverse version string. Computed.
     * 
     */
    @Export(name="dataverseVersion", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> dataverseVersion;

    /**
     * @return Dataverse version string. Computed.
     * 
     */
    public Output<Optional<String>> dataverseVersion() {
        return Codegen.optional(this.dataverseVersion);
    }
    /**
     * The description of the environment.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return The description of the environment.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * The display name of the environment.
     * 
     */
    @Export(name="displayName", refs={String.class}, tree="[0]")
    private Output<String> displayName;

    /**
     * @return The display name of the environment.
     * 
     */
    public Output<String> displayName() {
        return this.displayName;
    }
    /**
     * The domain name of the Dataverse database.
     * 
     */
    @Export(name="domainName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> domainName;

    /**
     * @return The domain name of the Dataverse database.
     * 
     */
    public Output<Optional<String>> domainName() {
        return Codegen.optional(this.domainName);
    }
    /**
     * Enterprise policies associated with the environment.
     * 
     */
    @Export(name="enterprisePolicies", refs={List.class,EnterprisePolicy.class}, tree="[0,1]")
    private Output</* @Nullable */ List<EnterprisePolicy>> enterprisePolicies;

    /**
     * @return Enterprise policies associated with the environment.
     * 
     */
    public Output<Optional<List<EnterprisePolicy>>> enterprisePolicies() {
        return Codegen.optional(this.enterprisePolicies);
    }
    /**
     * ID of the environment group.
     * 
     */
    @Export(name="environmentGroupId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> environmentGroupId;

    /**
     * @return ID of the environment group.
     * 
     */
    public Output<Optional<String>> environmentGroupId() {
        return Codegen.optional(this.environmentGroupId);
    }
    /**
     * The type (SKU) of the environment.
     * 
     */
    @Export(name="environmentType", refs={String.class}, tree="[0]")
    private Output<String> environmentType;

    /**
     * @return The type (SKU) of the environment.
     * 
     */
    public Output<String> environmentType() {
        return this.environmentType;
    }
    /**
     * The base language code of the Dataverse database.
     * 
     */
    @Export(name="languageCode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> languageCode;

    /**
     * @return The base language code of the Dataverse database.
     * 
     */
    public Output<Optional<String>> languageCode() {
        return Codegen.optional(this.languageCode);
    }
    /**
     * The timestamp when the environment was last modified.
     * 
     */
    @Export(name="lastModifiedTime", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastModifiedTime;

    /**
     * @return The timestamp when the environment was last modified.
     * 
     */
    public Output<Optional<String>> lastModifiedTime() {
        return Codegen.optional(this.lastModifiedTime);
    }
    /**
     * GUID of the linked app.
     * 
     */
    @Export(name="linkedAppId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> linkedAppId;

    /**
     * @return GUID of the linked app.
     * 
     */
    public Output<Optional<String>> linkedAppId() {
        return Codegen.optional(this.linkedAppId);
    }
    /**
     * Type of linked app: Canvas or ModelDriven.
     * 
     */
    @Export(name="linkedAppType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> linkedAppType;

    /**
     * @return Type of linked app: Canvas or ModelDriven.
     * 
     */
    public Output<Optional<String>> linkedAppType() {
        return Codegen.optional(this.linkedAppType);
    }
    /**
     * URL of the linked app. Computed.
     * 
     */
    @Export(name="linkedAppUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> linkedAppUrl;

    /**
     * @return URL of the linked app. Computed.
     * 
     */
    public Output<Optional<String>> linkedAppUrl() {
        return Codegen.optional(this.linkedAppUrl);
    }
    /**
     * The geographic region of the environment.
     * 
     */
    @Export(name="location", refs={String.class}, tree="[0]")
    private Output<String> location;

    /**
     * @return The geographic region of the environment.
     * 
     */
    public Output<String> location() {
        return this.location;
    }
    /**
     * Dataverse organization ID (resourceId from linkedEnvironmentMetadata). Computed.
     * 
     */
    @Export(name="organizationId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> organizationId;

    /**
     * @return Dataverse organization ID (resourceId from linkedEnvironmentMetadata). Computed.
     * 
     */
    public Output<Optional<String>> organizationId() {
        return Codegen.optional(this.organizationId);
    }
    /**
     * AAD user or group GUID who owns the environment.
     * 
     */
    @Export(name="ownerId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ownerId;

    /**
     * @return AAD user or group GUID who owns the environment.
     * 
     */
    public Output<Optional<String>> ownerId() {
        return Codegen.optional(this.ownerId);
    }
    /**
     * AAD security group GUID restricting environment access.
     * 
     */
    @Export(name="securityGroupId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> securityGroupId;

    /**
     * @return AAD security group GUID restricting environment access.
     * 
     */
    public Output<Optional<String>> securityGroupId() {
        return Codegen.optional(this.securityGroupId);
    }
    /**
     * The current state of the environment (e.g., Ready, Preparing).
     * 
     */
    @Export(name="state", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> state;

    /**
     * @return The current state of the environment (e.g., Ready, Preparing).
     * 
     */
    public Output<Optional<String>> state() {
        return Codegen.optional(this.state);
    }
    /**
     * JSON metadata string for provisioning templates.
     * 
     */
    @Export(name="templateMetadata", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> templateMetadata;

    /**
     * @return JSON metadata string for provisioning templates.
     * 
     */
    public Output<Optional<String>> templateMetadata() {
        return Codegen.optional(this.templateMetadata);
    }
    /**
     * Template names used for Dataverse provisioning.
     * 
     */
    @Export(name="templates", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> templates;

    /**
     * @return Template names used for Dataverse provisioning.
     * 
     */
    public Output<Optional<List<String>>> templates() {
        return Codegen.optional(this.templates);
    }
    /**
     * Dataverse unique name. Computed.
     * 
     */
    @Export(name="uniqueName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> uniqueName;

    /**
     * @return Dataverse unique name. Computed.
     * 
     */
    public Output<Optional<String>> uniqueName() {
        return Codegen.optional(this.uniqueName);
    }
    /**
     * The Dataverse instance URL of the environment.
     * 
     */
    @Export(name="url", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> url;

    /**
     * @return The Dataverse instance URL of the environment.
     * 
     */
    public Output<Optional<String>> url() {
        return Codegen.optional(this.url);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Environment(java.lang.String name) {
        this(name, EnvironmentArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Environment(java.lang.String name, EnvironmentArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Environment(java.lang.String name, EnvironmentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("powerplatform:index:Environment", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Environment(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("powerplatform:index:Environment", name, null, makeResourceOptions(options, id), false);
    }

    private static EnvironmentArgs makeArgs(EnvironmentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? EnvironmentArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/rpothin")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Environment get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Environment(name, id, options);
    }
}
