// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.rpothin.powerplatform.EnvironmentArgs;
import io.github.rpothin.powerplatform.Utilities;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a Power Platform environment. Environments are containers for apps, flows, data, and other resources. Uses the BAP admin REST API for lifecycle management.
 * 
 */
@ResourceType(type="powerplatform:index:Environment")
public class Environment extends com.pulumi.resources.CustomResource {
    /**
     * The timestamp when the environment was created.
     * 
     */
    @Export(name="createdTime", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> createdTime;

    /**
     * @return The timestamp when the environment was created.
     * 
     */
    public Output<Optional<String>> createdTime() {
        return Codegen.optional(this.createdTime);
    }
    /**
     * The currency code of the Dataverse database.
     * 
     */
    @Export(name="currencyCode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> currencyCode;

    /**
     * @return The currency code of the Dataverse database.
     * 
     */
    public Output<Optional<String>> currencyCode() {
        return Codegen.optional(this.currencyCode);
    }
    /**
     * The description of the environment.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return The description of the environment.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * The display name of the environment.
     * 
     */
    @Export(name="displayName", refs={String.class}, tree="[0]")
    private Output<String> displayName;

    /**
     * @return The display name of the environment.
     * 
     */
    public Output<String> displayName() {
        return this.displayName;
    }
    /**
     * The domain name of the Dataverse database.
     * 
     */
    @Export(name="domainName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> domainName;

    /**
     * @return The domain name of the Dataverse database.
     * 
     */
    public Output<Optional<String>> domainName() {
        return Codegen.optional(this.domainName);
    }
    /**
     * The type (SKU) of the environment.
     * 
     */
    @Export(name="environmentType", refs={String.class}, tree="[0]")
    private Output<String> environmentType;

    /**
     * @return The type (SKU) of the environment.
     * 
     */
    public Output<String> environmentType() {
        return this.environmentType;
    }
    /**
     * The base language code of the Dataverse database.
     * 
     */
    @Export(name="languageCode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> languageCode;

    /**
     * @return The base language code of the Dataverse database.
     * 
     */
    public Output<Optional<String>> languageCode() {
        return Codegen.optional(this.languageCode);
    }
    /**
     * The timestamp when the environment was last modified.
     * 
     */
    @Export(name="lastModifiedTime", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastModifiedTime;

    /**
     * @return The timestamp when the environment was last modified.
     * 
     */
    public Output<Optional<String>> lastModifiedTime() {
        return Codegen.optional(this.lastModifiedTime);
    }
    /**
     * The geographic region of the environment.
     * 
     */
    @Export(name="location", refs={String.class}, tree="[0]")
    private Output<String> location;

    /**
     * @return The geographic region of the environment.
     * 
     */
    public Output<String> location() {
        return this.location;
    }
    /**
     * The current state of the environment (e.g., Ready, Preparing).
     * 
     */
    @Export(name="state", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> state;

    /**
     * @return The current state of the environment (e.g., Ready, Preparing).
     * 
     */
    public Output<Optional<String>> state() {
        return Codegen.optional(this.state);
    }
    /**
     * The Dataverse instance URL of the environment.
     * 
     */
    @Export(name="url", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> url;

    /**
     * @return The Dataverse instance URL of the environment.
     * 
     */
    public Output<Optional<String>> url() {
        return Codegen.optional(this.url);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Environment(java.lang.String name) {
        this(name, EnvironmentArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Environment(java.lang.String name, EnvironmentArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Environment(java.lang.String name, EnvironmentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("powerplatform:index:Environment", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Environment(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("powerplatform:index:Environment", name, null, makeResourceOptions(options, id), false);
    }

    private static EnvironmentArgs makeArgs(EnvironmentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? EnvironmentArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/rpothin")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Environment get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Environment(name, id, options);
    }
}
