// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import io.github.rpothin.powerplatform.Utilities;
import io.github.rpothin.powerplatform.inputs.GetAppsArgs;
import io.github.rpothin.powerplatform.inputs.GetAppsPlainArgs;
import io.github.rpothin.powerplatform.inputs.GetConnectorsArgs;
import io.github.rpothin.powerplatform.inputs.GetConnectorsPlainArgs;
import io.github.rpothin.powerplatform.inputs.GetDataRecordsArgs;
import io.github.rpothin.powerplatform.inputs.GetDataRecordsPlainArgs;
import io.github.rpothin.powerplatform.inputs.GetDlpPoliciesArgs;
import io.github.rpothin.powerplatform.inputs.GetDlpPoliciesPlainArgs;
import io.github.rpothin.powerplatform.inputs.GetDlpPolicyMigrationConfigArgs;
import io.github.rpothin.powerplatform.inputs.GetDlpPolicyMigrationConfigPlainArgs;
import io.github.rpothin.powerplatform.inputs.GetEnvironmentsArgs;
import io.github.rpothin.powerplatform.inputs.GetEnvironmentsPlainArgs;
import io.github.rpothin.powerplatform.inputs.GetFlowsArgs;
import io.github.rpothin.powerplatform.inputs.GetFlowsPlainArgs;
import io.github.rpothin.powerplatform.inputs.GetSecurityRolesArgs;
import io.github.rpothin.powerplatform.inputs.GetSecurityRolesPlainArgs;
import io.github.rpothin.powerplatform.outputs.GetAppsResult;
import io.github.rpothin.powerplatform.outputs.GetConnectorsResult;
import io.github.rpothin.powerplatform.outputs.GetDataRecordsResult;
import io.github.rpothin.powerplatform.outputs.GetDlpPoliciesResult;
import io.github.rpothin.powerplatform.outputs.GetDlpPolicyMigrationConfigResult;
import io.github.rpothin.powerplatform.outputs.GetEnvironmentsResult;
import io.github.rpothin.powerplatform.outputs.GetFlowsResult;
import io.github.rpothin.powerplatform.outputs.GetSecurityRolesResult;
import java.util.concurrent.CompletableFuture;

public final class PowerplatformFunctions {
    /**
     * Lists Power Apps in a Power Platform environment.
     * 
     */
    public static Output<GetAppsResult> getApps(GetAppsArgs args) {
        return getApps(args, InvokeOptions.Empty);
    }
    /**
     * Lists Power Apps in a Power Platform environment.
     * 
     */
    public static CompletableFuture<GetAppsResult> getAppsPlain(GetAppsPlainArgs args) {
        return getAppsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Lists Power Apps in a Power Platform environment.
     * 
     */
    public static Output<GetAppsResult> getApps(GetAppsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getApps", TypeShape.of(GetAppsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists Power Apps in a Power Platform environment.
     * 
     */
    public static Output<GetAppsResult> getApps(GetAppsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getApps", TypeShape.of(GetAppsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists Power Apps in a Power Platform environment.
     * 
     */
    public static CompletableFuture<GetAppsResult> getAppsPlain(GetAppsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("powerplatform:index:getApps", TypeShape.of(GetAppsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists connectors available in a Power Platform environment.
     * 
     */
    public static Output<GetConnectorsResult> getConnectors(GetConnectorsArgs args) {
        return getConnectors(args, InvokeOptions.Empty);
    }
    /**
     * Lists connectors available in a Power Platform environment.
     * 
     */
    public static CompletableFuture<GetConnectorsResult> getConnectorsPlain(GetConnectorsPlainArgs args) {
        return getConnectorsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Lists connectors available in a Power Platform environment.
     * 
     */
    public static Output<GetConnectorsResult> getConnectors(GetConnectorsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getConnectors", TypeShape.of(GetConnectorsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists connectors available in a Power Platform environment.
     * 
     */
    public static Output<GetConnectorsResult> getConnectors(GetConnectorsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getConnectors", TypeShape.of(GetConnectorsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists connectors available in a Power Platform environment.
     * 
     */
    public static CompletableFuture<GetConnectorsResult> getConnectorsPlain(GetConnectorsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("powerplatform:index:getConnectors", TypeShape.of(GetConnectorsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Queries Dataverse records from a collection using OData filter, select, orderby, top, apply, and expand parameters. Returns the first page of matching records. Use the &#39;top&#39; parameter to control result count for large tables.
     * 
     */
    public static Output<GetDataRecordsResult> getDataRecords(GetDataRecordsArgs args) {
        return getDataRecords(args, InvokeOptions.Empty);
    }
    /**
     * Queries Dataverse records from a collection using OData filter, select, orderby, top, apply, and expand parameters. Returns the first page of matching records. Use the &#39;top&#39; parameter to control result count for large tables.
     * 
     */
    public static CompletableFuture<GetDataRecordsResult> getDataRecordsPlain(GetDataRecordsPlainArgs args) {
        return getDataRecordsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Queries Dataverse records from a collection using OData filter, select, orderby, top, apply, and expand parameters. Returns the first page of matching records. Use the &#39;top&#39; parameter to control result count for large tables.
     * 
     */
    public static Output<GetDataRecordsResult> getDataRecords(GetDataRecordsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getDataRecords", TypeShape.of(GetDataRecordsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Queries Dataverse records from a collection using OData filter, select, orderby, top, apply, and expand parameters. Returns the first page of matching records. Use the &#39;top&#39; parameter to control result count for large tables.
     * 
     */
    public static Output<GetDataRecordsResult> getDataRecords(GetDataRecordsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getDataRecords", TypeShape.of(GetDataRecordsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Queries Dataverse records from a collection using OData filter, select, orderby, top, apply, and expand parameters. Returns the first page of matching records. Use the &#39;top&#39; parameter to control result count for large tables.
     * 
     */
    public static CompletableFuture<GetDataRecordsResult> getDataRecordsPlain(GetDataRecordsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("powerplatform:index:getDataRecords", TypeShape.of(GetDataRecordsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists all rule-based DLP (Data Loss Prevention) policies in the tenant.
     * 
     */
    public static Output<GetDlpPoliciesResult> getDlpPolicies() {
        return getDlpPolicies(GetDlpPoliciesArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Lists all rule-based DLP (Data Loss Prevention) policies in the tenant.
     * 
     */
    public static CompletableFuture<GetDlpPoliciesResult> getDlpPoliciesPlain() {
        return getDlpPoliciesPlain(GetDlpPoliciesPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Lists all rule-based DLP (Data Loss Prevention) policies in the tenant.
     * 
     */
    public static Output<GetDlpPoliciesResult> getDlpPolicies(GetDlpPoliciesArgs args) {
        return getDlpPolicies(args, InvokeOptions.Empty);
    }
    /**
     * Lists all rule-based DLP (Data Loss Prevention) policies in the tenant.
     * 
     */
    public static CompletableFuture<GetDlpPoliciesResult> getDlpPoliciesPlain(GetDlpPoliciesPlainArgs args) {
        return getDlpPoliciesPlain(args, InvokeOptions.Empty);
    }
    /**
     * Lists all rule-based DLP (Data Loss Prevention) policies in the tenant.
     * 
     */
    public static Output<GetDlpPoliciesResult> getDlpPolicies(GetDlpPoliciesArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getDlpPolicies", TypeShape.of(GetDlpPoliciesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists all rule-based DLP (Data Loss Prevention) policies in the tenant.
     * 
     */
    public static Output<GetDlpPoliciesResult> getDlpPolicies(GetDlpPoliciesArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getDlpPolicies", TypeShape.of(GetDlpPoliciesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists all rule-based DLP (Data Loss Prevention) policies in the tenant.
     * 
     */
    public static CompletableFuture<GetDlpPoliciesResult> getDlpPoliciesPlain(GetDlpPoliciesPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("powerplatform:index:getDlpPolicies", TypeShape.of(GetDlpPoliciesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Reads an existing DLP policy by ID and returns its configuration ready for use with ResDlpPolicy or powerplatform:index:DlpPolicy. This function is the Pulumi equivalent of the utl-dlppolicy-replicator Terraform module. It is advisory-only: no enforcement or reclassification is applied.
     * 
     */
    public static Output<GetDlpPolicyMigrationConfigResult> getDlpPolicyMigrationConfig(GetDlpPolicyMigrationConfigArgs args) {
        return getDlpPolicyMigrationConfig(args, InvokeOptions.Empty);
    }
    /**
     * Reads an existing DLP policy by ID and returns its configuration ready for use with ResDlpPolicy or powerplatform:index:DlpPolicy. This function is the Pulumi equivalent of the utl-dlppolicy-replicator Terraform module. It is advisory-only: no enforcement or reclassification is applied.
     * 
     */
    public static CompletableFuture<GetDlpPolicyMigrationConfigResult> getDlpPolicyMigrationConfigPlain(GetDlpPolicyMigrationConfigPlainArgs args) {
        return getDlpPolicyMigrationConfigPlain(args, InvokeOptions.Empty);
    }
    /**
     * Reads an existing DLP policy by ID and returns its configuration ready for use with ResDlpPolicy or powerplatform:index:DlpPolicy. This function is the Pulumi equivalent of the utl-dlppolicy-replicator Terraform module. It is advisory-only: no enforcement or reclassification is applied.
     * 
     */
    public static Output<GetDlpPolicyMigrationConfigResult> getDlpPolicyMigrationConfig(GetDlpPolicyMigrationConfigArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getDlpPolicyMigrationConfig", TypeShape.of(GetDlpPolicyMigrationConfigResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Reads an existing DLP policy by ID and returns its configuration ready for use with ResDlpPolicy or powerplatform:index:DlpPolicy. This function is the Pulumi equivalent of the utl-dlppolicy-replicator Terraform module. It is advisory-only: no enforcement or reclassification is applied.
     * 
     */
    public static Output<GetDlpPolicyMigrationConfigResult> getDlpPolicyMigrationConfig(GetDlpPolicyMigrationConfigArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getDlpPolicyMigrationConfig", TypeShape.of(GetDlpPolicyMigrationConfigResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Reads an existing DLP policy by ID and returns its configuration ready for use with ResDlpPolicy or powerplatform:index:DlpPolicy. This function is the Pulumi equivalent of the utl-dlppolicy-replicator Terraform module. It is advisory-only: no enforcement or reclassification is applied.
     * 
     */
    public static CompletableFuture<GetDlpPolicyMigrationConfigResult> getDlpPolicyMigrationConfigPlain(GetDlpPolicyMigrationConfigPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("powerplatform:index:getDlpPolicyMigrationConfig", TypeShape.of(GetDlpPolicyMigrationConfigResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Retrieves a list of Power Platform environments available for the authenticated user.
     * 
     */
    public static Output<GetEnvironmentsResult> getEnvironments() {
        return getEnvironments(GetEnvironmentsArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Retrieves a list of Power Platform environments available for the authenticated user.
     * 
     */
    public static CompletableFuture<GetEnvironmentsResult> getEnvironmentsPlain() {
        return getEnvironmentsPlain(GetEnvironmentsPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Retrieves a list of Power Platform environments available for the authenticated user.
     * 
     */
    public static Output<GetEnvironmentsResult> getEnvironments(GetEnvironmentsArgs args) {
        return getEnvironments(args, InvokeOptions.Empty);
    }
    /**
     * Retrieves a list of Power Platform environments available for the authenticated user.
     * 
     */
    public static CompletableFuture<GetEnvironmentsResult> getEnvironmentsPlain(GetEnvironmentsPlainArgs args) {
        return getEnvironmentsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Retrieves a list of Power Platform environments available for the authenticated user.
     * 
     */
    public static Output<GetEnvironmentsResult> getEnvironments(GetEnvironmentsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getEnvironments", TypeShape.of(GetEnvironmentsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Retrieves a list of Power Platform environments available for the authenticated user.
     * 
     */
    public static Output<GetEnvironmentsResult> getEnvironments(GetEnvironmentsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getEnvironments", TypeShape.of(GetEnvironmentsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Retrieves a list of Power Platform environments available for the authenticated user.
     * 
     */
    public static CompletableFuture<GetEnvironmentsResult> getEnvironmentsPlain(GetEnvironmentsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("powerplatform:index:getEnvironments", TypeShape.of(GetEnvironmentsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists Cloud Flows in a Power Platform environment by querying the Dataverse workflow table (category=5). This approach works with service principal credentials and does not require a per-user Power Automate license. Returns the first page of results; use the &#39;top&#39; parameter to control page size. Note: the service principal must be an Application User with read access to the workflow entity in Dataverse, and will see all flows visible to that principal (not a user-scoped view).
     * 
     */
    public static Output<GetFlowsResult> getFlows(GetFlowsArgs args) {
        return getFlows(args, InvokeOptions.Empty);
    }
    /**
     * Lists Cloud Flows in a Power Platform environment by querying the Dataverse workflow table (category=5). This approach works with service principal credentials and does not require a per-user Power Automate license. Returns the first page of results; use the &#39;top&#39; parameter to control page size. Note: the service principal must be an Application User with read access to the workflow entity in Dataverse, and will see all flows visible to that principal (not a user-scoped view).
     * 
     */
    public static CompletableFuture<GetFlowsResult> getFlowsPlain(GetFlowsPlainArgs args) {
        return getFlowsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Lists Cloud Flows in a Power Platform environment by querying the Dataverse workflow table (category=5). This approach works with service principal credentials and does not require a per-user Power Automate license. Returns the first page of results; use the &#39;top&#39; parameter to control page size. Note: the service principal must be an Application User with read access to the workflow entity in Dataverse, and will see all flows visible to that principal (not a user-scoped view).
     * 
     */
    public static Output<GetFlowsResult> getFlows(GetFlowsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getFlows", TypeShape.of(GetFlowsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists Cloud Flows in a Power Platform environment by querying the Dataverse workflow table (category=5). This approach works with service principal credentials and does not require a per-user Power Automate license. Returns the first page of results; use the &#39;top&#39; parameter to control page size. Note: the service principal must be an Application User with read access to the workflow entity in Dataverse, and will see all flows visible to that principal (not a user-scoped view).
     * 
     */
    public static Output<GetFlowsResult> getFlows(GetFlowsArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getFlows", TypeShape.of(GetFlowsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Lists Cloud Flows in a Power Platform environment by querying the Dataverse workflow table (category=5). This approach works with service principal credentials and does not require a per-user Power Automate license. Returns the first page of results; use the &#39;top&#39; parameter to control page size. Note: the service principal must be an Application User with read access to the workflow entity in Dataverse, and will see all flows visible to that principal (not a user-scoped view).
     * 
     */
    public static CompletableFuture<GetFlowsResult> getFlowsPlain(GetFlowsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("powerplatform:index:getFlows", TypeShape.of(GetFlowsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Fetches Dataverse security roles from a Power Platform environment.
     * 
     */
    public static Output<GetSecurityRolesResult> getSecurityRoles(GetSecurityRolesArgs args) {
        return getSecurityRoles(args, InvokeOptions.Empty);
    }
    /**
     * Fetches Dataverse security roles from a Power Platform environment.
     * 
     */
    public static CompletableFuture<GetSecurityRolesResult> getSecurityRolesPlain(GetSecurityRolesPlainArgs args) {
        return getSecurityRolesPlain(args, InvokeOptions.Empty);
    }
    /**
     * Fetches Dataverse security roles from a Power Platform environment.
     * 
     */
    public static Output<GetSecurityRolesResult> getSecurityRoles(GetSecurityRolesArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getSecurityRoles", TypeShape.of(GetSecurityRolesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Fetches Dataverse security roles from a Power Platform environment.
     * 
     */
    public static Output<GetSecurityRolesResult> getSecurityRoles(GetSecurityRolesArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("powerplatform:index:getSecurityRoles", TypeShape.of(GetSecurityRolesResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Fetches Dataverse security roles from a Power Platform environment.
     * 
     */
    public static CompletableFuture<GetSecurityRolesResult> getSecurityRolesPlain(GetSecurityRolesPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("powerplatform:index:getSecurityRoles", TypeShape.of(GetSecurityRolesResult.class), args, Utilities.withVersion(options));
    }
}
