// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.components;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.rpothin.powerplatform.components.inputs.PipelineEnvironmentEntryArgs;
import io.github.rpothin.powerplatform.components.inputs.PipelineStageConfigArgs;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ResDeploymentPipelineArgs extends com.pulumi.resources.ResourceArgs {

    public static final ResDeploymentPipelineArgs Empty = new ResDeploymentPipelineArgs();

    @Import(name="deploymentPipelineUserRoleId")
    private @Nullable String deploymentPipelineUserRoleId;

    public Optional<String> deploymentPipelineUserRoleId() {
        return Optional.ofNullable(this.deploymentPipelineUserRoleId);
    }

    @Import(name="devEnvironmentKey", required=true)
    private String devEnvironmentKey;

    public String devEnvironmentKey() {
        return this.devEnvironmentKey;
    }

    @Import(name="enableAiDeploymentNotes")
    private @Nullable Boolean enableAiDeploymentNotes;

    public Optional<Boolean> enableAiDeploymentNotes() {
        return Optional.ofNullable(this.enableAiDeploymentNotes);
    }

    @Import(name="enableRedeployment")
    private @Nullable Boolean enableRedeployment;

    public Optional<Boolean> enableRedeployment() {
        return Optional.ofNullable(this.enableRedeployment);
    }

    @Import(name="enableTelemetry")
    private @Nullable Boolean enableTelemetry;

    public Optional<Boolean> enableTelemetry() {
        return Optional.ofNullable(this.enableTelemetry);
    }

    @Import(name="environments", required=true)
    private Map<String,PipelineEnvironmentEntryArgs> environments;

    public Map<String,PipelineEnvironmentEntryArgs> environments() {
        return this.environments;
    }

    @Import(name="hostEnvironmentId", required=true)
    private String hostEnvironmentId;

    public String hostEnvironmentId() {
        return this.hostEnvironmentId;
    }

    @Import(name="lifecycleState")
    private @Nullable String lifecycleState;

    public Optional<String> lifecycleState() {
        return Optional.ofNullable(this.lifecycleState);
    }

    @Import(name="pipelineDescription")
    private @Nullable String pipelineDescription;

    public Optional<String> pipelineDescription() {
        return Optional.ofNullable(this.pipelineDescription);
    }

    @Import(name="pipelineName", required=true)
    private String pipelineName;

    public String pipelineName() {
        return this.pipelineName;
    }

    @Import(name="pipelineStages", required=true)
    private List<PipelineStageConfigArgs> pipelineStages;

    public List<PipelineStageConfigArgs> pipelineStages() {
        return this.pipelineStages;
    }

    @Import(name="rootBusinessUnitId")
    private @Nullable String rootBusinessUnitId;

    public Optional<String> rootBusinessUnitId() {
        return Optional.ofNullable(this.rootBusinessUnitId);
    }

    @Import(name="securityGroupId")
    private @Nullable String securityGroupId;

    public Optional<String> securityGroupId() {
        return Optional.ofNullable(this.securityGroupId);
    }

    private ResDeploymentPipelineArgs() {}

    private ResDeploymentPipelineArgs(ResDeploymentPipelineArgs $) {
        this.deploymentPipelineUserRoleId = $.deploymentPipelineUserRoleId;
        this.devEnvironmentKey = $.devEnvironmentKey;
        this.enableAiDeploymentNotes = $.enableAiDeploymentNotes;
        this.enableRedeployment = $.enableRedeployment;
        this.enableTelemetry = $.enableTelemetry;
        this.environments = $.environments;
        this.hostEnvironmentId = $.hostEnvironmentId;
        this.lifecycleState = $.lifecycleState;
        this.pipelineDescription = $.pipelineDescription;
        this.pipelineName = $.pipelineName;
        this.pipelineStages = $.pipelineStages;
        this.rootBusinessUnitId = $.rootBusinessUnitId;
        this.securityGroupId = $.securityGroupId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ResDeploymentPipelineArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ResDeploymentPipelineArgs $;

        public Builder() {
            $ = new ResDeploymentPipelineArgs();
        }

        public Builder(ResDeploymentPipelineArgs defaults) {
            $ = new ResDeploymentPipelineArgs(Objects.requireNonNull(defaults));
        }

        public Builder deploymentPipelineUserRoleId(@Nullable String deploymentPipelineUserRoleId) {
            $.deploymentPipelineUserRoleId = deploymentPipelineUserRoleId;
            return this;
        }

        public Builder devEnvironmentKey(String devEnvironmentKey) {
            $.devEnvironmentKey = devEnvironmentKey;
            return this;
        }

        public Builder enableAiDeploymentNotes(@Nullable Boolean enableAiDeploymentNotes) {
            $.enableAiDeploymentNotes = enableAiDeploymentNotes;
            return this;
        }

        public Builder enableRedeployment(@Nullable Boolean enableRedeployment) {
            $.enableRedeployment = enableRedeployment;
            return this;
        }

        public Builder enableTelemetry(@Nullable Boolean enableTelemetry) {
            $.enableTelemetry = enableTelemetry;
            return this;
        }

        public Builder environments(Map<String,PipelineEnvironmentEntryArgs> environments) {
            $.environments = environments;
            return this;
        }

        public Builder hostEnvironmentId(String hostEnvironmentId) {
            $.hostEnvironmentId = hostEnvironmentId;
            return this;
        }

        public Builder lifecycleState(@Nullable String lifecycleState) {
            $.lifecycleState = lifecycleState;
            return this;
        }

        public Builder pipelineDescription(@Nullable String pipelineDescription) {
            $.pipelineDescription = pipelineDescription;
            return this;
        }

        public Builder pipelineName(String pipelineName) {
            $.pipelineName = pipelineName;
            return this;
        }

        public Builder pipelineStages(List<PipelineStageConfigArgs> pipelineStages) {
            $.pipelineStages = pipelineStages;
            return this;
        }

        public Builder pipelineStages(PipelineStageConfigArgs... pipelineStages) {
            return pipelineStages(List.of(pipelineStages));
        }

        public Builder rootBusinessUnitId(@Nullable String rootBusinessUnitId) {
            $.rootBusinessUnitId = rootBusinessUnitId;
            return this;
        }

        public Builder securityGroupId(@Nullable String securityGroupId) {
            $.securityGroupId = securityGroupId;
            return this;
        }

        public ResDeploymentPipelineArgs build() {
            if ($.devEnvironmentKey == null) {
                throw new MissingRequiredPropertyException("ResDeploymentPipelineArgs", "devEnvironmentKey");
            }
            if ($.environments == null) {
                throw new MissingRequiredPropertyException("ResDeploymentPipelineArgs", "environments");
            }
            if ($.hostEnvironmentId == null) {
                throw new MissingRequiredPropertyException("ResDeploymentPipelineArgs", "hostEnvironmentId");
            }
            if ($.pipelineName == null) {
                throw new MissingRequiredPropertyException("ResDeploymentPipelineArgs", "pipelineName");
            }
            if ($.pipelineStages == null) {
                throw new MissingRequiredPropertyException("ResDeploymentPipelineArgs", "pipelineStages");
            }
            return $;
        }
    }

}
