// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.rpothin.powerplatform.components;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ResDlpPolicyArgs extends com.pulumi.resources.ResourceArgs {

    public static final ResDlpPolicyArgs Empty = new ResDlpPolicyArgs();

    @Import(name="displayName", required=true)
    private String displayName;

    public String displayName() {
        return this.displayName;
    }

    @Import(name="enableTelemetry")
    private @Nullable Boolean enableTelemetry;

    public Optional<Boolean> enableTelemetry() {
        return Optional.ofNullable(this.enableTelemetry);
    }

    @Import(name="ruleSets")
    private @Nullable List<Object> ruleSets;

    public Optional<List<Object>> ruleSets() {
        return Optional.ofNullable(this.ruleSets);
    }

    private ResDlpPolicyArgs() {}

    private ResDlpPolicyArgs(ResDlpPolicyArgs $) {
        this.displayName = $.displayName;
        this.enableTelemetry = $.enableTelemetry;
        this.ruleSets = $.ruleSets;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ResDlpPolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ResDlpPolicyArgs $;

        public Builder() {
            $ = new ResDlpPolicyArgs();
        }

        public Builder(ResDlpPolicyArgs defaults) {
            $ = new ResDlpPolicyArgs(Objects.requireNonNull(defaults));
        }

        public Builder displayName(String displayName) {
            $.displayName = displayName;
            return this;
        }

        public Builder enableTelemetry(@Nullable Boolean enableTelemetry) {
            $.enableTelemetry = enableTelemetry;
            return this;
        }

        public Builder ruleSets(@Nullable List<Object> ruleSets) {
            $.ruleSets = ruleSets;
            return this;
        }

        public Builder ruleSets(Object... ruleSets) {
            return ruleSets(List.of(ruleSets));
        }

        public ResDlpPolicyArgs build() {
            if ($.displayName == null) {
                throw new MissingRequiredPropertyException("ResDlpPolicyArgs", "displayName");
            }
            return $;
        }
    }

}
