// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Inputs
{

    /// <summary>
    /// Licensing settings.
    /// </summary>
    public sealed class TenantLicensingSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Disable billing policy creation by non-admin users.
        /// </summary>
        [Input("disableBillingPolicyCreationByNonAdminUsers")]
        public Input<bool>? DisableBillingPolicyCreationByNonAdminUsers { get; set; }

        /// <summary>
        /// Disable use of unassigned AI Builder credits.
        /// </summary>
        [Input("disableUseOfUnassignedAIBuilderCredits")]
        public Input<bool>? DisableUseOfUnassignedAIBuilderCredits { get; set; }

        /// <summary>
        /// Enable tenant capacity report for environment admins.
        /// </summary>
        [Input("enableTenantCapacityReportForEnvironmentAdmins")]
        public Input<bool>? EnableTenantCapacityReportForEnvironmentAdmins { get; set; }

        /// <summary>
        /// Enable tenant licensing report for environment admins.
        /// </summary>
        [Input("enableTenantLicensingReportForEnvironmentAdmins")]
        public Input<bool>? EnableTenantLicensingReportForEnvironmentAdmins { get; set; }

        /// <summary>
        /// Storage capacity consumption warning threshold.
        /// </summary>
        [Input("storageCapacityConsumptionWarningThreshold")]
        public Input<int>? StorageCapacityConsumptionWarningThreshold { get; set; }

        public TenantLicensingSettingsArgs()
        {
        }
        public static new TenantLicensingSettingsArgs Empty => new TenantLicensingSettingsArgs();
    }
}
