// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

/**
 * Azure billing instrument (subscription) details for a billing policy.
 */
export interface BillingInstrumentArgs {
    /**
     * The billing instrument identifier.
     */
    id?: pulumi.Input<string>;
    /**
     * The Azure resource group within the subscription.
     */
    resourceGroup?: pulumi.Input<string>;
    /**
     * The Azure subscription ID.
     */
    subscriptionId?: pulumi.Input<string>;
}

/**
 * OData $expand parameter for a navigation property in getDataRecords.
 */
export interface DataRecordsExpandParam {
    /**
     * OData filter expression for the expanded entity.
     */
    filter?: string;
    /**
     * The navigation property name to expand.
     */
    navigationProperty: string;
    /**
     * Comma-separated list of columns to include for the expanded entity.
     */
    select?: string;
}

/**
 * OData $expand parameter for a navigation property in getDataRecords.
 */
export interface DataRecordsExpandParamArgs {
    /**
     * OData filter expression for the expanded entity.
     */
    filter?: pulumi.Input<string>;
    /**
     * The navigation property name to expand.
     */
    navigationProperty: pulumi.Input<string>;
    /**
     * Comma-separated list of columns to include for the expanded entity.
     */
    select?: pulumi.Input<string>;
}

/**
 * Configuration for the Dataverse database associated with a Power Platform environment.
 */
export interface DataverseArgs {
    /**
     * Whether the Dataverse instance is in administration mode.
     */
    administrationModeEnabled?: pulumi.Input<boolean>;
    /**
     * Whether background operations are enabled during administration mode.
     */
    backgroundOperationEnabled?: pulumi.Input<boolean>;
    /**
     * Currency code for the Dataverse database (e.g. USD). Immutable after creation.
     */
    currencyCode?: pulumi.Input<string>;
    /**
     * Domain prefix for the Dataverse instance URL.
     */
    domainName?: pulumi.Input<string>;
    /**
     * Base language LCID (e.g. 1033). Immutable after creation.
     */
    languageCode?: pulumi.Input<number>;
    /**
     * Dataverse organization GUID. Computed.
     */
    organizationId?: pulumi.Input<string>;
    /**
     * AAD security group GUID restricting environment access.
     */
    securityGroupId?: pulumi.Input<string>;
    /**
     * JSON metadata for provisioning templates. Immutable after creation.
     */
    templateMetadata?: pulumi.Input<string>;
    /**
     * Provisioning templates (e.g. D365_Sales). Immutable after creation.
     */
    templates?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Dataverse unique name. Computed.
     */
    uniqueName?: pulumi.Input<string>;
    /**
     * URL of the Dataverse instance. Computed.
     */
    url?: pulumi.Input<string>;
    /**
     * Dataverse version string. Computed.
     */
    version?: pulumi.Input<string>;
}

/**
 * An enterprise policy associated with a Power Platform environment.
 */
export interface EnterprisePolicyArgs {
    /**
     * The resource ID of the policy.
     */
    id?: pulumi.Input<string>;
    /**
     * Azure region of the policy.
     */
    location?: pulumi.Input<string>;
    /**
     * Policy link status (e.g. Linked, Disabled).
     */
    status?: pulumi.Input<string>;
    /**
     * System-assigned ID of the policy.
     */
    systemId?: pulumi.Input<string>;
    /**
     * Policy type (e.g. NetworkInjection, Encryption, Identity).
     */
    type?: pulumi.Input<string>;
}

/**
 * A rule set for a DLP policy, defining data loss prevention rules.
 */
export interface RuleSetArgs {
    /**
     * The unique identifier of the rule set.
     */
    id?: pulumi.Input<string>;
    /**
     * The inputs for the rule set, which may vary based on the rule.
     */
    inputs?: pulumi.Input<{[key: string]: any}>;
    /**
     * The version of the rule set.
     */
    version?: pulumi.Input<string>;
}

/**
 * Catalog settings.
 */
export interface TenantCatalogSettingsArgs {
    /**
     * Power Catalog audience setting.
     */
    powerCatalogAudienceSetting?: pulumi.Input<string>;
}

/**
 * Champions settings.
 */
export interface TenantChampionsSettingsArgs {
    /**
     * Disable champions invitation reachout.
     */
    disableChampionsInvitationReachout?: pulumi.Input<boolean>;
    /**
     * Disable skills match invitation reachout.
     */
    disableSkillsMatchInvitationReachout?: pulumi.Input<boolean>;
}

/**
 * Environment settings.
 */
export interface TenantEnvironmentsSettingsArgs {
    /**
     * Disable preferred data location for Teams environment creation.
     */
    disablePreferredDataLocationForTeamsEnvironment?: pulumi.Input<boolean>;
}

/**
 * Governance policy settings.
 */
export interface TenantGovernancePolicySettingsArgs {
    /**
     * Enable desktop flow data policy management.
     */
    enableDesktopFlowDataPolicyManagement?: pulumi.Input<boolean>;
}

/**
 * Governance settings.
 */
export interface TenantGovernanceSettingsArgs {
    /**
     * Disable admin digest.
     */
    disableAdminDigest?: pulumi.Input<boolean>;
    /**
     * Disable developer environment creation by non-admin users.
     */
    disableDeveloperEnvironmentCreationByNonAdminUsers?: pulumi.Input<boolean>;
    /**
     * Enable default environment routing.
     */
    enableDefaultEnvironmentRouting?: pulumi.Input<boolean>;
    /**
     * Route all makers to personal dev environments.
     */
    environmentRoutingAllMakers?: pulumi.Input<boolean>;
    /**
     * Target environment group for default environment routing.
     */
    environmentRoutingTargetEnvironmentGroupId?: pulumi.Input<string>;
    /**
     * Target security group for default environment routing.
     */
    environmentRoutingTargetSecurityGroupId?: pulumi.Input<string>;
    /**
     * Governance policy settings.
     */
    policy?: pulumi.Input<inputs.TenantGovernancePolicySettingsArgs>;
}

/**
 * Intelligence settings.
 */
export interface TenantIntelligenceSettingsArgs {
    /**
     * Disable Copilot.
     */
    disableCopilot?: pulumi.Input<boolean>;
    /**
     * Enable OpenAI bot publishing.
     */
    enableOpenAiBotPublishing?: pulumi.Input<boolean>;
}

/**
 * Licensing settings.
 */
export interface TenantLicensingSettingsArgs {
    /**
     * Disable billing policy creation by non-admin users.
     */
    disableBillingPolicyCreationByNonAdminUsers?: pulumi.Input<boolean>;
    /**
     * Disable use of unassigned AI Builder credits.
     */
    disableUseOfUnassignedAIBuilderCredits?: pulumi.Input<boolean>;
    /**
     * Enable tenant capacity report for environment admins.
     */
    enableTenantCapacityReportForEnvironmentAdmins?: pulumi.Input<boolean>;
    /**
     * Enable tenant licensing report for environment admins.
     */
    enableTenantLicensingReportForEnvironmentAdmins?: pulumi.Input<boolean>;
    /**
     * Storage capacity consumption warning threshold.
     */
    storageCapacityConsumptionWarningThreshold?: pulumi.Input<number>;
}

/**
 * Model experimentation settings.
 */
export interface TenantModelExperimentationSettingsArgs {
    /**
     * Disable data logging.
     */
    disableDataLogging?: pulumi.Input<boolean>;
    /**
     * Enable model data sharing.
     */
    enableModelDataSharing?: pulumi.Input<boolean>;
}

/**
 * Power Apps settings.
 */
export interface TenantPowerAppsSettingsArgs {
    /**
     * Disable connection sharing with everyone.
     */
    disableConnectionSharingWithEveryone?: pulumi.Input<boolean>;
    /**
     * Disable create from Figma.
     */
    disableCreateFromFigma?: pulumi.Input<boolean>;
    /**
     * Disable create from image.
     */
    disableCreateFromImage?: pulumi.Input<boolean>;
    /**
     * Disable maker match.
     */
    disableMakerMatch?: pulumi.Input<boolean>;
    /**
     * Disable share with everyone.
     */
    disableShareWithEveryone?: pulumi.Input<boolean>;
    /**
     * Disable unused license assignment.
     */
    disableUnusedLicenseAssignment?: pulumi.Input<boolean>;
    /**
     * Enable guests to make apps.
     */
    enableGuestsToMake?: pulumi.Input<boolean>;
}

/**
 * Power Automate settings.
 */
export interface TenantPowerAutomateSettingsArgs {
    /**
     * Disable Copilot for Power Automate.
     */
    disableCopilot?: pulumi.Input<boolean>;
}

/**
 * Power Pages settings.
 */
export interface TenantPowerPagesSettingsArgs {
}

/**
 * Power Platform workload settings at tenant scope.
 */
export interface TenantPowerPlatformSettingsArgs {
    /**
     * Catalog settings.
     */
    catalogSettings?: pulumi.Input<inputs.TenantCatalogSettingsArgs>;
    /**
     * Champions settings.
     */
    champions?: pulumi.Input<inputs.TenantChampionsSettingsArgs>;
    /**
     * Environment settings.
     */
    environments?: pulumi.Input<inputs.TenantEnvironmentsSettingsArgs>;
    /**
     * Governance settings.
     */
    governance?: pulumi.Input<inputs.TenantGovernanceSettingsArgs>;
    /**
     * Intelligence settings.
     */
    intelligence?: pulumi.Input<inputs.TenantIntelligenceSettingsArgs>;
    /**
     * Licensing settings.
     */
    licensing?: pulumi.Input<inputs.TenantLicensingSettingsArgs>;
    /**
     * Model experimentation settings.
     */
    modelExperimentation?: pulumi.Input<inputs.TenantModelExperimentationSettingsArgs>;
    /**
     * Power Apps settings.
     */
    powerApps?: pulumi.Input<inputs.TenantPowerAppsSettingsArgs>;
    /**
     * Power Automate settings.
     */
    powerAutomate?: pulumi.Input<inputs.TenantPowerAutomateSettingsArgs>;
    /**
     * Power Pages settings.
     */
    powerPages?: pulumi.Input<inputs.TenantPowerPagesSettingsArgs>;
    /**
     * Search settings.
     */
    search?: pulumi.Input<inputs.TenantSearchSettingsArgs>;
    /**
     * Teams integration settings.
     */
    teamsIntegration?: pulumi.Input<inputs.TenantTeamsIntegrationSettingsArgs>;
    /**
     * User management settings.
     */
    userManagementSettings?: pulumi.Input<inputs.TenantUserManagementSettingsArgs>;
}

/**
 * Search settings.
 */
export interface TenantSearchSettingsArgs {
    /**
     * Disable Bing video search.
     */
    disableBingVideoSearch?: pulumi.Input<boolean>;
    /**
     * Disable community search.
     */
    disableCommunitySearch?: pulumi.Input<boolean>;
    /**
     * Disable docs search.
     */
    disableDocsSearch?: pulumi.Input<boolean>;
}

/**
 * Teams integration settings.
 */
export interface TenantTeamsIntegrationSettingsArgs {
    /**
     * Share with colleagues user limit.
     */
    shareWithColleaguesUserLimit?: pulumi.Input<number>;
}

/**
 * User management settings.
 */
export interface TenantUserManagementSettingsArgs {
    /**
     * Enable delete disabled user in all environments.
     */
    enableDeleteDisabledUserInAllEnvironments?: pulumi.Input<boolean>;
}
