// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Inputs
{

    /// <summary>
    /// OData $expand parameter for a navigation property in getDataRecords.
    /// </summary>
    public sealed class DataRecordsExpandParam : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// OData filter expression for the expanded entity.
        /// </summary>
        [Input("filter")]
        public string? Filter { get; set; }

        /// <summary>
        /// The navigation property name to expand.
        /// </summary>
        [Input("navigationProperty", required: true)]
        public string NavigationProperty { get; set; } = null!;

        /// <summary>
        /// Comma-separated list of columns to include for the expanded entity.
        /// </summary>
        [Input("select")]
        public string? Select { get; set; }

        public DataRecordsExpandParam()
        {
        }
        public static new DataRecordsExpandParam Empty => new DataRecordsExpandParam();
    }
}
