// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Inputs
{

    /// <summary>
    /// User management settings.
    /// </summary>
    public sealed class TenantUserManagementSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable delete disabled user in all environments.
        /// </summary>
        [Input("enableDeleteDisabledUserInAllEnvironments")]
        public Input<bool>? EnableDeleteDisabledUserInAllEnvironments { get; set; }

        public TenantUserManagementSettingsArgs()
        {
        }
        public static new TenantUserManagementSettingsArgs Empty => new TenantUserManagementSettingsArgs();
    }
}
