// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Inputs
{

    /// <summary>
    /// Champions settings.
    /// </summary>
    public sealed class TenantChampionsSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Disable champions invitation reachout.
        /// </summary>
        [Input("disableChampionsInvitationReachout")]
        public Input<bool>? DisableChampionsInvitationReachout { get; set; }

        /// <summary>
        /// Disable skills match invitation reachout.
        /// </summary>
        [Input("disableSkillsMatchInvitationReachout")]
        public Input<bool>? DisableSkillsMatchInvitationReachout { get; set; }

        public TenantChampionsSettingsArgs()
        {
        }
        public static new TenantChampionsSettingsArgs Empty => new TenantChampionsSettingsArgs();
    }
}
