// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerplatform.Inputs
{

    /// <summary>
    /// Catalog settings.
    /// </summary>
    public sealed class TenantCatalogSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Power Catalog audience setting.
        /// </summary>
        [Input("powerCatalogAudienceSetting")]
        public Input<string>? PowerCatalogAudienceSetting { get; set; }

        public TenantCatalogSettingsArgs()
        {
        }
        public static new TenantCatalogSettingsArgs Empty => new TenantCatalogSettingsArgs();
    }
}
