// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Lists Power Apps in a Power Platform environment.
 */
export function getApps(args: GetAppsArgs, opts?: pulumi.InvokeOptions): Promise<GetAppsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("powerplatform:index:getApps", {
        "environmentId": args.environmentId,
    }, opts);
}

export interface GetAppsArgs {
    /**
     * The ID of the environment to list apps for.
     */
    environmentId: string;
}

export interface GetAppsResult {
    /**
     * The list of Power Apps.
     */
    readonly apps: outputs.AppSummary[];
}
/**
 * Lists Power Apps in a Power Platform environment.
 */
export function getAppsOutput(args: GetAppsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAppsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("powerplatform:index:getApps", {
        "environmentId": args.environmentId,
    }, opts);
}

export interface GetAppsOutputArgs {
    /**
     * The ID of the environment to list apps for.
     */
    environmentId: pulumi.Input<string>;
}
