// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Reads an existing DLP policy by ID and returns its configuration ready for use with ResDlpPolicy or powerplatform:index:DlpPolicy. This function is the Pulumi equivalent of the utl-dlppolicy-replicator Terraform module. It is advisory-only: no enforcement or reclassification is applied.
 */
export function getDlpPolicyMigrationConfig(args: GetDlpPolicyMigrationConfigArgs, opts?: pulumi.InvokeOptions): Promise<GetDlpPolicyMigrationConfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("powerplatform:index:getDlpPolicyMigrationConfig", {
        "sourcePolicyId": args.sourcePolicyId,
    }, opts);
}

export interface GetDlpPolicyMigrationConfigArgs {
    /**
     * The ID of the source DLP policy to read migration configuration from.
     */
    sourcePolicyId: string;
}

export interface GetDlpPolicyMigrationConfigResult {
    /**
     * Display name of the source DLP policy. Use as the displayName input for ResDlpPolicy.
     */
    readonly displayName: string;
    /**
     * Display name of the source DLP policy. Use as the name input for powerplatform:index:DlpPolicy.
     */
    readonly name: string;
    /**
     * Rule set configurations from the source policy, ready for input to ResDlpPolicy or DlpPolicy.
     */
    readonly ruleSets: outputs.RuleSet[];
}
/**
 * Reads an existing DLP policy by ID and returns its configuration ready for use with ResDlpPolicy or powerplatform:index:DlpPolicy. This function is the Pulumi equivalent of the utl-dlppolicy-replicator Terraform module. It is advisory-only: no enforcement or reclassification is applied.
 */
export function getDlpPolicyMigrationConfigOutput(args: GetDlpPolicyMigrationConfigOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDlpPolicyMigrationConfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("powerplatform:index:getDlpPolicyMigrationConfig", {
        "sourcePolicyId": args.sourcePolicyId,
    }, opts);
}

export interface GetDlpPolicyMigrationConfigOutputArgs {
    /**
     * The ID of the source DLP policy to read migration configuration from.
     */
    sourcePolicyId: pulumi.Input<string>;
}
