// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages an ISV (Independent Software Vendor) contract for Power Platform licensing.
 */
export class IsvContract extends pulumi.CustomResource {
    /**
     * Get an existing IsvContract resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): IsvContract {
        return new IsvContract(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'powerplatform:index:IsvContract';

    /**
     * Returns true if the given object is an instance of IsvContract.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IsvContract {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IsvContract.__pulumiType;
    }

    /**
     * The timestamp when the ISV contract was created.
     */
    declare public /*out*/ readonly createdOn: pulumi.Output<string | undefined>;
    /**
     * The geographic region of the ISV contract.
     */
    declare public readonly geo: pulumi.Output<string>;
    /**
     * The timestamp when the ISV contract was last modified.
     */
    declare public /*out*/ readonly lastModifiedOn: pulumi.Output<string | undefined>;
    /**
     * The name of the ISV contract.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The status of the ISV contract.
     */
    declare public readonly status: pulumi.Output<string | undefined>;

    /**
     * Create a IsvContract resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IsvContractArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.geo === undefined && !opts.urn) {
                throw new Error("Missing required property 'geo'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["geo"] = args?.geo;
            resourceInputs["name"] = args?.name;
            resourceInputs["status"] = args?.status;
            resourceInputs["createdOn"] = undefined /*out*/;
            resourceInputs["lastModifiedOn"] = undefined /*out*/;
        } else {
            resourceInputs["createdOn"] = undefined /*out*/;
            resourceInputs["geo"] = undefined /*out*/;
            resourceInputs["lastModifiedOn"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IsvContract.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a IsvContract resource.
 */
export interface IsvContractArgs {
    /**
     * The geographic region for the ISV contract (e.g., unitedstates, europe). Immutable after creation.
     */
    geo: pulumi.Input<string>;
    /**
     * The name of the ISV contract.
     */
    name: pulumi.Input<string>;
    /**
     * The status of the ISV contract: Enabled or Disabled.
     */
    status?: pulumi.Input<string>;
}
